### ISSUE TITLE
Android: multiple custom dimensions result in incorrect multiple analytics hits

### ISSUE THREAD

**Issue by gatkinsNZ** [danwilson/google-analytics-plugin#100]
Hi. While integrating in this great plugin I came across an issue with custom dimensions.

When you have multiple dimensions added, screen views (and I believe events too) get logged multiple times in Google Analytics. This is because when one of the plugin's track analytics methods is called it adds each custom dimensions via an [individual tracking call](https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L134)

```
tracker.send(new HitBuilders
                    .AppViewBuilder()
                    .setCustomDimension((Integer.parseInt(key)), value).build());
```

**Comment by danwilson** [comment]
Thanks for the fix - I finally merged it yesterday (sorry for the delay)!

**Comment by maheshwarLigade** [comment]
Hi. On single screen i want to set the multiple custom dimension how I should  set. using array or any thing else.
 mTracker.send(new HitBuilders.ScreenViewBuilder()
                .setCustomDimension(dimension, dimentionValue)
                .setCustomDimension(dimension, dimentionValue)
                .setCustomDimension(dimension, dimentionValue)
                .setCustomDimension(dimension, dimentionValue)
                .build()

Is it right way or any other solution. because on the same screen the dimension should be any number of.
