### ISSUE TITLE
Big file size

### ISSUE THREAD

**Issue by calebeaires** [danwilson/google-analytics-plugin#104]
The lib google analytics size is to big. How does this affect on the apk/ipa file size?

**Comment by gatkinsNZ** [comment]
Hi. I assume you are talking about the google play services client side
lib.

If using eclipse you can turn on proguard which shrinks it right down (to
around .05 Mb), or if Android Studio I believe you can choose to only
include the analytics part of Google play services.

**Comment by danwilson** [comment]
It can make the app size bigger, but aside from what @gatkinsNZ mentioned, there is nothing this plugin can do to minimize that file size since it is simply a plugin that uses the existing library from Google.
