### ISSUE TITLE
Error: analytics is not defined

### ISSUE THREAD

**Issue by technotip** [danwilson/google-analytics-plugin#107]
I've installed the plugin - I can locate it inside plugins folder.

Here is my code:

app.js
<code>
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {

 if(typeof analytics !== undefined) {
    analytics.startTrackerWithId('UA-2320664-14');
            } else {
                console.log('Google Analytics Unavailable');
            }

  });
})
</code>

Still I get the following error in my Chrome Console Window.
Uncaught ReferenceError: analytics is not defined(anonymous function) @ app.js:47(anonymous function) @ ionic.bundle.js:44806onPlatformReady @ ionic.bundle.js:2445onWindowLoad @ ionic.bundle.js:2426
ionic.bundle.js:20306 ReferenceError: analytics is not defined

**Comment by sh3nan1gans** [comment]
I don't think the plugin gets loaded when debugging in a browser. You'll need to run your app on an emulator or an actual device. Also, my app checks for analytics like so:
if (typeof analytics !== "undefined")

I'm not sure if it really matters...but it might help you if you run into a problem.
Hope this helps.

**Comment by technotip** [comment]
ya, the plugin doesn't load when debugging in a browser, so I got confused. But it's working perfectly fine in the device. Thanks :)

**Comment by CreativeManix** [comment]
will the plugin works with chrome inspect? i.e. my app is still runs on device, but using chrome to inspect
