### ISSUE TITLE
GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

### ISSUE THREAD

**Issue by jonystorm** [danwilson/google-analytics-plugin#108]
This appears on JS console (not tracking any events):

GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

**Comment by mackenrou** [comment]
+1

**Comment by JosMarRivera** [comment]
+1

**Comment by gatkinsNZ** [comment]
You can apparently just ignore this error - I get it too but it doesn't cause me any issues.

See this: http://stackoverflow.com/questions/18068627/logcat-message-the-google-play-services-resources-were-not-found-check-your-pr
