### ISSUE TITLE
Null tracking ID on Android, even tracking ID is set right after deviceready

### ISSUE THREAD

**Issue by ricolo** [danwilson/google-analytics-plugin#109]
I use ngCordova wrapper of this plugin and have the tracking ID set in the main controller (which is loaded once the app starts).

```
        $ionicPlatform.ready(function () {
            $timeout(function () {
                $cordovaGoogleAnalytics.startTrackerWithId(trackingId);
                $cordovaGoogleAnalytics.debugMode();
                $cordovaGoogleAnalytics.trackView('TestingTrackView');
            }, 2000);
        });
```

On Android, the trackView() call immediately following startTrackerWithId() also works as expected according to the log:

```
V/GAV4    ( 4439): GET /collect?sr=1080x1776&ht=1431959653462&cd=TestingTrackView&_u=.nK-AL&cid=7f5a72cf-1a28-40ec-a2cf-a947714967d5&_v=ma4.0.2&av=0.0.1&a=1095338038&v=1&an=isp&ul=en-us&t=screenview&tid=UA-XXXXXXXX-3&aid=com.ionicframework.isp845770&qt=10014&z=117 HTTP/1.1
```

However for all subsequent manual navigations, the tracking ID becomes null (**tid=null**) on Android:

```
V/GAV4    ( 4439): GET /collect?sr=1080x1776&ht=1431959675056&cd=%2Fapp%2Fauthor&_u=.rK-AL&cid=7f5a72cf-1a28-40ec-a2cf-a947714967d5&_v=ma4.0.2&av=0.0.1&a=395223038&v=1&an=isp&ul=en-us&t=screenview&tid=null&aid=com.ionicframework.isp845770&qt=22192&z=119 HTTP/1.1
V
```

Refer to the code snippet, I have to set the timeout above 3000 ms for all subsequent manual navigations with the tracking ID populated. It seems like some resource is not completely ready when the tracking ID is set, and $ionicPlatform.ready() cannot help on this issue. As a reference, the same code base works well on iOS even without $timeout().

**Comment by danwilson** [comment]
Do you know if this is still happening? I was never able to reproduce on Android.

**Comment by ricolo** [comment]
I can still reproduce the issue by removing the timeout(). I'm using the following specifications:
- Genymotion Nexus 5 emulator
- cordova android 4.1.1
- cordova-plugin-google-analytics version 0.7.1
- ionic 1.1.0
- ngCordova 0.1.20-alpha

BTW, another user also experienced the same [issue](https://github.com/danwilson/google-analytics-plugin/issues/112#issuecomment-108509101) and resolved through timeout().

**Comment by danwilson** [comment]
The only thing I can spot here is that the two times this has been reported it was on a Genymotion emulator.  Have you tried on an actual device?

**Comment by ricolo** [comment]
Just tested on an actual Android device - with zero millisecond timeout, tracking is not working (probably due to null tracking ID, but I don't know how to output the console log on an actual device like it does in genymotion). Once I restore the timeout, it's working again.

**Comment by ricolo** [comment]
Sorry just found that it's not working even with timeout on my android device. Let me check again and confirm later.

**Comment by ricolo** [comment]
Tested on a Nexus 6P device with Android 6.0 and confirmed that tracking ID was missing without timeout.

**Comment by victorsosa** [comment]
please try again using the last release.

**Comment by webdwarf** [comment]
Hi,
help me please, I have no tracking on android, work on IOS.
This is my index.js for android :
----------------------------------------------------------------------------------
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
       
        function _waitForAnalytics(){
            if(typeof analytics !== 'undefined'){
                window.ga.debugMode();
                window.ga.startTrackerWithId('UA-87838250-1');
                window.ga.trackView('APP first screen');
            }
            else{
                setTimeout(function(){
                    _waitForAnalytics();
                },250);
            }
        };
        _waitForAnalytics();
        

    },
----------------------------------------------------------------------------------
cordova 6.1
com.danielcwilson.plugins.googleanalytics@1.8.1

**Comment by victorsosa** [comment]
@webdwarf the debugmode() call goes after the startTrackerWithId()

Also the last version is 1.7.1, I think that is a typo.

**Comment by martyzz1** [comment]
Also, I think as has been suggested by others you could wrap your trackView in the success callback 

```
window.ga.startTrackerWithId('UA-87838250-1', 30, function(msg) {
    console.log('Tracker start success', msg)
    window.ga.debugMode()
    window.ga.trackView('APP first screen');
});
```

This works for me, but also be aware it can take several minutes before the hits appear on googles realtime view...

**Comment by webdwarf** [comment]
perfect thanks

**Comment by victorsosa** [comment]
closed old issue

**Comment by saisatya525** [comment]
i have the issue with ios with ionic 3,result saying null for start trackid ....for android everything is fine
