### ISSUE TITLE
Warning : Object //github.com/danwilson/google-analytics-plugin.git has no method 'join'

### ISSUE THREAD

**Issue by payalcsureja** [danwilson/google-analytics-plugin#110]
When you try to add/remove plugin via grunt command like

grunt plugin:add:https://github.com/danwilson/google-analytics-plugin.git

It gives you warning and stops process

Warning : Object //github.com/danwilson/google-analytics-plugin.git has no method 'join'

**Comment by danwilson** [comment]
The plugin should be added with the cordova cli or phonegap cli.
