### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by edschiffer** [danwilson/google-analytics-plugin#112]
Dear Dan,
everywhere I search about integrating Google Analytics into a Cordova app I see your plugin, and yet I can't make it work.

I'm using 
.  Cordova 4.1.2
.  Node 0.10.35
.  Android 4.4.2 API 19
and plugins
.  com.google.playservices
.  org.apache.cordova.console
.  org.apache.cordova.device

I've installed via _"cordova plugin add https://github.com/danwilson/google-analytics-plugin.git"_ and added the _"window.analytics.startTrackerWithId('UA-XXXX-YY')"_ line inside _"onDeviceReady: function() {"_ on index.js with my correspondent UA code.

at Google Analytics I've set a Mobile Property and I'm not getting any data. Tried emulating on Genymotion and serving the app on Chrome.

sorry if it is too lame, but I'm afraid if it is a version conflict.

**Comment by gatkinsNZ** [comment]
Is this on Android or ios or both? And are you using the native IDEs to
compile the app or phonegap build?

Have you used debugmode() to see what is being sent through (using
debugger). Also have you tried a trackview() call after
startTrackerWithId() as I am not sure if startTrackerWithId() itself
actually sends anything to analytics.

If on Android are you using proguard to compress as this can cause probs
without the right settings.

**Comment by gatkinsNZ** [comment]
Just saw you are referring to chrome and a emulator. It won't work when
running the app in a browser on your pc, and would be best to test the
issue on a real device

**Comment by tabrindle** [comment]
Also keep in mind data is not instantaneous coming through GA. I know it sucks, but wait 24 hours to make sure its really not working.

**Comment by gatkinsNZ** [comment]
You should though hopefully see it in the real time data view (well could
be delayed 10 to 20 mins)

**Comment by edschiffer** [comment]
thanks for the quick reply, gatkinsNZ and tabrindle. I'll check all these.
I'm building for both Android and iOS, and I'm using Phonegap build.

does this plugin work slower then the normal site-analytics connection? because I use it with my website and I can check almost instantaneous when someone gets online.

and yes, I gave about a week and yet no user was accounted on the app. on Chrome I was using "cordova serve" to check it. still not sure how Cordova handles its plugins when serving, but I at least expected the Genymotion emulation to account users.

**Comment by gatkinsNZ** [comment]
Cordova serve won't work as that is just displaying the app in a desktop
browser,  correct? It therefore doesn't have any of the plugin/android/iOS
code required.

I would think it would work in an emulator, but nothing beats a real
device. You might want to consider running it through Android Studio so you
can see errors and debugmode() output, etc.

**Comment by cgmcrae** [comment]
Having a similar issue, placed startTrackerWithID() and trackview() inside OnDeviceReady function, but nothing has shown up on my google analytics page in the past 48 hours. I am also running it on an Android device running 4.3.

**Comment by gatkinsNZ** [comment]
Have you tried the plugin's debug mode and looking at logcat messages in
eclipse/android studio? Also have you made sure your app has the right
permissions and you have added domains into the Cordova whitelist?

I've just successfully implemented this myself in the last month or so, so
it should work for you.

**Comment by ricolo** [comment]
I have a similar issue (https://github.com/danwilson/google-analytics-plugin/issues/109) and it seems onDeviceReady is not enough for it to completely initialized, because the tracking ID becomes null in subsequent navigations. I eventually resort to timeout() function to wait for at least 3 seconds before calling startTrackerWithID() for this to work.

**Comment by ricolo** [comment]
As a side note, this issue only appears in Android. I don't need the timeout() function for it to work properly in iOS emulator.

**Comment by cgmcrae** [comment]
Just wanted to document my process to make sure I am not doing anything wrong.

1) Created new Cordova project (using default HelloCordova app)
2) Added google-analytics-plugin using CLI
3)In 'index.js', edited onDeviceReady to be
'  onDeviceReady: function() {
        app.receivedEvent('deviceready');
        window.analytics.startTrackerWithID('UA-[tracking ID]');
        window.analytics.trackView('Home Page');
    }, '
4) Deployed onto HTC One running Android 4.3
5) Opened app, checked google analytics at 5 minute increments for one hour, nothing appeared.

**Comment by edschiffer** [comment]
we have just figured it out, it indeed neeed a timeout() function, ricolo. thanks!
we discovered if the methods were loading using Chrome console plugged into a Android mobile.

**Comment by ramsabarish** [comment]
I too have the same problem and things didn't work even after using setTimeout for 3 sec. 

I have created an account on Google Analytics and got a tracking ID. Installed the plugin and called the following methods on deviceReady:

function onDeviceReady() {
	 setTimeout(function(){ 

		  window.analytics.startTrackerWithId('UA-64XXXX77-1',
                       function(response){
			             alert(JSON.stringify(response));
		               },
                       function(error){
			             alert(JSON.stringify(error));
		              });

		  window.analytics.debugMode();  
                
	 }, 3000);	
}

After that there was an alert saying "tracker started" but no data is shown on Google Analytics reports for last 6 hours. The LogCat shows an error for missing Google Play Services i.e. "The Google Play services resources were not found. Check your project configuration to ensure that the resources are included". Is it because of the missing Google Play Services resource, I'm unable to get the Google Analytics reports. Kindly help me out.  

I'm using the following specifications:
1. cordova-plugin-google-analytics 0.7.2
2. cordova 4.0.0
3. Android device Moto-G, OS 4.4.4

**Comment by ramsabarish** [comment]
Everything works fine, the reports are updated after every 24 hours.

**Comment by kaansoral** [comment]
I was also having issues, turns out you definitely need the manual .trackView on mobile

I also can't catch the android logs with my logcat usage, however the iOS logs are verbose enough

**Comment by cemerson** [comment]
I've combed through the issues here but think I have to jump in on this one too. Seems like there are a few diff issues in this thread but I'm not sure if mine is a dup or unique. 

My startTrackerWithID() seems to go fine and my trackView() calls look pretty good ... but nothing is showing up in GA. And just to rule out the lag/delay that is often associated with GA tracking ... I can throw page tracking calls with the same UA ID from a website and see instant real-time data - so this isn't a Google Analytics lag thing. 

Here's a snapshot from my Xcode log ... note the data:error bit towards the bottom - only thing that looks off. But again, after all the above, nothing shows up in GA ... (and I've watched for 30-60 minutes).

````javascript
GoogleAnalytics 3.10 -[GAIBatchingDispatcher persist:] 
    (GAIBatchingDispatcher.m:497): Saved hit: {
    parameters =     {
        "&_crc" = 0;
        "&_u" = ".oK-L";
        "&_v" = "mi3.1.0";
        "&a" = 00000000; // altered for code-sharing security
        "&aid" = "io.cordova.hellocordova";
        "&an" = HelloCordova;
        "&av" = "0.0.1";
        "&cd" = TESTPAGENAMEHERE;
        "&cid" = "000000000-0000-0000-00000-000000000"; // altered for code-sharing security
        "&ds" = app;
        "&sr" = 320x568;
        "&t" = screenview;
        "&tid" = "UA-00000000-XX"; // altered for code-sharing security
        "&ul" = en;
        "&v" = 1;
        "&z" = 14436701015031726792;
        gaiVersion = "3.10";
    };
    timestamp = "2015-07-30 11:45:59 +0000";
}

2015-07-30 07:46:08.665 HelloCordova[31134:2083617] 
    GoogleAnalytics 3.10 -[GAIRequestBuilder requestPostUrl:payload:compression:] 
        (GAIRequestBuilder.m:167): building URLRequest for https://ssl.google-analytics.com/batch

2015-07-30 07:46:08.666 HelloCordova[31134:2083617] 
    GoogleAnalytics 3.10 -[GAIBatchingDispatcher dispatchWithCompletionHandler:] 
        (GAIBatchingDispatcher.m:612): Sending hit(s) POST: https://ssl.google-analytics.com/batch

2015-07-30 07:46:08.711 HelloCordova[31134:2083505] 
    GoogleAnalytics 3.10 -[GAIBatchingDispatcher didSendHits:response:data:error:] 
        (GAIBatchingDispatcher.m:208): Hit(s) dispatched: HTTP status 200

2015-07-30 07:46:08.713 HelloCordova[31134:2083617] 
    GoogleAnalytics 3.10 -[GAIBatchingDispatcher deleteHits:] 
        (GAIBatchingDispatcher.m:509): hit(s) Successfully deleted

2015-07-30 07:46:08.715 HelloCordova[31134:2083617] 
    GoogleAnalytics 3.10 -[GAIBatchingDispatcher didSendHits:] 
        (GAIBatchingDispatcher.m:219): 2 hit(s) sent

````

I tried an earlier version of the GA SDK [cited here](https://stackoverflow.com/questions/24955138/google-analytics-3-08-ios-idfa-class-missing-wont-collect-idfa/24957329#24957329) but that didn't seem to change anything.  I'm also not getting any SSL/HTTP complaints from Xcode - so I don't think this is some whitelist/network issue.

Thanks for any advice/help anyone can offer.
