### ISSUE TITLE
How to trigger event on ng-click?

### ISSUE THREAD

**Issue by varunis** [danwilson/google-analytics-plugin#113]
I am successfully able to trigger events from a controller.
I want to trigger analytics events on ng-click in the template. I am trying to do that like this:
```
<ion-list>
    <ion-item nav-clear menu-close ng-click="analytics.trackEvent('Dashboard', 'dashboard clicked');" ui-sref="app.dashboard">
         Dashboard
    </ion-item>
</ion-list>
```
But this doesn't work. I am doing something wrong?

**Comment by amritk** [comment]
I'm not 100% sure, but it could be that analytics doesn't exist in that scope. You could always add it to your rootscope:

```
$rootScope.analytics = {
    trackEvent: analytics.trackEvent
};
```

**Comment by Deminetix** [comment]
This is an angular question. Never the less, you have 2 click handlers on your ion-item `ui-sref` and `ng-click` which is bound to cause you headaches. A better solution would be to use `ng-click="goDashboard()"` and then in your controller:

    $scope.goDashboard = function () {
        analytics.trackEvent('Dashboard', 'dashboard clicked');
        $state.go('app.dashboard');
    });

Obviously you'll need to inject `$state` and `analytics` into your controller. You can omit analytics if you dont have a service wrapper
