### ISSUE TITLE
[Android] java: package com.google.android.gms.analytics does not exist

### ISSUE THREAD

**Issue by hannahcin** [danwilson/google-analytics-plugin#114]
Hi dan,
I followed your installation steps and the plugin works smoothly with iOS. However, for Android, I cannot compile my project due to these errors:

Error:(3, 40) java: package com.google.android.gms.analytics does not exist
Error:(4, 47) java: package com.google.android.gms.analytics.Logger does not exist
Error:(5, 40) java: package com.google.android.gms.analytics does not exist
Error:(6, 40) java: package com.google.android.gms.analytics does not exist
Error:(34, 12) java: cannot find symbol
  symbol:   class Tracker
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin
Error:(129, 47) java: cannot find symbol
  symbol:   class Tracker
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin
Error:(111, 23) java: cannot find symbol
  symbol:   variable GoogleAnalytics
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin
Error:(114, 13) java: cannot find symbol
  symbol:   variable GoogleAnalytics
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin
Error:(135, 21) java: package HitBuilders does not exist
Error:(151, 21) java: package HitBuilders does not exist
Error:(170, 21) java: package HitBuilders does not exist
Error:(193, 21) java: package HitBuilders does not exist
Error:(214, 21) java: package HitBuilders does not exist
Error:(237, 21) java: package HitBuilders does not exist
Error:(262, 21) java: package HitBuilders does not exist
Error:(279, 89) java: cannot find symbol
  symbol:   variable LogLevel
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin
Error:(279, 9) java: cannot find symbol
  symbol:   variable GoogleAnalytics
  location: class com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin

Please advise...

**Comment by hannahcin** [comment]
Cordova v.4.2.0
Android SDK v19

**Comment by mapierce** [comment]
+1

**Comment by emilgp** [comment]
+1
cordova 5.0.0
android sdk 21(for crosswalk) and 22 (target)

**Comment by hannahcin** [comment]
Update: I followed the setup for google play services here: https://developers.google.com/android/guides/setup ("Other" tab, because I was using Android Studio without Gradle)

Then after a cordova build android, I went into Android Studio and followed these steps:
Go to File -> Project Structure
Select 'Project Settings'
Select 'Dependencies' Tab
Click '+' and select '1.Library Dependencies'
Search for : com.google.android.gms:play-services
Select the latest version and click 'OK'

This fixed the issue for me. :fist:

**Comment by amritk** [comment]
had the same issue, completely removed and reinitiated my project and it started working

**Comment by danwilson** [comment]
Closed with #118

**Comment by skhouseholder** [comment]
I was having this error and other peoples' fixes didn't work for me, so hopefully this will help someone now that I've solved my issue:

If you're getting this error when you run `ant release`, [this issue](https://github.com/floatinghotpot/cordova-admob-pro/issues/179) may help. tl;dr: you're not supposed to be running `ant release`.
