### ISSUE TITLE
Application Download Referral

### ISSUE THREAD

**Issue by albaraam** [danwilson/google-analytics-plugin#116]
does it support application download referral??

**Comment by ashishsajwan** [comment]
:+1:  does it support application download referral?? @danwilson @mgerlach-klick

**Comment by danwilson** [comment]
Can you explain what this is, please? Thanks!

**Comment by Bnaya** [comment]
@danwilson he means this thing:
https://developers.google.com/analytics/devguides/collection/android/v4/campaigns

**Comment by albaraamishlawi** [comment]
Thanks @Bnaya that's exactly what I meant

**Comment by danwilson** [comment]
Thanks! It is not currently, but there is a PR that needs some attention that should bring it in.
