### ISSUE TITLE
Cause builds to failed because using deprecated "com.google.playservices"

### ISSUE THREAD

**Issue by TGNC-dev** [danwilson/google-analytics-plugin#117]
Hi,

This plugin is causing troubles because of using "com.google.playservices", which is now deprecated. I can not build anymore if i use it with https://github.com/floatinghotpot/cordova-admob-pro installed.

So is it possible to fix it? Or can someone just give my a hint on what to do so i can do it myself?

Thanks by advance

**Comment by Daz66** [comment]
Hi,

I've got exactly the same problem too.
Does anyone have a solution or any guidance?

Thanks, Daz

**Comment by danwilson** [comment]
Closed with #118
