### ISSUE TITLE
setAnonymizeIp for privacy issues

### ISSUE THREAD

**Issue by jeresiv** [danwilson/google-analytics-plugin#119]
I need to be able to set anonymizeIP to true for privacy concerns can a method or flag be added for this functionality?

https://developers.google.com/android/reference/com/google/android/gms/analytics/Tracker#setAnonymizeIp(boolean)

**Comment by Hirbod** [comment]
+1

**Comment by mpoisot** [comment]
duplicate of #83

**Comment by danwilson** [comment]
Duplicate of #83
