### ISSUE TITLE
Plugin add issue

### ISSUE THREAD

**Issue by prosenjit-itobuz** [danwilson/google-analytics-plugin#125]
Plugin not added 
error log
`cordova plugin add https://github.com/danwilson/google-analytics-plugin.git
Fetching plugin "https://github.com/danwilson/google-analytics-plugin.git" via git clone
Repository "https://github.com/danwilson/google-analytics-plugin.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/var/folders/l1/wpyp22b95f3dz4p7szrb9mz80000gn/T/git/1436939939096/LICENSE'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)`

what is the problem?

**Comment by MS-elug** [comment]
It's an issue with the latest version of cordova build.

You can manually retrofit the changes in your npm cache:
https://github.com/apache/cordova-lib/commit/66007122d1d8096aae2142f24f83c6ded20e6d8d

**Comment by canadaka** [comment]
I have been using this plugin for months and mine won't install now as well.

````
Failed to install 'cordova-plugin-google-analytics':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
````

Running:
ionic@1.0.1
cordova@4.3.1
android@3.7.2

**Comment by jroji** [comment]
Hi all,

i have the same issue than @canadaka since the latest commits. I saw that you update from google-play-services dependency to framework on the plugin xml, and now is not working after using it for months. Could we use the working version before the commits, or should we modify something on the cordova construction?

Running:
cordova@3.6.3-0.2.13

**Comment by prosenjit-itobuz** [comment]
This was an issue with Cordova CLi vs 5.1.1. When I rolled back issues solved.

**Comment by canadaka** [comment]
I think my issue might have been that the new `framework` tag only works with Android platform 4 which requires Cordova 5. I can't update to Cordova 5 yet, so I instead just made a fork of this project reverting to the old `dependancy` tag.
