### ISSUE TITLE
iOS addTransactionItem and addTransaction methods do not work

### ISSUE THREAD

**Issue by usselva** [danwilson/google-analytics-plugin#128]
iOS addTransactionItem and addTransaction methods do not work. These methods do not send the number value such as revenue, tax, shipping, price, quantity etc. 

This seems to be because the assignment of NSString to NSNumber directly which causes these values to be not sent. The following fix seem to work for this:

Original Code:
        price = [command.arguments objectAtIndex:4];

Modified Code : 
        NSNumberFormatter *f = [[NSNumberFormatter alloc] init];
        f.numberStyle = NSNumberFormatterDecimalStyle;
        price = [f numberFromString:[command.arguments objectAtIndex:4]];

Doing similar formatting to all the number fields make these two methods to send those fields to the Google Servers correctly. Please review this and if this look good apply this fix.

**Comment by danwilson** [comment]
I have not seen an issue with these not working... can you show an example of what you are sending in code, and maybe a sample of what is being shown in GA (if it is partial)?  Thanks!

**Comment by victorsosa** [comment]
I will take a look at this when I had some time. But also this is going to be deprecated soon for the new e-commerce api.

**Comment by victorsosa** [comment]
releated to issue #81

**Comment by Graham-C** [comment]
@usselva Have you seen transactions come through in GA for iOS at all? I have never been able to get any transaction to appear for iOS. Screen views come through fine for both but only Android transactions appear.
Could you share your full code for UniversalAnalyticsPlugin.m please?

**Comment by victorsosa** [comment]
This was fixed, Now the is a NSNumber pointer
