### ISSUE TITLE
java.lang.ClassNotFoundException: com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin

### ISSUE THREAD

**Issue by Fabii23** [danwilson/google-analytics-plugin#130]
java.lang.ClassNotFoundException: com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin

java.lang.ClassNotFoundException: Didn't find class "com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin" on path: DexPathList[[zip file "/data/app/-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Error adding plugin com.danielcwilson.plugins.analytics.UniversalAnalyticsPlugin

java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference

**Comment by danwilson** [comment]
Sorry... a log without any other information is not helpful. What is the actual issue here? When is it happening? What versions of the CLI and Platforms are you using?
