### ISSUE TITLE
Cordova build android error

### ISSUE THREAD

**Issue by glucoz** [danwilson/google-analytics-plugin#134]
I have install the plugin with the cordova CLI (cordova 4.2) : 
cordova plugin add com.danielcwilson.plugins.googleanalytics

It work fine on the IOS project, but i have this error when i build the Android project.

/Users/corwin/Documents/_CORDOVA/WSBR/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ENOENT, no such file or directory '/Users/corwin/Documents/adt-bundle-mac-x86_64-20131030/sdk/com.google.android.gms:play-services-analytics:+/build.xml'

I have already install the "Google play services" and "Google repository". 

Thanks for your help

**Comment by ndacosta** [comment]
Install Android Support Repository

**Comment by glucoz** [comment]
i do install Android Support Repository, but same error

**Comment by ndacosta** [comment]
I had the same error and installed Android Support Repository and Android Support Library, then removed android platform and the plugin and finally added again platform and plugin. try again. I hope you resolve your problem.

**Comment by streetkid** [comment]
I have the same error. There is no such file ! the only file structure for the play-services I can find is adt-bundle-xxx/sdk/extras/google/google_play_services/ and inside there is no build.xml

**Comment by glucoz** [comment]
Thank you ndacosta, BUILD SUCCESSFUL !

**Comment by cemerson** [comment]
@glucoz  / @ndacosta  Please tell me there is some way around this w/out having to remove/re-add the android platform ?

**Comment by ndacosta** [comment]
I don't know. it work for me after remove/re-add the android platform. may
be there is a way to update the platform.

**Comment by cemerson** [comment]
I found a couple possible leads ... 

````
// File 1: C:\myapp\platforms\android\local.properties
sdk.dir=/Users/Me/Documents/Development/adt-bundle-mac/sdk

// File 2:  C:\myapp\platforms\android\project.properties
android.library.reference.2=../../../../../../../../Documents/Development/adt-bundle-mac/sdk/com.google.android.gms:play-services-analytics:+
android.library.reference.3=../../../../../../../../Documents/Development/adt-bundle-mac/sdk/com.google.android.gms:play-services-analytics:+
android.library.reference.4=../../../../../../../../Documents/Development/adt-bundle-mac/sdk/com.google.android.gms:play-services-analytics:+
````

but even after fixing them to use the updated/correct paths the dang thing still threw (other) errors. Gah ... man I hate removing/adding platforms! Someone really needs to find a way to spare us all from having to do that soon - so frustrating to have to re-setup platforms each time (mainly the splash/icon stuff).

**Comment by ndacosta** [comment]
you can add the splash/icon stuff to the main config, something like this
<platform name="android">
        <splash src="res/screen/android/splash_200x320.png" density="ldpi"
/>
        <splash src="res/screen/android/splash_320x480.png" density="mdpi"
/>
        <splash src="res/screen/android/splash_480x800.png" density="hdpi"
/>
        <splash src="res/screen/android/splash_720x1280.png"
density="xhdpi" />

        <icon src="res/icon/android/icon_36x36.png" density="ldpi" />
        <icon src="res/icon/android/icon_48x48.png" density="mdpi" />
        <icon src="res/icon/android/icon_72x72.png" density="hdpi" />
        <icon src="res/icon/android/icon_96x96.png" density="xhdpi" />
    </platform>

**Comment by cemerson** [comment]
That works now? I gave up on that stuff long ago but will give it another shot.

**Comment by ndacosta** [comment]
it works for me with the splashscreen plugin (cordova-plugin-splashscreen)
