### ISSUE TITLE
Bitcode support? (iOS9 / Xcode 7)

### ISSUE THREAD

**Issue by cemerson** [danwilson/google-analytics-plugin#136]
Anyone know when the Google Analytics SDK and/or this plugin will be updated to support the new BITCODE silliness introduced in iOS 9 / Xcode 7? This is a repeat of the [Google Groups question here](https://groups.google.com/forum/#!topic/ga-mobile-app-analytics/d6ML4BKBBeY) but I thought I'd post here since, IMHO, Dan's plugin here is currently *the* best option for Cordova Google Analytics integration.

**Comment by aderowbotham** [comment]
Ah... presumably (in fact, fairly conclusively) this is why I am getting this then:

`com.danielcwilson.plugins.googleanalytics/libGoogleAnalyticsServices.a(TAGDataProvider.o)'
 does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by aderowbotham** [comment]
...ok, setting `Enable Bitcode` to `"No"` project-wide (in both CordovaLib.xcodeproj and the parent project) seems to be a workaround.

**Comment by MosheBerman** [comment]
Will bitcode be supported in the near future?

**Comment by cemerson** [comment]
@aderowbotham  / @MosheBerman  - not sure yet but I think the first step is finding out when the Google Analytics SDK for iOS (libGoogleAnalyticsServices.a?) will get updated with Bitcode support. That, I believe, is what no one has responded to yet. That's what the Google Groups question above (https://goo.gl/vmcwdq) is asking about ... which sadly no one has responded to for over a month since it was posted.

**Comment by rromanchuk** [comment]
...and now gold master is out. If it's anything like arm64 support, I'd imagine a 5-6month wait before this is supported. http://stackoverflow.com/questions/18934043/unable-to-link-googleanalytics-3-01-with-xcode-5-missing-required-architecture

**Comment by billinghamj** [comment]
Issue is being tracked here: https://code.google.com/p/analytics-issues/issues/detail?id=671

**Comment by SylvainAtHON** [comment]
the issue is fix on google side:
https://code.google.com/p/analytics-issues/issues/detail?id=671#c92
can you integrate version 3.14 ?

**Comment by danwilson** [comment]
PR #163 and #164

**Comment by extempl** [comment]
Still have problem with `libGoogleAnalyticsServices.a(TAGHit.o)' does not contain bitcode`.
