### ISSUE TITLE
Cannot use/revert to v0.7.1 getting error 304

### ISSUE THREAD

**Issue by renesansz** [danwilson/google-analytics-plugin#137]
Everytime I install a specific version for the plugin it returns me an error:
![error](http://i.imgur.com/WDRSBSu.png)

**Comment by Deminetix** [comment]
Not sure if ionic handles that correctly, try putting it in your package.json in the cordovaPlugins array

**Comment by DreamYahia** [comment]
take a look on this reply
https://github.com/danwilson/google-analytics-plugin/issues/165#issuecomment-151263435
