### ISSUE TITLE
Is there a way to reset or re-initialize GA tracking after initializing once?

### ISSUE THREAD

**Issue by cemerson** [danwilson/google-analytics-plugin#138]
It appears that once you call the initial startTrackerWithId() method for this plugin you can't get it to re-init with a different GA UAID. Is there a way to do this w/the current methods available? Something like: stopTracker()?

**Comment by danwilson** [comment]
Once this has an Android component I will merge.  I will look into adding it.

**Comment by victorsosa** [comment]
fix on issue  #195
