### ISSUE TITLE
No campaign data found issue

### ISSUE THREAD

**Issue by nehatha** [danwilson/google-analytics-plugin#139]
I am getting the same issue.
The below is the logcat on init.

08-19 12:58:12.688: V/GAV3(3920): Thread[GAThread,5,main]: connecting to Analytics service
08-19 12:58:12.708: V/GAV3(3920): Thread[GAThread,5,main]: connect: bindService returned true for Intent { act=com.google.android.gms.analytics.service.START cmp=com.google.android.gms/.analytics.service.AnalyticsService (has extras) }
08-19 12:58:12.708: V/GAV3(3920): Thread[main,5,main]: service connected, binder: android.os.BinderProxy@42f784c8
08-19 12:58:12.708: V/GAV3(3920): Thread[main,5,main]: bound to service
08-19 12:58:12.708: V/GAV3(3920): Thread[main,5,main]: Connected to service
08-19 12:58:12.708: V/GAV3(3920): Thread[GAThread,5,main]: Loaded clientId
08-19 12:58:12.718: I/GAV3(3920): Thread[GAThread,5,main]: No campaign data found.

Please need a solution.

**Comment by danwilson** [comment]
I'm sorry, I don't understand the issue.

**Comment by engincancan** [comment]
I tried it with latest version 0.8.1 and it works. Here is an example;
`adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n com.example.application/com.google.android.gms.analytics.CampaignTrackingReceiver --es "referrer" "utm_source=testSource&utm_medium=testMedium&utm_term=testTerm&utm_content=testContent&utm_campaign=testCampaign1"`

`Thread[GAThread,9,main]: Campaign found: utm_source=testSource`

This issue can be closed.

**Comment by amolc** [comment]
Can you please help of how we can call a function to record campaign data through the plugin.

Google Analytics Notes - 
https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#general-campaigns

I tried to check your readme.md and we do not have enough information to record campaign information.

Thanks

**Comment by raviagarwal292** [comment]
@victorsosa could you please add a feature for campaign tracking as its one of the most important and killer feature for anyone to know where their app installation is coming from.

Reference link How do I implement Campaign tracking with Cordova?

Regards
Ravi Agarwal

**Comment by raviagarwal292** [comment]
@danwilson  could you please add a feature for campaign tracking as its one of the most important and killer feature for anyone to know where their app installation is coming from.

Reference link How do I implement Campaign tracking with Cordova?

Regards
Ravi Agarwal

**Comment by victorsosa** [comment]
releated to #68

**Comment by victorsosa** [comment]
PR #264 sent
