### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sirMuffles91** [danwilson/google-analytics-plugin#140]
I added this plugin, set the .run directive. built the project and it failed to build. removed the code and plug, still wont build, I am getting the error:

AILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-analytics:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-analytics/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-analytics/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-analytics/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/google/android/gms/play-services-analytics/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

How do I fix this? I see that the dependency is sitting in the build.gradle file but dont know what the heck is generating it...

**Comment by willgeiger** [comment]
Any resolution to this? I'm having the same problem with Cordova Android 5.1.1.

**Comment by sidlauskaslukas** [comment]
Which version do you use? 8.0+ doesn't work with Cordova 5.x, so my suggestion would be to use an earlier version: 
cordova plugin add cordova-plugin-google-analytics@0.7.1

**Comment by danwilson** [comment]
You might need to add the Google Play Services SDK via the [Android SDK Manager](https://developer.android.com/sdk/installing/adding-packages.html).  I've updated the README with this information as well.  Let me know if that helps.

**Comment by piotrowski** [comment]
I had the same error with another plugin (founds this by googling for "Could not find any version that matches com.google.android.gms:play-services-analytics:+."). Additionally to Play Services SDK I also had to install the Google Repository.

**Comment by georgir** [comment]
with cordova-plugin-google-analytics@0.7.1 I get another error:
Error: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.

**Comment by Waog** [comment]
Adding _Google Play services_ and _Google Repository_ via _Android SDK Manager_ solved the problem for me:
![image](https://cloud.githubusercontent.com/assets/5098472/16038450/4d052328-3225-11e6-8287-cbd54993052e.png)

**Comment by victorsosa** [comment]
This is a missing dependency issue, won't fix.
