### ISSUE TITLE
Plugin no longer compatible with newest Android Studio

### ISSUE THREAD

**Issue by nitzanwilnai** [danwilson/google-analytics-plugin#142]
In the newest version 4 of Google Analytics libGoogleAnalyticsServices.jar is no longer used:
https://developers.google.com/analytics/devguides/collection/android/v4/

Including it causes a conflict with AdMob and google-play-services.jar

**Comment by danwilson** [comment]
libGoogleAnalyticsServices.jar has not been included since January with commit 9c1e87bda5585ce6c0e2f0321bc74cc13382acdb . Not sure what version you have been using, but you likely simply need to upgrade - thanks!
