### ISSUE TITLE
Plugin fails to build on Android. Cannot revert to 0.7.1

### ISSUE THREAD

**Issue by hasandogu** [danwilson/google-analytics-plugin#145]
I just installed this plugin but I am getting the following error. Any insight into why I might be getting this?

I noted the readme suggesting to revert to 0.7.1 in case of problems with the latest version on Android. However, 0.7.1 doesn't exist on plugins.cordova.io.

1>  Installing Android library: com.google.android.gms:play-services-analytics:+
1>  Error during processing of action! Attempting to revert...
1>  Failed to install 'cordova-plugin-google-analytics':TypeError Uh oh!
1>  Arguments to path.resolve must be strings
1>      at Object.win32.resolve (path.js:146:13)
1>      at module.exports.framework.install (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
1>      at Object.ActionStack.process (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
1>      at handleInstall (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
1>      at D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
1>      at _fulfilled (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:787:54)
1>      at self.promiseDispatch.done (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:816:30)
1>      at Promise.promise.promiseDispatch (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:749:13)
1>      at D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:509:49
1>      at flush (D:\Users\HasanDogu\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.0\node_modules\cordova\node_modules\q\q.js:108:17)
1>  TypeError: Uh oh!
1>  Arguments to path.resolve must be strings

**Comment by jdgeier** [comment]
I am having this issue as well.

**Comment by asanin-2sol** [comment]
When I reverted to 0.7.1 I had the same problem.

Removing and re-adding the android platform solved the problem for me.

**Comment by DreamYahia** [comment]
take a look on this reply
https://github.com/danwilson/google-analytics-plugin/issues/165#issuecomment-151263435

**Comment by danwilson** [comment]
closing with workaround from @DreamYahia - thanks
