### ISSUE TITLE
libGoogleAnalyticsServices.a(TAGDataProvider.o)' does not contain bitcode

### ISSUE THREAD

**Issue by nodesocket** [danwilson/google-analytics-plugin#148]
How can I fix this error?

`ld: '/Users/justin/Sites/my-app/phonegap/platforms/ios/Commando/Plugins/com.danielcwilson.plugins.googleanalytics/libGoogleAnalyticsServices.a(TAGDataProvider.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by FdezRomero** [comment]
I'm having a similar problem with version 0.8.0, added from NPM. Targeting iOS 8.0 with the 9.0 SDK GM.

```text
ld: '/Users/Rodrigo/Git/iOS9/platforms/ios/Savelist/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGHit.o)' does not contain bitcode.
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by FdezRomero** [comment]
I just found a workaround by setting `Project > Build Settings > Build Options > Enable Bitcode = No`, as mentioned by @aderowbotham in #136.

**Comment by prcela** [comment]
Note: Keep in mind that disabling bitcode will also disable app thinning.

**Comment by FdezRomero** [comment]
@prcela Wow that sucks... I had no idea. Thanks for mentioning it.

**Comment by bradleyflood** [comment]
Same error since upgrading to Xcode 7.0.

**Comment by andrewb273** [comment]
Likewise having this issue, currently disabled bitcode

**Comment by alejandromagnorsky** [comment]
+1

**Comment by animista01** [comment]
+1. Waiting for a fix.

**Comment by myyellowshoe** [comment]
+1

**Comment by alejandromagnorsky** [comment]
+1

**Comment by ventayol** [comment]
+1

**Comment by heks** [comment]
+1

**Comment by cdbconcepts** [comment]
I think this is an issue with the Google Analytics SDK first and foremost... needs to be updated with bitcode support in order for this plugin to get updated.

**Comment by JWesorick** [comment]
+1

**Comment by ordinaryman09** [comment]
+1

**Comment by billinghamj** [comment]
The bug in the actual GA SDK is being tracked here: https://code.google.com/p/analytics-issues/issues/detail?id=671

**Comment by MohammedPPE** [comment]
+1
getting angry on this issue. Why nobody from google is responding for this?

**Comment by YissacharB** [comment]
I had this issue and i have found a workaround 
I've added the folowing line 'ENABLE_BITCODE = NO' to 'platforms/ios/cordova/build.xcconfig' before the build.
And it worked for me.

**Comment by jtomaszewski** [comment]
Thanks for workaround, @YissacharB .

I've just created a `hooks/before_compile/disable_bitcode_on_ios.sh` file:
```sh
#!/bin/sh

# Exit, if there's no ios here.
[[ $CORDOVA_PLATFORMS == *"ios"* ]] || exit 0

# This is needed until https://github.com/danwilson/google-analytics-plugin/issues/148 gets fixed.
if ! cat "platforms/ios/cordova/build.xcconfig" | grep -q "ENABLE_BITCODE"; then
  echo "ENABLE_BITCODE = NO" >> platforms/ios/cordova/build.xcconfig
fi
```

**Comment by tobiasoleary** [comment]
On Oct 9th Google finally responded at https://code.google.com/p/analytics-issues/issues/detail?id=671

> We thank everyone for their patience as we are actively working to get the new SDK released as soon as possible. As work around it is possible to build and deploy projects that have the current Google Analytics SDK with bitcode disabled for iOS targets and with watchOS targets with bitcode enabled.
>
>There is an example on stackoverflow on how to disable bitcode.
> http://stackoverflow.com/questions/30848208/new-warnings-in-ios9
>
> There there are also reports that the related xcode distribution profile signing issue for applications with this configuration is resolved with Xcode 7.1 beta 3:
> https://forums.developer.apple.com/thread/9734

**Comment by danwilson** [comment]
PR #163 and #164

**Comment by lferro9000** [comment]
If you are using cocoapods, you can add this at the end of the Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

This will recurse through all the pods and mark the ENABLE_BITCODE off. Naturally, you will not be able to compile for the watch / apple tv (as they require it on some versions)

**Comment by jonathanlking** [comment]
+1
