### ISSUE TITLE
AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices

### ISSUE THREAD

**Issue by cloakedninjas** [danwilson/google-analytics-plugin#150]
```
W/GAv4(10565): AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.

W/GAv4(10565): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
```

When I built a debug version of my app, I saw analytics events appear. But now I've built and deployed a release build, I see these errors in my logcat. Any ideas?

**Comment by cloakedninjas** [comment]
Ok - slight correction, both debug and release builds reported this error. Following [This SO post](http://stackoverflow.com/questions/30154057/analyticsservice-not-registered-in-the-app-manifest-error) I added the following into my <application> section of the AndroidManifest:

```xml
<receiver android:enabled="true" android:name="com.google.android.gms.analytics.AnalyticsReceiver">
    <intent-filter>
        <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
    </intent-filter>
</receiver>
<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.analytics.AnalyticsService" />
```

This is a bit of a hack though, since the `AndroidManifest.xml` is volatile and not in SCM, I think this might need to be copied in with a Cordova hook.

**Comment by dwmkerr** [comment]
+1 Adding the following to my `AndroidManifest.xml` file solved the problem for me:

```xml
<receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false"/>

        <!-- Optionally, register CampaignTrackingReceiver and CampaignTrackingService to enable
             installation campaign reporting -->
        <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
```

**Comment by dwmkerr** [comment]
+1 Adding the following to my `AndroidManifest.xml` file solved the problem for me:

```xml
        <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false"/>

        <!-- Optionally, register CampaignTrackingReceiver and CampaignTrackingService to enable
             installation campaign reporting -->
        <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
```

This is with Cordova 5.2.0, an android Nexus 5 emulator and everything else being pretty vanilla. It looks like this is an issue if the device does not have the latest version of Google Play Services installed.

**Comment by dwmkerr** [comment]
Forking now to make a fix, a small adjustment to the config should do it.

**Comment by cloakedninjas** [comment]
FWIW, I created a Grunt task in my build process to ensure the `AndroidManifest.xml` is valid.

https://gist.github.com/cloakedninjas/7263284b9a938a1a6567

Not 100% fool proof when it deals with the `<receiver>` and `<service>` tags, but suffices for my project.

**Comment by dwmkerr** [comment]
@cloakedninjas: that's a nice solution!

**Comment by dwmkerr** [comment]
@danwilson @cloakedninjas fix for the above issue available in PR #151 if you need it!

**Comment by maheshwarLigade** [comment]
I Got Exception:

 Successfully bound to service but never got onServiceConnected callback.

I register all in Manifest.xml
  
        <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver"
            android:enabled="true">
            <intent-filter>
                <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.AnalyticsService"
            android:enabled="true"
            android:exported="false"/>

        
        <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <service android:name="com.google.android.gms.analytics.CampaignTrackingService" />

**Comment by m-adil** [comment]
I tried all of these suggested solutions but none of these worked for me. I actually just updated my cordova to 6.2.0 and android platform to 5.1.1 and now getting this warning:
`W/PluginManager: THREAD WARNING: exec() call to UniversalAnalytics.setUserId blocked the main thread for 24ms. Plugin should use CordovaInterface.getThreadPool().`

and that error:
`W/CordovaPlugin: Attempted to send a second callback for ID: UniversalAnalytics1023676980
                                Result was: "Invalid action"`

Any other proper fix please?
