### ISSUE TITLE
Enable GA 'Remarketing and Advertising Reporting Features' ?

### ISSUE THREAD

**Issue by kevin-finesse** [danwilson/google-analytics-plugin#153]
I've used this plugin on several phonegap build apps and have always been delighted with how simple it is to install and use - many thanks. Now I have a client that wants to enable the google analytics 'remarketing and advertising features'. Is there any way of doing that with this plugin?

regards
Kevin

**Comment by nitsans** [comment]
Any news on that ?

**Comment by nitsans** [comment]
https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad#app

**Comment by gillesBzk** [comment]
Hello Dan !
Are you thinking ti implement this feature ?
Thanks
Gilles

**Comment by CodingCarlos** [comment]
Hi Dan!! I'm also very interested on this. Are you thinking on it?

**Comment by CodingCarlos** [comment]
Right now I'm not at home (easter, you now...) and I have not my computer for testing, but I think that adding support for this function could be as easy as this:

### For Android:
At [android/UniversalAnalyticsPlugin.java](https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java):

Add a new var for enable remarketing
`public static final String ENABLE_ADVERTISING_ID_COLLECTION = "enableAdvertisingIdCollection";`

In the execute(), add an option to the "else if":
```
} else if (ENABLE_ADVERTISING_ID_COLLECTION.equals(action)) {
    boolean option = args.getBoolean(0);
    this.enableAdvertisingIdCollection(option, callbackContext);
    return true;
}
```

And after all functions, add the one called in the previous conditional:

```
private void enableAdvertisingIdCollection(boolean option, CallbackContext callbackContext) {
    if (! trackerStarted ) {
        callbackContext.error("Tracker not started");
        return;
    }
    
    if (null != option) {
        tracker.enableAdvertisingIdCollection(option);
        callbackContext.success("Advertising id collection setted to: " + option);
    } else {
        callbackContext.error("option is not valid");
    }
}
```

At [www/analytics.js](https://github.com/danwilson/google-analytics-plugin/blob/master/www/analytics.js):

Before exporting the module, add the following code:
```
UniversalAnalyticsPlugin.prototype.enableAdvertisingIdCollection= function(option, success, error) {
  cordova.exec(success, error, 'UniversalAnalytics', 'enableAdvertisingIdCollection', [option]);
};
```

### For iOS
I have never done anything for iOS, so **I have no idea of how it works** :cry:

**Comment by zanemcca** [comment]
+1

**Comment by JimWhiteheadMR** [comment]
+1 on this feature request.

FWIW, in my project I just followed the instructions given here:
https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad#app
under the section "App-tracking code change for iOS" (located in section, "Enable Remarketing and Advertising Reporting Features for an app")

This section states:

_To enable these features for iOS, collect the IDFA (Identifier for Advertisers). To enable IDFA collection, link the libAdIdAccess.a and AdSupport.framework libraries to your application and set the allowIDFACollection to YES on each tracker that will collect the IDFA. For example:_

```
// Assumes a tracker has already been initialized with a property ID, otherwise
// getDefaultTracker returns nil.
id tracker = [[GAI sharedInstance] defaultTracker];

// Enable IDFA collection.
tracker.allowIDFACollection = YES;
```

To implement this, I:

* Added the "tracker.allowIDFACollection = YES" line after each instance of "id tracker == [[GAI sharedInstance] defaultTracker]" in UniversalAnalyticsPlugin.m

* Added in the library "libAdIdAccess.a" (found in the Google Analytics for iOS SDK at: https://developers.google.com/analytics/devguides/collection/ios/v3/sdk-download

* Added in "AdSupport.framework" (no download needed, visible in XCode)

* Added the following line to the plugin.xml file for cordova-plugin-google-analytics:

`	<source-file src="ios/libAdIdAccess.a" framework="true" />`

I'm not yet sure whether this will work. At the very least, it doesn't seem to cause any harm. If it seems to work, I'll submit a pull request.

**Comment by victorsosa** [comment]
fixed

**Comment by paramesh016** [comment]
when i need to enable demographics ,
i added window.analytics.setAllowIDFACollection ,
but in console it shows " window.analytics.setAllowIDFACollection  is not a function ".
I also tried window.ga.setAllowIDFACollection , the result is same so what is the solution for enabling demographics .
Please help

Thanks in advance

**Comment by paramesh016** [comment]
wow thanks a lot , i was facing this issue 
Wouldn't have done without your support .Thanks a lot

**Comment by victorsosa** [comment]
@paramesh016  you welcome

**Comment by paramesh016** [comment]
Hi i have one doubt ,even after adding the below line
**window.analytics.setAllowIDFACollection(true);**
and there is no error in the console 
and after enabling demographics in my google analytics account 

i shows "There is no data for this view."
![booble boy](https://cloud.githubusercontent.com/assets/5110852/17479532/a8907076-5d90-11e6-9e15-8b5171908dfd.png)


can u help pls with this please .thank you

**Comment by victorsosa** [comment]
@paramesh016 please open a new issue with this bug

**Comment by paramesh016** [comment]
@victorsosa : Sure 
and also i am not able to enable see **"data collection"** 


![google analytics](https://cloud.githubusercontent.com/assets/5110852/17481938/0bc52388-5d9d-11e6-8e2d-b53d2d9ddfb0.png)

instead of having this way (below) :


![google analytics2](https://cloud.githubusercontent.com/assets/5110852/17481883/c7b24d4c-5d9c-11e6-8b98-5d32be958ef9.png)

because here i should enable "**Remarketing and Advertising report features**" so that i get **demographics reporting data** , since i am not able to see data collection .I am not able to enable it .Please provide if u have any solution on this 

and sorry if i am being unproffesional

**Comment by Lyncros** [comment]
Hello @victorsosa I'm also tryinig to implement remarketing in my app, which I'm compiling trough phonegap and it doesn´t seem to be logging remarketing information. I'm not planning to display adds in my app, just be able to display google ads to those who downloaded it in the last 30 days. 
Could you give me a hint as of where to look to fix the problem?

**Comment by victorsosa** [comment]
@Lyncros please check issue #274
