### ISSUE TITLE
Can't get past the splashscreen

### ISSUE THREAD

**Issue by izeau** [danwilson/google-analytics-plugin#157]
Hi guys, I really need some help right now. I installed the plugin with `ionic plugin add cordova-plugin-google-analytics` and now my app won't even load past splash screen (iOS device / simulator).

There's absolutely NO error to be found ANYWHERE, in my terminal, in Xcode's console.

Do you have any insight?

**Comment by danwilson** [comment]
Please provide more information... such as did you try to make any calls on `window.analytics`? What version of Cordova CLI and Cordova iOS?

**Comment by victorsosa** [comment]
please try last release, maybe related to #168 and this is too old closed issue IOS
