### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by LilDevine89** [danwilson/google-analytics-plugin#158]
Hi am using visual studio 2015 Cordova 4.3.1.

After adding plugin i have done a rebuild and am reciving this error:

>  Failed to install 'com.cmackay.plugins.googleanalytics':TypeError Uh oh!
>  Arguments to path.resolve must be strings
>      at Object.win32.resolve (path.js:146:13)
>      at module.exports.framework.install (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
>      at Object.ActionStack.process (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
>      at handleInstall (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
>      at C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
>      at _fulfilled (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:787:54)
>      at self.promiseDispatch.done (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:816:30)
>      at Promise.promise.promiseDispatch (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:749:13)
>      at C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:509:49
>      at flush (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:108:17)
>  TypeError: Uh oh!
>  Arguments to path.resolve must be strings

**Comment by CookieCookson** [comment]
I had this same issue on a different plugin, try updating your android platform to 4.0.0.
```
$ cordova platform update android
```

See https://github.com/phonegap/phonegap-plugin-push/issues/186 for more details

**Comment by danwilson** [comment]
@LilDevine89 : Did @CookieCookson's reply help?

**Comment by victorsosa** [comment]
I notice that this is `com.cmackay.plugins.googleanalytics` you are posting in the wrong place. This is 
danwilson/google-analytics-plugin
