### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Vertilol** [danwilson/google-analytics-plugin#159]
Hi, 
I'm new at Cordova development and i'm trying to have the google analytics to my application but it's not working.
I added the window.analytics.startTrackerWithId("with my number") and window.analytics.trackView('home') into the onDeviceReady event, but nothing is happening on the real time analytics.

I really don't know what to do, if someone can help me it would be really good !

Thank for the reading :)

**Comment by Vertilol** [comment]
Actually it's working, but the real time not.
Do you know why ? :)

**Comment by danwilson** [comment]
See #33
