### ISSUE TITLE
Plugin conflict with pushwoosh

### ISSUE THREAD

**Issue by jobberteamcarolo** [danwilson/google-analytics-plugin#161]
Hi there,

It looks like you can't build on PGB if you have this plugin + "pushwoosh-pgb-plugin".
Only on android, ios & windows build fine.

I had a hard time finding what was causing this issue since the only error message show on PGB is "Oh geez, something went wrong on our server", so here is all the informations I can get on my phonegap community thread :

http://community.phonegap.com/nitobi/topics/pgb-fail-conflict-plugins-with-google-analytics-only-android

Thanks a lot,
Romain.

**Comment by danwilson** [comment]
You might try using the latest version of this plugin, and if you have issues with that see if the comments here help: https://github.com/danwilson/google-analytics-plugin/issues/123#issuecomment-151145095 

There shouldn't be these Play Services conflicts anymore with the 0.8.0+ versions of this plugin

**Comment by jobberteamcarolo** [comment]
Hi Dan, 

We are not setting version code on our config.xml so Phonegap Build is using latest version of the plugin (0.8.0 according to the logs).

gap:plugin name="pushwoosh-pgb-plugin" source="npm"
gap:plugin name="cordova-plugin-google-analytics" source="npm"

Is there a version higher than 0.8.0 ?
Thank you for your time,
Romain.

**Comment by danwilson** [comment]
0.8.1 is available, but it's changes are primarily for Android.

I'm not familiar enough with PhoneGap Build to know how to resolve a dependency issue.  If you are on 0.8.0 or 0.8.1 they should not be including the same file, that should only be possible with 0.7.1.

**Comment by jobberteamcarolo** [comment]
Hello Dan,

I was using 0.8.0 and I just tried with version 0.8.1 but the problem still remains.

This is the phonegap community thread: http://community.phonegap.com/nitobi/topics/pgb-fail-conflict-plugins-between-google-analytics-pushwoosh-pgb-plugin-only-android

Do you have any idea how I could resolve this or why the issue is still happening on version 0.8.0+ on Phonegap Build ?

Thank you,
Romain.

**Comment by mtamony** [comment]
I'm using Pushwoosh with this GA plugin in a Cordova non-PGB project. I can't get the GA plugin to do anything at all. Does this look ok for js?
onDeviceReady: function() {
    initPushwoosh();
    app.receivedEvent('deviceready');
    window.analytics.startTrackerWithId('UA-XXXXXXXX-2');
},

**Comment by victorsosa** [comment]
we are using gradle to avoid conflict with others projects, issue closed.
