### ISSUE TITLE
com.google.playservices@19.00 issue

### ISSUE THREAD

**Issue by mukesh1609** [danwilson/google-analytics-plugin#165]
Hi i am using some other plugin that is using the latest version of com.google.playservices that is 22 ,but in the version 0.7.1 of the analytics plugin the dependency is com.google.playservices@19.00, since the lastest version is not working in android, so what can de done to use latest version of com.google.playservices using 0.7.1 version of analytics plugin

**Comment by DreamYahia** [comment]
hi
remove this folder plugins/com.google.playservices and plugins/cordova-plugin-google-analytics
after that
cordova plugin add cordova-plugin-google-analytics@0.7.1

**Comment by rjdjohnston** [comment]
No longer works. the playservices plugin no longer has v 19.0.0 available to download..

**Comment by moraleslevi** [comment]
Running into this issue still as well.

> Failed to install 'cordova-plugin-google-analytics':CordovaError: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@19.0.0
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/src/plugman/fetch.js:146:33
    at _rejected (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/phonegap/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/phonegap/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/phonegap/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

**Comment by Medtrack** [comment]
Same for me:

Not working for me any solution. The app works from windows and is downloaded from git repository to a Mac and a Linux machines. Both Mac and Linux crashed.

I don't even have plugin com.analytics.google, I have com.google.playservices but the path is wrong.
How can I debug this? How to know where cordova is trying to find that folder?

```
$ cordova prepare android
Error during processing of action! Attempting to revert...
Error: Uh oh!
ENOENT: no such file or directory, scandir '/Users/me/git/myapp/Mobile/Android/loc/platforms/android/com.google.playservices'
```

**Comment by comlaterra** [comment]
Is this issue being tracked?, reopened? Do we have a solution?

**Comment by Medtrack** [comment]
I have three installs of the same project: on windows, Mac and Linux, with the exact same code and plugins. The difference is the version of cordova, 6.1.0, on Mac and Linux and 5.3.3.

This issue makes impossible to compile the app on Mac and Linux

**Comment by sirdowan** [comment]
Any solutions on this? 
Facing similar issues, either for ios or android builds, no matter what I do I get this error when installing:
Error: version not found: cordova-plugin-googleplayservices@19.0.0 etc

And when running app: ga is not defined 

Also, for android the 8.1 version crashes the app on device on every startup.
