### ISSUE TITLE
Unable to run on IOS device

### ISSUE THREAD

**Issue by omargon** [danwilson/google-analytics-plugin#166]
Hi,

I've been trying to integrate this plugin onto my app but once installed if I try to run my app on an IOS device I get the following error:

"...Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGHit.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Not sure what to do. I don't get any errors from the build or while emulating. I can also run on an android device but it won't run on IOS device.

Any help would be appreciated. Thanks.

**Comment by lordakshaya** [comment]
@danwilson I guess this is already solved (thanks to PR #163). When will it be officially released?

**Comment by danwilson** [comment]
Yes, it should be resolved if you are adding the plugin using the git URL, and the latest version (0.8.1) has been published on npm as well. Please try to uninstall and add the plugin again to see if it is resolved - thanks!

**Comment by lordakshaya** [comment]
@danwilson Awesome!

**Comment by omargon** [comment]
Thanks @lordakshaya and @danwilson. I was able to run on device once I reinstalled plugin via URL. :+1:

**Comment by Yuripetusko** [comment]
Hello so if I use 0.8.1 I can build for ios, but then I get android error about 
`UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dex.DexException: Multiple dex files define`

with 0.7.1 Android issue is fixed but it won't build for ios with above error

**Comment by Yuripetusko** [comment]
fixed by manually linking these libs
https://github.com/danwilson/google-analytics-plugin/issues/11
