### ISSUE TITLE
Android builds failing after #166

### ISSUE THREAD

**Issue by lordakshaya** [danwilson/google-analytics-plugin#167]
After resolution of #166, the android builds are failing. Can you please fix this?

**Comment by danwilson** [comment]
Can you be more specific please?

**Comment by lordakshaya** [comment]
I get the following error:

![image](https://cloud.githubusercontent.com/assets/1169337/10836792/607817fc-7ee4-11e5-988e-c65795992810.png)

**Comment by danwilson** [comment]
Can you verify if Google Play Services SDK is installed via [Android SDK Manager](https://developer.android.com/sdk/installing/adding-packages.html)?

**Comment by basterbrugge** [comment]
I think this error came from Phonegap Build. I've seen it there, but it has been resolved.

**Comment by lordakshaya** [comment]
Hi @danwilson, the SDK has been installed using Android SDK Manager itself.  But as @basterbrugge said, ours is NOT a Phonegap Build project, the application is created using `cordova-cli` for all purposes and this error shows up while running `cordova build android`.

**Comment by youssmak** [comment]
@lordakshaya I had the same issue. Installing Android support repository and Android support library trough the sdk manager fixed the issue.

**Comment by lordakshaya** [comment]
@youssmak ok, i'll re-verify/re-install those and see if it helps! Thanks for the tip!

**Comment by lordakshaya** [comment]
@youssmak @danwilson so I ran the android sdk manager and realised that I already have the Android Support Library and Android Support Repository installed but they were outdated. Also, the SDK tools were outdated in my case. So, I updated all of them. 

However, even after the updates, I still witness the same error. Below, I am listing the installed versions:
1. Android SDK Tools - Rev 24.4.1
2. Android SDK Platform Tools - Rev 23.0.1
3. Android SDK Build Tools - Rev 23.0.1 and Rev 22.0.1
4. Android 5.1.1 (API 22) - SDK Platform rev 2.
5. Android Support Repository - Rev 24 
6. Android Support Library - Rev 23.1
7. Cordova - ver 5.3.3
8. Java - ver 1.7.0_51

Please guide me of what I can do next?

**Comment by lordakshaya** [comment]
@youssmak @danwilson I stumbled on the README about trying the solution here https://github.com/danwilson/google-analytics-plugin/issues/123#issuecomment-151145095. I realise I was missing the Google Play Services and Google Play Repository. Once I installed them, the build started to work :) Thanks for the help you too.

**Comment by jonatasfreitasv** [comment]
@lordakshaya thx :+1:
