### ISSUE TITLE
iOS - Hits are never sent

### ISSUE THREAD

**Issue by didi3r** [danwilson/google-analytics-plugin#168]
Hello,
I'm trying to make this plugin work without success. When I open the app I can see the following activity:

2015-11-04 15:51:01.860 GE Health Care Hub[8294:289594] INFO: GoogleAnalytics 3.14 -[GAIReachabilityChecker reachabilityFlagsChanged:](GAIReachabilityChecker.m:159): Reachability flags update: 0X000002
2015-11-04 15:51:01.860 GE Health Care Hub[8294:289594] INFO: GoogleAnalytics 3.14 -[GAIReachabilityChecker reachabilityFlagsChanged:](GAIReachabilityChecker.m:159): Reachability flags update: 00000000
2015-11-04 15:51:02.256 GE Health Care Hub[8294:289777] VERBOSE: GoogleAnalytics 3.14 -[GAIBatchingDispatcher persist:](GAIBatchingDispatcher.m:517): Saved hit: {
    parameters =     {
        "&_crc" = 0;
        "&_s" = 54;
        "&_u" = ".tnoK-L";
        "&_v" = "mi3.1.4";
        "&a" = 1964111295;
        "&aid" = "com.ge.ent.GEHealthcareHub";
        "&an" = "GE Health Care Hub";
        "&av" = "1.0.4";
        "&cd" = Featured;
        "&cid" = "40a9ec3d-4e86-4bd8-b650-89d5edc55d73";
        "&dm" = "x86_64";
        "&ds" = app;
        "&sr" = 640x1136;
        "&t" = screenview;
        "&tid" = "UA-XXXX-1";
        "&ul" = "en-us";
        "&v" = 1;
        "&z" = 15429306972082145888;
        gaiVersion = "3.14";
    };
    timestamp = "2015-11-04 21:51:02 +0000";
}

And as I interact with the app more hits are saved: 

2015-11-04 15:51:02.264 GE Health Care Hub[8294:289777] VERBOSE: GoogleAnalytics 3.14 -[GAIBatchingDispatcher persist:](GAIBatchingDispatcher.m:517): Saved hit: {
    parameters =     {
        "&_crc" = 0;
        "&_s" = 55;
        "&_u" = ".oK-L";
        "&_v" = "mi3.1.4";
        "&a" = 1964111295;
        "&aid" = "com.ge.ent.GEHealthcareHub";
        "&an" = "GE Health Care Hub";
        "&av" = "1.0.4";
        "&cd" = Favorites;
        "&cid" = "40a9ec3d-4e86-4bd8-b650-89d5edc55d73";
        "&dm" = "x86_64";
        "&ds" = app;
        "&sr" = 640x1136;
        "&t" = screenview;
        "&tid" = "UA-XXXX-1";
        "&ul" = "en-us";
        "&v" = 1;
        "&z" = 15429306972082145889;
        gaiVersion = "3.14";
    };
    timestamp = "2015-11-04 21:51:02 +0000";
}

Thing is that those hits are never sent to google analytics and in consequence I don't receive any tracking information on my GA dashboard. As far as I understand all those stored hits should be sent avery 2 minutes (https://developers.google.com/analytics/devguides/collection/ios/v3/dispatch) but it seems that it never happens.

I'm testing this in the ios simulator and I'm using cordova 5.3.3. What it isn't clear for me is if I have to set some special permission to my app to make this plugin work or something like that.

**Comment by interacsean** [comment]
Have you set your tracking code properly?  The below line looks like it hasn't been updated with your real google analytics ID:
`"&tid" = "UA-XXXX-1";`

**Comment by jobelenus** [comment]
I'm having a similar issue. I don't see any tracking info in google analytics. Though I do in fact see a "Hits sent" message in the console log:

Feb 15 16:12:44 abel dylanpush[31471]: VERBOSE: GoogleAnalytics 3.14 -[GAIBatchingDispatcher dispatchWithCompletionHandler:] (GAIBatchingDispatcher.m:632): Sending hit(s) GET: https://ssl.google-analytics.com/collect?....
Feb 15 16:12:44 abel dylanpush[31471]: INFO: GoogleAnalytics 3.14 -[GAIBatchingDispatcher didSendHits:response:data:error:] (GAIBatchingDispatcher.m:226): Hit(s) dispatched: HTTP status -1
Feb 15 16:12:44 abel dylanpush[31471]: INFO: GoogleAnalytics 3.14 -[GAIBatchingDispatcher deleteHits:] (GAIBatchingDispatcher.m:529): hit(s) Successfully deleted
Feb 15 16:12:44 abel dylanpush[31471]: INFO: GoogleAnalytics 3.14 -[GAIBatchingDispatcher didSendHits:] (GAIBatchingDispatcher.m:237): 1 hit(s) sent

It seems Google is rejecting this (HTTP Status -1)??? But I don't see any alerts or error logging in the account to see what the potential issue might be.

**Comment by interacsean** [comment]
Have you enabled debugging with ``googleAnalyticsCordovaProvider.debug = true`` in your app.config. I would have expected the log should show the parameters it had tried to send.

**Comment by jobelenus** [comment]
I used debugEnable() from this plugin. And yes I do have the full parameters, I merely truncated them because it has the UA string that shouldn't be out in the wild. Here are the parameters with the UA X'd out:

(GAIBatchingDispatcher.m:632): Sending hit(s) GET: https://ssl.google-analytics.com/collect?av=0.0.1&cid=4dd5478e-3931-4cb7-a75e-339163ff7e78&tid=UA-XXXXXXX-X&a=1593900812&dm=x86_64&t=screenview&aid=com.toursphere.dylanpush&ul=en-us&_u=.oK-L&ds=app&sr=750x1334&v=1&_s=9&_crc=0&an=dylanpush&_v=mi3.1.4&ht=1455570754058&qt=10039&z=4678019125111685063

**Comment by jobelenus** [comment]
I also have the full paramters:
```
            parameters =     {
                "&_crc" = 0;
                "&_s" = 9;
                "&_u" = ".oK-L";
                "&_v" = "mi3.1.4";
                "&a" = 1593900812;
                "&aid" = "com.toursphere.dylanpush";
                "&an" = dylanpush;
                "&av" = "0.0.1";
                "&cd" =         {
                    context =             {
                        jQuery18207973549955058843 = 367;
                    };
                    length = 0;
                    prevObject =             {
                        0 =                 {
                            jQuery18207973549955058843 = 367;
                        };
                        context =                 {
                            jQuery18207973549955058843 = 367;
                        };
                        length = 1;
                    };
                    selector = title;
                };
                "&cid" = "4dd5478e-3931-4cb7-a75e-339163ff7e78";
                "&dm" = "x86_64";
                "&ds" = app;
                "&sr" = 750x1334;
                "&t" = screenview;
                "&tid" = "UA-XXXXXXX-X";
                "&ul" = "en-us";
                "&v" = 1;
                "&z" = 4678019125111685063;
                gaiVersion = "3.14";
            };
            timestamp = "2016-02-15 21:12:34 +0000";
        }
```

**Comment by ithav** [comment]
Same issue here, with iOS 8.
Works fine for Android, no data for iOS is getting to analytics dashboard

**Comment by jobelenus** [comment]
My issue was that I didn't have the plist file generated by Google in the
Xcode project. I may or may not have needed a success and failure
JavaScript method passed to trackView (shouldn't need one but I added them
and I got results in analytics)

**Comment by jplethier** [comment]
I am having the same issue, I added this plugin to my ionic project, on android I have all hits working and I can see analytics for android users, but it is not working for ios.

**Comment by victorsosa** [comment]
PEOPLE please check the issue #274 for more information

**Comment by rubaiyat6370** [comment]
I am having the same issue. It was working previously. Without any reason its not working now. Hits are never sent.

**Comment by SuThwe** [comment]
It's same for me. It's working fine yesterday. I can't connect to GA today.
Do you have any solution for this, @rubaiyat6370 ?

**Comment by victorsosa** [comment]
Please check also #477
