### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by miche-atucha** [danwilson/google-analytics-plugin#169]
I am getting this error while building in xcode 7.1:

Undefined symbols for architecture arm64:
  "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
      -[TAGNetReachability stop] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
  "_SCNetworkReachabilityCreateWithName", referenced from:
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      -[TAGNetReachability stop] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
  "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
      -[TAGNetReachability start] in libGoogleAnalyticsServices.a(TAGNetReachability.o)
      _kDefaultReachabilityApi in libGoogleAnalyticsServices.a(GAIReachabilityChecker.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by victorsosa** [comment]
all issue closed
