### ISSUE TITLE
Plugin does not define it's own whitelist needs

### ISSUE THREAD

**Issue by lietu** [danwilson/google-analytics-plugin#172]
Many people (incl. me) expect that Cordova plugins define their own whitelist needs in the plugin.xml so they don't have to worry about every plugin separately.

This plugin does not do that, and does not explain this clearly to the users either.

`plugin.xml` should include something along the lines of:

```
<platform name="android">
  <config-file target="res/xml/config.xml" parent="/*">
    <access origin="http://*.google-analytics.com"/>
    <access origin="https://*.google-analytics.com"/>
  </config-file>
</platform>
<platform name="ios">
  <config-file target="res/xml/config.xml" parent="/*">
    <access origin="http://*.google-analytics.com"/>
    <access origin="https://*.google-analytics.com"/>
  </config-file>
</platform>
```

**Comment by shtaft** [comment]
Bump. Also experiencing this issue. Thanks for the fix @lietu

**Comment by indrasantosa** [comment]
I search around it seems we need to install a whitelist plugin? Or defining the access origin for plugin.xml is enough?

**Comment by ZiFFeL1992** [comment]
Guys do you have any clue why this plugin is working on Android only?

Every event returns success, but cannot see any data on Google Analytics Panel :/

**Comment by victorsosa** [comment]
I suppose `<access >` is deprecated and we should use whitelist instead.
```
<allow-navigation href="http://*.google-analytics.com" />
<allow-navigation href="https://*.google-analytics.com" />
```
base on the whitelist 
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/index.html#navigation-whitelist

**Comment by victorsosa** [comment]
I tested this out and none change need to be done in the code.
