### ISSUE TITLE
Conflict with ConnectSDK Plugin

### ISSUE THREAD

**Issue by ds8k** [danwilson/google-analytics-plugin#180]
After installing this plugin Android will no longer build, throwing this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Building with Cordova CLI 5.3.3, Cordova Android 5.0.0, and using the latest Ionic Framework.

Connect plugin located here - https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/

**Comment by ElieSauveterre** [comment]
I had the same problem with google-analytics-plugin and cordova-plugin-locationservices.
In the plugin.xml file, one plugin required com.google.android.gms:play-services-location:7.8.0 and the other com.google.android.gms:play-services-location:+

I solved it by putting the same version of com.google.android.gms:play-services-location on both files.

**Comment by victorsosa** [comment]
google-analytics-plugin do no depends from `com.google.android.gms:play-services-location` anymore; this is not longer an issue.
