### ISSUE TITLE
Build Failed IOS Intel XDK plugin 0.8.1 and 0.8.0 and 0.7.2

### ISSUE THREAD

**Issue by ivanov84** [danwilson/google-analytics-plugin#182]
I am trying to build ios cordova hybrid mobile app with Intel XDK with plugin 0.8.1 and I have error in compiling process:

duplicate symbol l030 in:
    .../[App Name]/platforms/ios/[App Name]/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGContainerOpener.o)
    .../[App Name]/platforms/ios/[App Name]/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(GAITrackerModel.o)
ld: 223 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I built succesfully ios biuld with plugin 0.8.0 (I have local copy) 1 week ago, but today I can not build app despite of using plugin 0.8.0 local or 0.7.2.

Please help me! What does this error mean?

**Comment by ivanov84** [comment]
It's because of GOOGLE!!!!

https://developers.google.com/analytics/devguides/collection/ios/v3/sdk-download?hl=en


But I still did not resolve the problem

**Comment by ivanov84** [comment]
I found this:

Plugin Submission Guidelines
Any application that contains binary libraries will be rejected. This is because we need to be able to see exactly what is in a plugin as part of our code review process. So when submitting a plugin make sure that it doesn’t contain binary libraries. (PhoneGap)

So... IMHO, we need to fix code in ours plugins.
Any ideas?

**Comment by TompiT** [comment]
I have the same issue using Xcode v6.2 and plugin v0.8.1. 
I can build the project if I remove the arm64 architecture but it's not an option. 
Which version of Xcode are you using?
Also, I'm not sure if there is a relation with [this GA bitcode support](https://developers.google.com/analytics/devguides/collection/ios/v3/sdk-download).
I plan to upgrade to Xcode v7.1.1 anyway to see if the issue persists.

**Comment by ivanov84** [comment]
Specialist from Intel XDK said:

Our iOS build system is still using Xcode 6, we are in the process of upgrading it to Xcode 7, but no ETA on when that upgrade will be available. In order to use the v3.13 version of the library, you'll have to contact the plugin developers to figure out which version of their plugin still uses v3.13 of the Google Analytics library.

**Comment by TompiT** [comment]
Just an update, I'm not using Intel XDK but the issue remains the same i.e.
```
duplicate symbol l030 in:
.../[App Name]/platforms/ios/[App Name]/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGContainerOpener.o)
.../[App Name]/platforms/ios/[App Name]/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(GAITrackerModel.o)
ld: 223 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Unfortunately by upgrading to Xcode v7.1.1 the build fails with the same error.

**Comment by ivanov84** [comment]
I downgraded to version of plugin 0.8.0 from 23rd July 2015 and build was succesfull.

**Comment by TompiT** [comment]
I did the same, (i.e. downgrade to v0.8.0) no more issue, build is ok.
