### ISSUE TITLE
Any support for custom metrics?

### ISSUE THREAD

**Issue by nikolasleblanc** [danwilson/google-analytics-plugin#187]

**Comment by podliy16** [comment]
+1

**Comment by souly1** [comment]
+1

**Comment by belgacea** [comment]
@souly1  It must be merged as soon as possible !

**Comment by victorsosa** [comment]
I need someone to test this on iOS please; to complete this and merged it

**Comment by victorsosa** [comment]
I will merge this anyway, but I need someone to take some time on testing this for iOS

**Comment by belgacea** [comment]
@victorsosa Sorry, I don't use any Apple product
