### ISSUE TITLE
How to retrieve the INSTALL_REFERRER data locally

### ISSUE THREAD

**Issue by vijayrajasekaran** [danwilson/google-analytics-plugin#188]
Hello,

I have installed this plugin and while testing locally by broadcasting the below intent, it works fine and i get the referral data printed in the log ("utm_source=test"), is it possible to save the data received and store it in a local JavaScript variable.

Like, var referrer = "utm_source=test";

adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n com.example.app/com.google.android.gms.analytics.CampaignTrackingReceiver --es referrer "utm_source=test"

Thank you.

**Comment by Marc2017** [comment]
Any solution for this?

**Comment by victorsosa** [comment]
This maybe releated to #208

**Comment by raviagarwal292** [comment]
@victorsosa could you please add a feature for campaign tracking as its one of the most important and killer feature for anyone to know where their app installation is coming from.

Reference link How do I implement Campaign tracking with Cordova?

Regards
Ravi Agarwal

**Comment by raviagarwal292** [comment]
@danwilson  could you please add a feature for campaign tracking as its one of the most important and killer feature for anyone to know where their app installation is coming from.

Reference link How do I implement Campaign tracking with Cordova?

Regards
Ravi Agarwal

**Comment by victorsosa** [comment]
PR sent

**Comment by zepfan** [comment]
Can someone help me with this? I still cannot get it working. I need to get the INSTALL_REFERRER for my app.

Using this code:
```window.ga.getVar('cn', (result) => {
	if(!result) {
		return false;
	}

	alert('getVar returns:', JSON.stringify(result));
	}
}, (error) => {
	// fail silently
});```

And this link to the Play Store:
https://play.google.com/store/apps/details?id=com.myappname.app&referrer=foobar&utm_source=thing1&utm_medium=thing2&utm_campaign=thing3

I get null/undefined every time. What am I doing wrong?

**Comment by victorsosa** [comment]
please check comment issue #410
