### ISSUE TITLE
What is the correct code for custom dimensions

### ISSUE THREAD

**Issue by sambhav-gore** [danwilson/google-analytics-plugin#189]
I have set up a custom dimension in my Google Analytics admin.

While adding the custom dimension, what is the correct code ?

Int:
```
window.analytics.addCustomDimension(1, customValue, success, failure);
```

OR

String ?
```
window.analytics.addCustomDimension('dimension1', customValue, success, failure);
```

In this file, Line 72, it is expecting an Int variable.

**Comment by sambhav-gore** [comment]
I confirm that using Int is working in the Adroid version. Waiting for iOS test. Will update here. If anyone has and insight, please tell.

**Comment by sambhav-gore** [comment]
I further confirm that using int worked for iOS as well.
So this is the code which worked correctly:

```
window.analytics.addCustomDimension(1, customValue, success, failure);
```

**Comment by barocsi** [comment]
Should you wait for success callback before sending the consecutive event?
