### ISSUE TITLE
Error ITMS-9017 Invalid Bundle during store submission

### ISSUE THREAD

**Issue by binphx** [danwilson/google-analytics-plugin#191]
Hi, while trying to submit app to iTunes Connect via Application Loader getting the following error:

<img width="681" alt="screen shot 2016-01-11 at 3 05 50 pm" src="https://cloud.githubusercontent.com/assets/3800746/12248245/4d1d52ec-b875-11e5-928b-2072db947578.png">

using phone gap build
phonegap cli-5.2.0

Builds and tests great while doing development. Submitting to app store is the problem.
Is this an issue or have we done something incorrect? 

Thank you.

**Comment by comapedrosa** [comment]
Same issue with:

Cordova CLI: 6.1.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by victorsosa** [comment]
We can fix this using cocoapods, this plugin could help us:
https://github.com/blakgeek/cordova-plugin-cocoapod-support

**Comment by victorsosa** [comment]
please check comment issue #377
