### ISSUE TITLE
Ability to close the session and to start anew?

### ISSUE THREAD

**Issue by javacado** [danwilson/google-analytics-plugin#195]
Hello. Thanks for the plugin. Its workign right out of the box. I have a need to change the tracking ID on my app when the user switches his 'home base'. Is there a method I can call to end the current session with analytics and then init again? Thanks!

I tried just calling the startTrackerWithId() again but that didn't work

**Comment by victorsosa** [comment]
this can be implement. but sessions should use the same tracking ID

https://developers.google.com/analytics/devguides/collection/android/v4/sessions

**Comment by victorsosa** [comment]
PR sent

**Comment by javacado** [comment]
Thanks
