### ISSUE TITLE
cannot find symbol variable app_tracker

### ISSUE THREAD

**Issue by healthdectech** [danwilson/google-analytics-plugin#196]
Hi everybody. I've used other versions in the past, but I am starting a new project and getting some errors on set up (have not yet started creating the assets that wlll be tracked (i.e. no js integration yet).

Android Studio 1.5.1 (Mac)
Cordova 6.0.0
Cordova Android 5.1.0
Plugin version 0.8.1
Developer Services enabled (com.google.android.gms:play-services-gcm:8.4.0)

on build I get two errors:
-- error: cannot find symbol variable app_tracker (in AnalyticsTrackers.java) 
"tracker = GogleAnalytics.getinstance (mContext.newTracker (R.xml.ap_tracker;"
and
-- Execution failed for task ':compileDebugJavaWithJavaC'.

Any feedback appreciated!

**Comment by Dragsbaek** [comment]
@healthdectech - you found a solution? I get the same error:/

**Comment by eladmoshe** [comment]
+1

**Comment by eladmoshe** [comment]
The issue is just that the value R.xml.app_tracker is missing since there is no such file. You can either replace that string in AnalyticsTrackers.java with some hard coded value or create a file called `res/xml/app_tracker.xml` with something like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_tracker">ANY-STRING-WILL-DO</string>
</resources>
```

**Comment by victorsosa** [comment]
AnalyticsTrackers.java doesn't exist in the plug-in; check you dependencies the name of this plug-in is cordova-plugin-google-analytics
