### ISSUE TITLE
createAppView is deprecated, should use createScreenView instead

### ISSUE THREAD

**Issue by trinityEon** [danwilson/google-analytics-plugin#198]
On Xcode 7.2 I get a warning that createAppView is deprecated, should use createScreenView instead.

**Comment by tomkuipers** [comment]
+1

https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m#L193

**Comment by Robert430404** [comment]
+1

Were having the same problem with our app.

**Comment by BenjaminConant** [comment]
+1 this is effecting us as well

**Comment by victorsosa** [comment]
Thank you, merged
