### ISSUE TITLE
"Plugin should use a background thread"

### ISSUE THREAD

**Issue by remisture** [danwilson/google-analytics-plugin#199]
Should the plugin handle this, or am I using it wrong?

THREAD WARNING: ['UniversalAnalytics'] took '15.750977' ms. Plugin should use a background thread.

**Comment by cmarrero01** [comment]
I have the same situation here, and the problems for this is if you dont put that function on a background thread the app may have a big delay to start.

**Comment by remisture** [comment]
Any updates here?

**Comment by victorsosa** [comment]
PR 155 is under way

**Comment by victorsosa** [comment]
fixed
