### ISSUE TITLE
working in development mode, but not in release mode on the stores.

### ISSUE THREAD

**Issue by louisdoe** [danwilson/google-analytics-plugin#201]
Hi

I have installed this plugin in my Ionic app.
It works well in development but I released the app on the Play store and Itunes, and I get no tracking from the users there.

I have the `whitelist` plugin installed with:
config.xml:

```
<access origin="*"/>
<allow-navigation href="*"/>
<allow-intent href="*"/>
```

Can you help me figure out what's happening ?

Should I remove : window.analytics.debugMode() ?

Thanks

**Comment by mpz** [comment]
Hello! Can you please talk about any fix?
I have simular issue.

**Comment by victorsosa** [comment]
yes, you need to remove `window.analytics.debugMode()` from the code.

**Comment by ziggyJ** [comment]
I have similar issue. The iOS build works even with debugMode enabled. But Android release build does not work.

**Comment by Prasanna-Repo** [comment]
I too have tested with release version (cordova) its not working. Please help with this issue.

**Comment by victorsosa** [comment]
Please check issue #274 and #291

**Comment by victorsosa** [comment]
old issue
