### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by samuelsc** [danwilson/google-analytics-plugin#203]
Hi there,

I received a clang linker error after creating a blank cordova project with google-analytics-plugin installed.

```
...[SKIPPED]...
/Users/sillymba/Desktop/code/hello/platforms/ios/HelloWorld/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGHit.o)
    /Users/sillymba/Desktop/code/hello/platforms/ios/HelloWorld/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGPValueHash.o)
ld: 230 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to replicate:

I create a blank helloworld cordova project by cordova-cli 6.0.0 by following command. and add the plugin into this project

```
cordova create hello com.example.hello HelloWorld
cordova platform add ios
cordova plugin add cordova plugin add cordova-plugin-google-analytics
cordova build ios
```

Did anybody else encounter this error before? Any clues to resolve this?

[EDIT]
Cordova version: 6.0.0
Cordova-iOS version: 4.0.1
Xcode version: 6.4
Mac OSX ver: 10.10.1

**Comment by xr** [comment]
same issues here.

**Comment by samuelsc** [comment]
It seems that it is due to XCode 6.4. When I try to repeat the same steps and build them in Xcode 7.2 or 7.4, it works.

**Comment by xr** [comment]
But mine Xcode is 7.2 still doesn't work

**Comment by chipbell4** [comment]
I'm having the same issue in 7.2, with version 0.6.1 of the cordova plugin (to be precise). I'll keep fiddling and let you all know if I encounter a fix.

**Comment by jplethier** [comment]
I am having this issue here too, my xcode is 7.2 too.

**Comment by yannicklin** [comment]
I have the same issue, too.
My Xcode is 7.2.1

**Comment by Xwalk-Company** [comment]
Same issue, last cordova, for xcode 6.4

**Comment by yeahstyle** [comment]
Hi y'all. Anyone managed to find a fix for this? I'm experiencing the same problem xcode 6.2 and cordova 6.2.0. I've tried https://github.com/cmackay/google-analytics-plugin same issue!
:(

**Comment by victorsosa** [comment]
@yeahstyle   https://github.com/cmackay/google-analytics-plugin  is not this plugin

As samuelsc tested this out using the last xcode and works; this is a won't fix.
