### ISSUE TITLE
"Broken dependency?"

### ISSUE THREAD

**Issue by rodrigograca31** [danwilson/google-analytics-plugin#205]
Hi!

I added a plugin and it broke the compilation so I had to do: `cordova platform rm android` and `cordova platform add android` but in the second command it said: 

```
Installing "cordova-plugin-google-analytics" for android
Notice: com.google.playservices@19.0.0 has been automatically converted to cordova-plugin-googleplayservices and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-googleplayservices@19.0.0" via npm
Failed to install 'cordova-plugin-google-analytics':CordovaError: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@19.0.0
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:146:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error: Failed to fetch plugin cordova-plugin-googleplayservices@19.0.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: version not found: cordova-plugin-googleplayservices@19.0.0

```

I have another plugin that depends on the play services (admob):

`<dependency id="com.google.playservices" url="https://github.com/floatinghotpot/google-play-services" commit="r19" />`

and yours 

`<dependency id="com.google.playservices@19.0.0" />`

I'm not and expert on this but I think this library shouldn't specify the play services version...
Shouldn't 19.0.0 be a git tag on the play services repo...?

Thanks!

**Comment by jcesarmobile** [comment]
the current plugin.xml doesn't have the `<dependency id="com.google.playservices@19.0.0" />`, it has the `<framework src="com.google.android.gms:play-services-analytics:+" />`, it's the right way of doing it. You must be using an old version of the plugin

**Comment by rodrigograca31** [comment]
@jcesarmobile You are right... Not sure how but I swear I saw that there... It was another plugin or I had an older version.....
