### ISSUE TITLE
Set app version manually

### ISSUE THREAD

**Issue by zwacky** [danwilson/google-analytics-plugin#206]
hey there
some people may also have a OTA (over the air) update flow going on and the google-analytics-plugin only takes the native app version, rather than the JS that was updated by the OTA.

we already have `analytics.setUserId()`, why not `analytics.setAppVersion()` like in the js version of GA: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#appVersion.

**Comment by victorsosa** [comment]
Help wanted for PR

**Comment by zwacky** [comment]
like with the `setUserId` the tracker needs to be initialized to be fully functioning, of course.

**Comment by victorsosa** [comment]
@zwacky THank you, you are awesome. I will check this out when I have time.

**Comment by victorsosa** [comment]
@zwacky thanks
