### ISSUE TITLE
Is there get() function?

### ISSUE THREAD

**Issue by zigzag-way** [danwilson/google-analytics-plugin#208]
Is there get() function?
I`d like to do smth like this
        plugin.get(plugin.Fields.CLIENT_ID, ...)

**Comment by victorsosa** [comment]
Nop, there is not any get() method in the API.

**Comment by victorsosa** [comment]
But it can be implemented

**Comment by victorsosa** [comment]
Using this key list:
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters

**Comment by victorsosa** [comment]
PR #389 sent
