### ISSUE TITLE
PageView won't show in real time

### ISSUE THREAD

**Issue by albertleao** [danwilson/google-analytics-plugin#209]
My GA real time dashboard shows that my user is online, but even when sending

`window.analytics.trackView('/home')`

my active pages does not update.

**Comment by ThomasBormans** [comment]
+1

**Comment by philmerrell** [comment]
+1

**Comment by gion** [comment]
any updates on this?
+1

**Comment by luco** [comment]
+1

**Comment by EvWill** [comment]
+1

**Comment by AndrewBucklin** [comment]
+1

**Comment by victorsosa** [comment]
This is working on last release, please try again.
