### ISSUE TITLE
addTransaction & addTransactionItem not sending data

### ISSUE THREAD

**Issue by jackvial** [danwilson/google-analytics-plugin#213]
startTrackerWithId and trackView are working fine for me and I can see all the data in the GA dashboard but I'm not seeing any data for addTransaction & addTransactionItem. Any idea why the data would not showing in the dashboard?

**Comment by jackvial** [comment]
I see in the Java source there is "deprecated" comment next to addTransaction and addTransactionItem.
```Java
 tracker.send(hitBuilder
                    .setTransactionId(id)
                    .setAffiliation(affiliation)
                    .setRevenue(revenue).setTax(tax)
                    .setShipping(shipping)
                    .setCurrencyCode(currencyCode)
                    .build()
                    ); //Deprecated
```

Does this still work?

**Comment by ZiFFeL1992** [comment]
Sorry for the offtopic @jackvial , but I can't get this plugin working on Cordova 6 + Ionic 2, all callback success function fire but I can't see any data on Google Analitics Panel. Any advice?

**Comment by jackvial** [comment]
@ZiFFeL1992 Sometimes it can take 24 hours before your data shows up in the GA dashboard. Also if you run your app on android and use the "adb logcat" command that should show debugging info from the plugin.

**Comment by ZiFFeL1992** [comment]
Yes, I manage to get this working, you can close it (:

**Comment by victorsosa** [comment]
@jackvial yes addTransaction and addTransactionItem are  "deprecated".

we should create a new API using the new Enhanced Ecommerce SDK.
more info:
https://developers.google.com/analytics/devguides/collection/android/v4/ecommerce
