### ISSUE TITLE
Plugin not working on Android

### ISSUE THREAD

**Issue by ZiFFeL1992** [danwilson/google-analytics-plugin#214]
Plugin works on iOS simulator, data is updating on real time, but I can't get this working on Android.

window.analytics.startTrackerWithId -> returns success
window.analytics.setUserId -> returns success
window.analytics.trackView -> returns success

I don't know what to do at this point, I have latest Google Play Services installed.
Should I add any link to whitelist plugin?

I'm using cordova 6+ and ionic 2.

Thanks!

**Comment by BugsBunnyBR** [comment]
@ZiFFeL1992 , I just tested this plugin using Ionic2 and Android, the real time is not "real time" at all, but the data seemed to show up after some minutes or some number of events, I don't know. But I could see the tracking working.

**Comment by xueenda** [comment]
Same here. Android behaves really wired. I couldn't get any tracking "events" from Andoid.

**Comment by ZiFFeL1992** [comment]
Working on production, dunno why :/
Data still arrives delayed tho.

**Comment by dezudas** [comment]
@xueenda I think the problem might be with the loading try setInterval this worked for me `  if (typeof window.analytics !== 'undefined') {
    window.analytics.startTrackerWithId('Google code');
    window.analytics.setUserId(device.uuid);
  } else {
    setTimeout(function () {
      waitForAnalytics();
    }, 250);
  }`

**Comment by JumBay** [comment]
I have the same issue. Works on iOS simulator but not on android emulator/device.
Testing with ionic beta 8 and cordova 6.2.0.

```ts
GoogleAnalytics.startTrackerWithId('MY-ID')
          .then(success=> {
            //Enter here
            console.log('startTrackerWithId', success);
          });
```

Don't know what to do. Any ideas?

**Comment by rahulinaction** [comment]
Same here . The analytics dont appear in realtime while it works flawlessly for IOS

**Comment by victorsosa** [comment]
Data arrives delayed always in google analytics, so this is a won't fix.
