### ISSUE TITLE
Analytics don't show the values sent through the method "Analytics.trackView()"

### ISSUE THREAD

**Issue by raynerlemos** [danwilson/google-analytics-plugin#217]
Hello, i'm Rayner.

First, sorry for my english. xD

I use the Android to run my IONIC (1.7.13) aplication and cordova version 5.4.1
I'm trying to use this plugin and have been successful to date.
But i have a problem with function "analytics.trackView()". I can send the request to register the pages, but in the Analytics i can't see the access log. 
I affirm that i could because this test:

analytics.trackView("Home APP", function(response){
                      // SUCCESS
			console.log(response);
		}, function(response){
                      // ERROR
			console.log(response);
		});

The success response return the following information: "Track Screen: Home APP". 

How i can register the log and can't see this in the Analytics Dashboard? 
Someone have this problem too? 

Thanks all.

**Comment by philmerrell** [comment]
Yes, seeing this issue also, unfortunately.

**Comment by sergiomilici** [comment]
Any updates on this?

**Comment by victorsosa** [comment]
Hi, could someone test this using the new version 0.9.0?

and also try to test it changing this to one minute:
GoogleAnalytics.getInstance(this).setLocalDispatchPeriod(1);

the dispatch will be more quick.

**Comment by sergiomilici** [comment]
sure. i replace the UniversalAnalyticsPlugin.java under
'platforms/android/src/com/danielcwilson/plugin/analytics' taken from
master branch, rebuild and i still can't track views.

is this the correct way to test it?

2016-07-15 8:23 GMT-03:00 victor sosa <notifications@github.com>:

**Comment by victorsosa** [comment]
yes it is, did you change this code line?
`GoogleAnalytics.getInstance(this).setLocalDispatchPeriod(1);`

**Comment by sergiomilici** [comment]
yes i did.

2016-07-15 9:35 GMT-03:00 victor sosa <notifications@github.com>:

**Comment by victorsosa** [comment]
can you test by adding the cordova-plugin-whitelist into you project? please

also check this issue #172

**Comment by sergiomilici** [comment]
yes, i also add   in config.xml under  android platform tag.
<allow-navigation href="http://*.google-analytics.com" />
<allow-navigation href="https://*.google-analytics.com" />

it's rare that other things are working, like track an event.



2016-07-15 9:48 GMT-03:00 victor sosa <notifications@github.com>:

**Comment by victorsosa** [comment]
Thanks for the info; I was about to ask you about the other functions

**Comment by sergiomilici** [comment]
Hey, it's working. I made the mistake of using an old account of GA i had, and it was for a web site, not a Mobile app. I created a new Mobile App account in GA and it's all working now.
Thanks for your help.

**Comment by victorsosa** [comment]
No problema

**Comment by victorsosa** [comment]
@raynerlemos Please change issue #274
