### ISSUE TITLE
Working on wifi but not working in data network

### ISSUE THREAD

**Issue by overrider10** [danwilson/google-analytics-plugin#219]
Hi everyone!

This plugin is working perfectly for me on wifi network but it seems that pageview doesn't work in data network. Any ideas?

Thank you very much and thanks for the plugin!

**Comment by victorsosa** [comment]
Hi,

What you mean by data network? can you post some code example and how to duplicate you issue?

**Comment by victorsosa** [comment]
please check the issue #274 (pageview and trackview)
