### ISSUE TITLE
How to get the Analytics log in ionic app to display

### ISSUE THREAD

**Issue by pallaviMN** [danwilson/google-analytics-plugin#221]

**Comment by pallaviMN** [comment]
I am using ionic app to add google analytics to it. I have writted below line of code. 
$cordovaGoogleAnalytics.debugMode();
                        $cordovaGoogleAnalytics.startTrackerWithId('UA-000000-01');
                        $cordovaGoogleAnalytics.trackView('home');

How do i get list of all analytics i have done ?

**Comment by victorsosa** [comment]
please use analytics.google.com to get and display all you data.
