### ISSUE TITLE
How can we track more than one view

### ISSUE THREAD

**Issue by pallaviMN** [danwilson/google-analytics-plugin#222]
Hi Team, 

I have to track more than one view in our app, how can i do that with google analytics plugin

**Comment by bz123** [comment]
analytics.trackView('Screen Title')  in your controller?

**Comment by zehni** [comment]
Is the screen title something I set or the name of my controller?

**Comment by zehni** [comment]
@bz123  is the screen title something I set or the name of my controller?

**Comment by bz123** [comment]
@zehni something that you set, e.g window.analytics.trackView('Home')  or window.analytics.trackView('Forums')
