### ISSUE TITLE
Desktop views from mobile apps

### ISSUE THREAD

**Issue by remisture** [danwilson/google-analytics-plugin#223]
I use this plugin in an Ionic project, and only have my app for iOS and Android, but it shows desktop users in my metrics. How is that possible?
![skjermbilde 2016-06-03 kl 09 47 14](https://cloud.githubusercontent.com/assets/2372967/15772241/4981836c-2970-11e6-8cb1-3d7bd11ef830.png)

**Comment by victorsosa** [comment]
Did you do some test from emulator on those desktop, maybe?

**Comment by remisture** [comment]
I have done some testing in emulators, but not in the same periods these hits show up in the logs.

Now, two months later, desktop views have escalated. I now see desktop traffic almost every day. Anyone else experiencing this?

Thanks

**Comment by victorsosa** [comment]
@remisture Weird, I don't have these issue, if you find the root cause, please let me know.

**Comment by victorsosa** [comment]
@remisture please check issue  #274; this could be the problem
