### ISSUE TITLE
Firebase Analytics Support?

### ISSUE THREAD

**Issue by technotip** [danwilson/google-analytics-plugin#224]
As you might already know, AdMob has started using Firebase analytics as default analytics for its users. Is there any plan to support Firebase with this plugin?

Also, with the latest IONIC, window.analytics.trackView(); function [trackView] doesn't seem to be working :-(

**Comment by victorsosa** [comment]
support Firebase with this plugin? I just don't figure out how...

**Comment by victorsosa** [comment]
I don't see the Firebase implementation on AdMob anywhere;

https://github.com/floatinghotpot/cordova-plugin-admob

**Comment by victorsosa** [comment]
Firebase  analytics is another new google product on it own.

> At the heart of Firebase is Firebase Analytics, a free and unlimited analytics solution. Analytics integrates across Firebase features and provides you with unlimited reporting for up to 500 distinct events that you can define using the Firebase SDK. Firebase Analytics reports help you understand clearly how your users behave, which enables you to make informed decisions regarding app marketing and performance optimizations.

https://firebase.google.com/docs/analytics/
