### ISSUE TITLE
How to unset userID 

### ISSUE THREAD

**Issue by AsmaGargouri** [danwilson/google-analytics-plugin#226]
Is there a way I can unset userID ? 
In my case, I need to apart the behaviour of logged users and unlogged ones. 
To do so, I am calling on login : 
`analytics.setUserId(user.id)`

I am trying to unset UserId after logout, but I couldn't find a way.
I tried analytics.setUserId(undefined) and analytics.setUserId(null). But this does't seem working because it is adding 'null' value as userID  in my reports.

**Comment by victorsosa** [comment]
You don't have to do it; after the tracker is destroy the session end.
