### ISSUE TITLE
App unexpectedly Closed

### ISSUE THREAD

**Issue by ajeesh13** [danwilson/google-analytics-plugin#227]
Hi All,

I have been using this plugin since April.It was working fine.
But yesterday I have updated my android SDK. After that my application got into unexpectedly closed.I have removed plugin one by one from my cordova application using ionic framework. I found this plugin causes the application unexpectedly closing issue.
We are using this plugin for the app logs and we have completed all the functionalities for the apps.
So please give us a quick solution

Thanks & Regards
Ajeesh

**Comment by victorsosa** [comment]
Hi,

can you check the object `window.analytics` before load it

**Comment by victorsosa** [comment]
please check issue #27 if you are using ionic
