### ISSUE TITLE
No more support ?

### ISSUE THREAD

**Issue by belgacea** [danwilson/google-analytics-plugin#228]
Is this project dead ?
Commits have stopped eight months ago and issues/pull requests accumulate..
Anyone know a mature fork that is still in developement ?

**Comment by danwilson** [comment]
If anyone is interested in taking over, I am more than open to it. I can no longer keep up with the ways this plugin is being used on the mix of cordova versions, especially with Android and the google play services. I also cannot keep up with the Ionic specific requests.

**Comment by belgacea** [comment]
I understand very well. It's just sad to see this project stopped while the community is still active. I can not keep up this plugin either, because of my inexperience, so I'll wait for the new [Firebase analytics module](https://groups.google.com/forum/#!topic/firebase-talk/MKfIzAtNNuA).
Anyway, thank you for your work and this very helpful tool.

**Comment by victorsosa** [comment]
@danwilson I am interested and willing to take over this project. We can arrange a meeting or just let me know about, by message me the pending stuff, also to coordinate the project transfer.

**Comment by v3ss0n** [comment]
@belgacea firebase analytics module by community , is not so active in development too.

**Comment by victorsosa** [comment]
I want to keep this project alive and active in development. We have a community that depend on it with projects already running with it.

**Comment by v3ss0n** [comment]
The userbase is so big , its over 3k download a week. this project value is already high. why would Owner want to abandon ?

**Comment by victorsosa** [comment]
here is doing on personal reason; you have to understand everybody has a life. We have a community that depend on it, so it up to us to keep this alive.

**Comment by v3ss0n** [comment]
@danwilson  can you handover to @victorsosa  for the sake of community ?

**Comment by victorsosa** [comment]
@danwilson thanks I accepted the invitation as collaborator in this project. Thank you, you are awesome. :+1: 

issues/pull requests accumulated will be process accord to the project and PR will have the priority. It there is anything else just let me know about. Let's make this work.

**Comment by danwilson** [comment]
@victorsosa you are awesome - I very much appreciate your offer and already making things happen! Do you have the same username on npm?

**Comment by danwilson** [comment]
And nevermind... NPM errored out on me when I tried adding you... but it looks like it succeeded after all.

**Comment by victorsosa** [comment]
yes it did thanks
