### ISSUE TITLE
Cannot build for Ionic Android version

### ISSUE THREAD

**Issue by jsnkelvin** [danwilson/google-analytics-plugin#229]
This is the error log, i think it have something to do with the crashlytics integration on branch.io?

A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find com.crashlytics.sdk.android:answers-shim:0.0.3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         https://repo1.maven.org/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/Users/jasonjaputra/Library/Android/sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/Users/jasonjaputra/Library/Android/sdk/extras/android/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
         file:/Users/jasonjaputra/Library/Android/sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.pom
         file:/Users/jasonjaputra/Library/Android/sdk/extras/google/m2repository/com/crashlytics/sdk/android/answers-shim/0.0.3/answers-shim-0.0.3.aar
     Required by:
         :android:unspecified > io.branch.sdk.android:library:1.14.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Please help. Thanks!

**Comment by victorsosa** [comment]
Please check you project, this seems to be a dependency issue in you project, nothing related to this plugin.

`Could not find com.crashlytics.sdk.android:answers-shim:0.0.3.`
