### ISSUE TITLE
What happens when device is offline?

### ISSUE THREAD

**Issue by CoenWarmer** [danwilson/google-analytics-plugin#23]
Does the plugin store statistics until connection is restored? Or are those statistics simply not tracked?

**Comment by canadaka** [comment]
Can anyone confirm that this plugin indeed stores and sends stats that were generated offline, once online?

Google SDK seems to call this "Dispatching".
It is used here:
https://github.com/danwilson/google-analytics-plugin/blob/5957d36fef3242487c38f6348ba391ac85394c7d/android/UniversalAnalyticsPlugin.java#L114

"If a user loses network access or quits your app while there are still hits waiting to be dispatched, those hits are persisted in local storage. They will be dispatched the next time your app is running and dispatch is called."
https://developers.google.com/analytics/devguides/collection/android/v3/dispatch
