### ISSUE TITLE
Google Analytics UserId Tracking not working

### ISSUE THREAD

**Issue by chunfai92** [danwilson/google-analytics-plugin#230]
Hello,

I had try to set the user id tracking with google analytics but there are errors from logcat

`window.analytics.setUserId(uid); `

Errror from logcat
Attempted to send a second callback for ID: UniversalAnalytics659791081
Result was:  "Invalid section"

**Comment by lacvapps** [comment]
+1 Looking into this now.

**Comment by victorsosa** [comment]
@lacvapps  thanks

**Comment by lacvapps** [comment]
@victorsosa I fixed my issue by adding all the google play services and the google repository in the Android SDK Manager

**Comment by victorsosa** [comment]
@lacvapps  thanks. Yep, you need to add google play services and the google repository.
