### ISSUE TITLE
I can't answer PR / issues

### ISSUE THREAD

**Issue by ZiFFeL1992** [danwilson/google-analytics-plugin#237]
![image](https://cloud.githubusercontent.com/assets/5492960/16708395/827f03b2-45f2-11e6-97cc-60542c41d0ec.png)

The answer to that question is in the documentation: https://developers.google.com/analytics/devguides/collection/android/v4/campaigns

cc: @victorsosa

**Comment by victorsosa** [comment]
Ok, thanks for anwser.

Sorry, but I don't see the issue yet; you are referring to the permissions android:permission="android.permission.INSTALL_PACKAGES"

I don't see anything in the doc talking about it.

**Comment by victorsosa** [comment]
Base on the doc, there is no need for this permission. But there is a configuration for a intent:
```
        <intent-filter>
            <action android:name="com.android.vending.INSTALL_REFERRER" />
        </intent-filter>
```

**Comment by victorsosa** [comment]
what I saw missing is the parameter:
`android:enabled="true"
`
in the CampaignTrackingReceiver config.

**Comment by victorsosa** [comment]
this PR while be discarded
