### ISSUE TITLE
Issue with tracker.send

### ISSUE THREAD

**Issue by amolc** [danwilson/google-analytics-plugin#238]
Hello,

I am trying to send the Referrer Parameter. Can someone help me with a small code snippet.

$cordovaGoogleAnalytics.send(new HitBuilders
                .ScreenViewBuilder()
                .setCampaignParamsFromUrl(deepLinkUrl)
                .build()
                );

Is the code correct.

**Comment by victorsosa** [comment]
Hi,

yea, it seems correct if you send the correct deepLinkUrl parameter it should work.
what is the issue?

**Comment by victorsosa** [comment]
Sorry, this is not correct: I think you are trying to do this:
`window.ga.trackView('Screen Title', 'my-scheme://content/1111?utm_source=google&utm_campaign=my-campaign')`
