### ISSUE TITLE
Integrate in Web project

### ISSUE THREAD

**Issue by justme1** [danwilson/google-analytics-plugin#239]
Hi,

If I have a cordova app + a website - how can I use this plugin on a Website without Cordova?

Thanks

**Comment by victorsosa** [comment]
HI,

Nop, just use the web api from google as should be. Take a look to the documentation.

https://developers.google.com/analytics/devguides/collection/

Thanks.

**Comment by justme1** [comment]
@victorsosa  so in a Cordova/Web project the entire flow is:

if (CORDOVA) {
   // use google-analytics-plugin API;
} else {
  // use analytics.js API from Google
}

Is this really the solution?

**Comment by victorsosa** [comment]
ok, the idea is use it for the web and mobile at the same time, then yes that code will be a solution.

**Comment by justme1** [comment]
@victorsosa  thanks.

**Comment by victorsosa** [comment]
@justme1 you welcome
