### ISSUE TITLE
Error while building Android

### ISSUE THREAD

**Issue by galsch** [danwilson/google-analytics-plugin#240]
Hi,

After installing the plugin I get when running `cordova builtd android' the following error:

Found com.google.android.gms:play-services-analytics:+, but version 9.0.0 is needed for the google-services plugin.
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

How to fix this?
I've updated to latest version of both Google Play Services and Google Repository (version 31).

Please assist my project doesn't compile now...

**Comment by galsch** [comment]
In project.properties I changed line to:

cordova.system.library.2=com.google.android.gms:play-services-analytics:9.0.0

That seems to have solved my issue.

**Comment by victorsosa** [comment]
thanks, for take a look into it.
