### ISSUE TITLE
UniversalAnalyticsPlugin.m:219:43: Use of undeclared identifier 'screenName'

### ISSUE THREAD

**Issue by ricardoAntolin** [danwilson/google-analytics-plugin#242]
When generate proyect for IOS cant compile because this issue in UniversalAnalyticsPlugin.m line 219

**Comment by victorsosa** [comment]
Hi,

Please try again. I fixed the compile issue.

**Comment by ricardoAntolin** [comment]
Yes now is ok, thanks
