### ISSUE TITLE
setAppVersion() is not working

### ISSUE THREAD

**Issue by AshishMeshram** [danwilson/google-analytics-plugin#256]
App version is 0.0.1 by default

My code :

    window.ga.startTrackerWithId('UA-XXXXX-1');		
    window.ga.debugMode();
    window.ga.trackView('Home');
    window.ga.trackEvent('event', 'Event', 'Application Launched');
    window.ga.setAppVersion('1.0.0');
    window.ga.trackException('Fatal Error', true);

**Comment by victorsosa** [comment]
Hi,

Even if you don't set the appversion it should use the app version defined in the android package. I tested this out and it is working setting the appversion.

**Comment by victorsosa** [comment]
Are you using IONIC??

**Comment by AshishMeshram** [comment]
It is taking app version defined in android package by default. I never looked into config.xml Yes I am using IONIC!
