### ISSUE TITLE
window.ga.trackView() stops to track

### ISSUE THREAD

**Issue by stileinverso** [danwilson/google-analytics-plugin#257]
I'm using PhoneGap Build.
I've inserted this code  into onDeviceReady function

    window.ga.startTrackerWithId('UA-*********'); // <- Hidden only here
    window.ga.setAppVersion(version);
    window.ga.setAnonymizeIp(true);
    window.ga.trackView('index');

And I can see in Google Analytics when I open my app on my device (view: index).

There is a timed function in my code that tracks when the user changes app's view.
Shortly its content:

    myConsoleLog(page_name);
    window.ga.trackView(page_name);      
    window.ga.trackEvent(company_name, offer_name);

Where myConsoleLog is a function that replaces console.log function showing correctly the current page (view) name.
The problem is that Google Analytics stops to track view!
Nothing seems to happen.

Solutions?

**Comment by victorsosa** [comment]
Log please, it will be helpful

**Comment by stileinverso** [comment]
Which log do you need?

**Comment by victorsosa** [comment]
any log will do

**Comment by victorsosa** [comment]
Please change issue #274
