### ISSUE TITLE
Object [object Object] has no method 'exec' when using window.ga.setUserId

### ISSUE THREAD

**Issue by PowerP** [danwilson/google-analytics-plugin#258]
Hi,

when using: 
`window.ga.setUserId(this.user.get('id'));`

I get this error
`
TypeError: Object [object Object] has no method 'exec' at Object.androidExec [as exec] (file:///android_asset/www/cordova.js:940:40) at UniversalAnalyticsPlugin.setUserId (file:///android_asset/www/plugins/cordova-plugin-google-analytics/www/analytics.js:13:11) ....`

The problem is, that I only have it in production and I am not able to reproduce it. Has someone a idea where my problem is? 

thx for every help!
Cheers,
Pirmin

**Comment by victorsosa** [comment]
Can you please post you code too? I meant where are you calling setUserId... and how do set up window.ga?

**Comment by PowerP** [comment]
sorry about that. 

setup:

`bindEvents: function() {
    document.addEventListener('deviceready', this.onDeviceReady, false);
  },

  onDeviceReady: function() {
    window.ga.startTrackerWithId('XXXXXXXX');
    cordova.getAppVersion.getVersionNumber(function(version) {
      window.ga.setAppVersion(version);
    });
  }`


I use Ember.
Old:
`didTransition() {
          let self = this;
          let location = self.router.get('url');
            if (window.ga) {
              if (self.currentModel.user)
                window.ga.setUserId(self.currentModel.user.get('id'));
              window.ga.trackView(location);
              console.log('send location');
            } else
              console.log('ga not ready??');
          });
    },`

my current and new try is to even wait for deviceready event in here. As far as I know, the Listener will instant trigger when deviceready is true. Maybe the 0.3 seconds wait also helps. I don't know if this helps or fixed the problem as long I'm not updating the production but I will in the evening. 

`didTransition() {
      // location is a bit to late with loading. so we wait a bit before we send it.
      let self = this;
      Ember.run.later((function() {
          let location = self.router.get('url');
          document.addEventListener('deviceready', function() {
            console.log('device is ready and fires');
            if (window.ga) {
              if (self.currentModel.user)
                window.ga.setUserId(self.currentModel.user.get('id'));
              window.ga.trackView(location);
              console.log('send location');
            } else
              console.log('ga not ready??');
          });
      }), 300);
    },`

What do you think about it? 
Cheers

**Comment by victorsosa** [comment]
can you check using log that the onDeviceReady function is been called?

**Comment by PowerP** [comment]
I give it a try

**Comment by victorsosa** [comment]
please check issue #27 if you are using ionic

**Comment by victorsosa** [comment]
please check the answer #290 and let me know

**Comment by victorsosa** [comment]
this is related to the v1.7.x issue, th ionic 2 version need to be updated to the lastest version.
