### ISSUE TITLE
Problem integrating this plugin in Mobile First Application project

### ISSUE THREAD

**Issue by hernangiraldo89** [danwilson/google-analytics-plugin#259]
Hi Dan!
I have a problem...
I'm develop an application with: AngularJS, Ionic and Mobile First Platform 7.1(MFP), in this version of MFP I must add the plugin manually.
iOS works fine.
My problem is Android:
**Error: "The import com.google.android cannot be resolved".**
I download Google Play Services with SDK but the problem continues... 
Any idea to solve this problem?
Regards.

**Comment by victorsosa** [comment]
Hi @hernangiraldo89 

please try to add this:

    Android Support Repository
    Android Support Library
    Goole Play Services (you added this already)
    Google Repository

**Comment by victorsosa** [comment]
Also could you please post the complete log.

**Comment by hernangiraldo89** [comment]
I added:
Android Support Repository
Android Support Library

After this, the project compiles and deploy correctly on the device, it didn't happen before.
Now, I try to track an event, but I can't. 
This is the error log:

07-28 17:04:05.514: W/cr_BindingManager(31883): Cannot call determinedVisibility() - never saw a connection for the pid: 31883
07-28 17:04:05.592: W/System.err(31883): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzx;
07-28 17:04:05.592: W/System.err(31883): 	at com.google.android.gms.analytics.internal.zzf.zzaa(Unknown Source)
07-28 17:04:05.593: W/System.err(31883): 	at com.google.android.gms.analytics.GoogleAnalytics.getInstance(Unknown Source)
07-28 17:04:05.593: W/System.err(31883): 	at com.bhdleon.bankoffice.plugins.UniversalAnalyticsPlugin.startTracker(UniversalAnalyticsPlugin.java:138)
07-28 17:04:05.593: W/System.err(31883): 	at com.bhdleon.bankoffice.plugins.UniversalAnalyticsPlugin.execute(UniversalAnalyticsPlugin.java:47)
07-28 17:04:05.593: W/System.err(31883): 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
07-28 17:04:05.593: W/System.err(31883): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:151)
07-28 17:04:05.593: W/System.err(31883): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:61)
07-28 17:04:05.593: W/System.err(31883): 	at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
07-28 17:04:05.593: W/System.err(31883): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
07-28 17:04:05.593: W/System.err(31883): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
07-28 17:04:05.593: W/System.err(31883): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-28 17:04:05.593: W/System.err(31883): 	at android.os.Looper.loop(Looper.java:148)
07-28 17:04:05.593: W/System.err(31883): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-28 17:04:05.593: W/System.err(31883): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzx" on path: DexPathList[[zip file "/data/app/com.bhdleon.bankoffice-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bhdleon.bankoffice-2/lib/arm, /data/app/com.bhdleon.bankoffice-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-28 17:04:05.593: W/System.err(31883): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-28 17:04:05.593: W/System.err(31883): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-28 17:04:05.593: W/System.err(31883): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-28 17:04:05.593: W/System.err(31883): 	... 13 more
07-28 17:04:05.593: W/System.err(31883): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzx
07-28 17:04:05.593: W/System.err(31883): 		at java.lang.Class.classForName(Native Method)
07-28 17:04:05.593: W/System.err(31883): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-28 17:04:05.593: W/System.err(31883): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-28 17:04:05.593: W/System.err(31883): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-28 17:04:05.593: W/System.err(31883): 		... 14 more
07-28 17:04:05.593: W/System.err(31883): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by victorsosa** [comment]
can you please post the code used too?

**Comment by victorsosa** [comment]
add Google Repository too

**Comment by hernangiraldo89** [comment]
Hi @victorsosa! Sorry for my late.

This is my code:
cordova.exec(result, result, 'UniversalAnalytics', 'startTrackerWithId', ['UA-0101010101-01']);
cordova.exec(result, result, 'UniversalAnalytics', 'trackView', ['login']);

Google Repository, added, but the problem continue.

**Comment by victorsosa** [comment]
This should be you code:
```
window.ga.startTrackerWithId('UA-XXXX-YY')
window.ga.trackView('screen title')
```

**Comment by hernangiraldo89** [comment]
it doesn't work!

07-29 09:52:22.723: I/chromium(13727): [INFO:CONSOLE(135)] "TypeError: Cannot read property 'startTrackerWithId' of undefined
07-29 09:52:22.723: I/chromium(13727):     at new LoginController (file:///android_asset/www/default/js/main.js:14556:18)
07-29 09:52:22.723: I/chromium(13727):     at Object.e [as invoke] (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:69:315)
07-29 09:52:22.723: I/chromium(13727):     at x.instance (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:108:451)
07-29 09:52:22.723: I/chromium(13727):     at file:///android_asset/www/default/js/libs/ionic.bundle.min.js:91:474
07-29 09:52:22.723: I/chromium(13727):     at s (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:40:408)
07-29 09:52:22.723: I/chromium(13727):     at v (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:91:458)
07-29 09:52:22.723: I/chromium(13727):     at g (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:84:299)
07-29 09:52:22.723: I/chromium(13727):     at file:///android_asset/www/default/js/libs/ionic.bundle.min.js:83:413
07-29 09:52:22.723: I/chromium(13727):     at I.appendViewElement (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:389:3339)
07-29 09:52:22.723: I/chromium(13727):     at Object.render (file:///android_asset/www/default/js/libs/ionic.bundle.min.js:387:16956)", source: file:///android_asset/www/default/js/libs/ionic.bundle.min.js (135)

**Comment by hernangiraldo89** [comment]
cordova.exec(result, result, 'UniversalAnalytics', 'startTrackerWithId', ['UA-0101010101-01']);
cordova.exec(result, result, 'UniversalAnalytics', 'trackView', ['login']);

This code works correctly in iOS

**Comment by victorsosa** [comment]
Did you try to run the code inside a deviceready listener?
`document.addEventListener('deviceready', function() {})`

**Comment by victorsosa** [comment]
Well in you case is IONIC so should be:
```
myModule.run(function($ionicPlatform) {
    $ionicPlatform.ready(function() {
      // Anything native should go here, like StatusBar.styleLightContent()
    });
  });
```
http://ionicframework.com/docs/ionic-cli-faq/#platform-ready

**Comment by hernangiraldo89** [comment]
I tried this, but doesn't work it either...

**Comment by victorsosa** [comment]
check issue #27
