### ISSUE TITLE
"libAdIdAccess.a" not found

### ISSUE THREAD

**Issue by AbraXus** [danwilson/google-analytics-plugin#265]
Hello everyone, 

When installing the plugin, I get the following error: 

```
Failed to install 'cordova-plugin-google-analytics':CordovaError: Uh oh!
"cordova/plugins/cordova-plugin-google-analytics/ios/libAdIdAccess.a" not found!
```

I see that 'libAdIdAccess.a' is still referenced in your plugin.xml, but it is not in the referenced folder. 

Is this file not used anymore? Or can it be removed from plugin.xml?

**Comment by ventr1x** [comment]
The contributor just broke the plugin with his updates in the last hour.
It worked 30 minutes ago.
Sadly this plugin also doesn't really utilize correct versioning (I have no overview whatsoever what version is how old).
Download the version before 1.5.1, which is apparently 1.0.0, it works for me.

<plugin name="cordova-plugin-google-analytics" spec="1.0.0" source="npm" />

**Comment by AbraXus** [comment]
Wow, that was quick. Thank you! 
1.0.0 worked for me, too. 

I'll leave this issue open until it has been fixed.

**Comment by mjaverto** [comment]
Same here.

**Comment by victorsosa** [comment]
Thanks, I will fix the issue as soon as possible.

**Comment by victorsosa** [comment]
cordova-plugin-google-analytics@1.5.2
The lib was added, test and let me know.

**Comment by victorsosa** [comment]
PR #266
