### ISSUE TITLE
get "analytics not define" when using the plugin

### ISSUE THREAD

**Issue by ChenReuven** [danwilson/google-analytics-plugin#27]
i have a working PhoneGap/Cordova Project Ver 3.5. i try to work with GA with this plugin, But without success: https://github.com/danwilson/google-analytics-plugin

i success to install the plugin via this command: cordova plugin add https://github.com/danwilson/google-analytics-plugin.git

when i try the usage the plugin it faild. for example: analytics.startTrackerWithId('UA-XXXX-YY') // UX-2323-23 for example

Any "analytics" function that i try to use fail with error: "analytics is not defind"
1. i try via local server - get "analytics is not defind"
2. i try in simulator - get empty and white screen
3. i try on Real Device and also get empty and white screen

Please Help :) Thanks, Chen.R

**Comment by PRotig** [comment]
Hello Guys, 
I'm facing this exact problem, tried all propositions but never succeed..
Dis you find the solution ? 
Thanks a lot...

**Comment by caionorder** [comment]
Hello!!! 
i have same problem... ;(

**Comment by Ankitude** [comment]
Hello Guys,

I am also facing the same issue.
"window.analytics" is always showing 'undefined'.
I also waited for the Device Ready event, but still it shows 'undefined'.
Tried several ways, but failed.
Any quick help will be greatly appreciated.

**Comment by CreativeManix** [comment]
I too have the same issue with ionic

**Comment by Ankit-Prajapati** [comment]
Hi CreativeManix,

Where are you utilizing the Google Analytics Plugin?
Actually, in my environment, I needed to build the Template before utilizing the Plugin.
Building the template worked for me.

**Comment by cardex107** [comment]
Hello, I put the code in "Create" function for phaser game, not working in emulator but after installing in my mobile works fine.
`Game.prototype.create = function() {
		window.analytics.startTrackerWithId('UA-XXXXXXXX-X');
		window.analytics.debugMode();`

**Comment by rafaelbiten** [comment]
I was having the same problem and the best solution I found was to keep a flag on the local storage (ie.: 'trackingSet'). So I have an `analyticsService` and on its initialization I force that flag to false

`Something like: localStorageService.set('trackingSet', false);`

Then, whenever an action that needs to be tracked happens, I would check for that flag:

```
if (!trackingSet) {
	window.analytics.startTrackerWithId('UA-9975041-59');
	localStorageService.set('trackingSet', true);
}
```

Having a setTimeout on the deviceReady was working too, but I prefer this solution better.
Hope someone finds a better solution though.

 taking care of the analytics, I would check

**Comment by ridan** [comment]
What is the status of this issue? I am getting the same issue and tried a lot of these solutions but haven't had any luck. I am using ionic.

**Comment by cardex107** [comment]
The last solution is put in the config.xml inside `<widget ` the `package="com.example.analytics"`

**Comment by DianitaCAH** [comment]
Hello @danwilson I´m new at Cordova and I´ve tried different ways to fix this issue but no success. I´m using Cordova 6.1.1 and the platforms that have are only Android and iOS. I´m calling inside my document.ready 
document.addEventListener('deviceready', function () {
                    window.analytics.trackView('index');
                }, false);

But I never see to get any other error than "Uncaught TypeError: Cannot read property 'trackView' of undefined " and there is no feedback on my GA analytics page.

Thanks!

**Comment by devDuvan** [comment]
Hi, I had the same problem, the problem is that the plugin analytics delay in execution, so when ready to ionicPlatform "analytics" is made is still undefined, I solved creating a service functions analytics where the callback handling success and error checking that if the error is that the tracker has not yet started, then check and start.

**For example for trackView**

angular.module('app.utils.analytics', [])

.service('$analytics', function() {

    var initialize = function () {
        if (typeof analytics !== 'undefined') {
            analytics.startTrackerWithId('xxxxx');
            analytics.enableUncaughtExceptionReporting(true);
        } else {
           console.log("Google Analytics Unavailable");
        }
    };

    let error = function (err) {
        if (err !== 'Tracker not started' ) return;

        initialize();
    };

    this.trackView = function(view) {
        if (typeof analytics !== 'undefined') analytics.trackView(view, success, error);
    };

    this.initialize = initialize;
});
