### ISSUE TITLE
utm track not work in ios

### ISSUE THREAD

**Issue by WilsonFpz** [danwilson/google-analytics-plugin#271]
Hi
I followed https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns#url-builder to generate utm track link to app store.
But the result is not "direct/none" in google analytics itune report, which is not the one I set up in the url builder.
any idea? thanks.

**Comment by victorsosa** [comment]
PR #270

**Comment by victorsosa** [comment]
ver1.5.4 will coming out soon
