### ISSUE TITLE
trackView makes app crash

### ISSUE THREAD

**Issue by kessiler** [danwilson/google-analytics-plugin#272]
I'm sure this is related to the PR https://github.com/danwilson/google-analytics-plugin/pull/270

Cordova CLI: 6.3.1
Google Analytics plugin: 1.5.3

**Steps to reproduce:**
```
platform.ready().then(() => {
   GoogleAnalytics.startTrackerWithId("UA-81681718-1");
   GoogleAnalytics.trackView('mapsView');
});
```

**Stack trace:**
>  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull rangeOfString:]: unrecognized selector sent to instance 0x2e7c398'
> 	*** First throw call stack:
> 	(
> 		0   CoreFoundation                      0x02c4f494 __exceptionPreprocess + 180
> 		1   libobjc.A.dylib                     0x026e2e02 objc_exception_throw + 50
> 		2   CoreFoundation                      0x02c59253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
> 		3   CoreFoundation                      0x02b8e89d ___forwarding___ + 1037
> 		4   CoreFoundation                      0x02b8e46e _CF_forwarding_prep_0 + 14
> 		5   ionic-maps                          0x004585c5 +[GAIStringUtil urlParams:] + 46
> 		6   ionic-maps                          0x0045cc79 -[GAIDictionaryBuilder setCampaignParametersFromUrl:] + 105
> 		7   ionic-maps                          0x0011df5b __38-[UniversalAnalyticsPlugin trackView:]_block_invoke + 443
> 		8   libdispatch.dylib                   0x0551a9e3 _dispatch_call_block_and_release + 15
> 		9   libdispatch.dylib                   0x055386ed _dispatch_client_callout + 14
> 		10  libdispatch.dylib                   0x05521850 _dispatch_root_queue_drain + 744
> 		11  libdispatch.dylib                   0x05521561 _dispatch_worker_thread3 + 108
> 		12  libsystem_pthread.dylib             0x0586125c _pthread_wqthread + 1050
> 		13  libsystem_pthread.dylib             0x0585ef56 start_wqthread + 34
> 	)
>

**Comment by victorsosa** [comment]
ver1.5.4 will coming out soon

**Comment by ansarikhurshid786** [comment]
Hi, 
I am also facing same issue. Crashing in android after installing this plugin. I can't see error or warning log in console log. 

Crashing first time after new installation. 
Reopen application neither crashing nor working.
