### ISSUE TITLE
No data under Demographics 

### ISSUE THREAD

**Issue by paramesh016** [danwilson/google-analytics-plugin#276]
Hi i have one doubt ,even after adding the below line
window.analytics.setAllowIDFACollection(true);
and there is no error in the console 
and after enabling demographics in my google analytics account

i shows "There is no data for this view."

![demographics](https://cloud.githubusercontent.com/assets/5110852/17481314/28091c50-5d9a-11e6-9cbb-35fb0d8b2c3f.png)

can u help pls with this please .thank you

**Comment by victorsosa** [comment]
The code is set as the documentation mention here: https://developers.google.com/analytics/devguides/collection/android/v4/optional-features

I am getting similar issue, mine said:

> Your Demographics and Interest Reports have been enabled, but your Analytics tracking code does not include the necessary support to show them. Learn more about the simple, one-line, one-time change to your tracking code to add this support.

Maybe we are ignoring something else?

**Comment by victorsosa** [comment]
I found in the docs this:

> Some data in this report may have been removed when a threshold was applied.

You can see that in yellow below the report title; please read the docs.

> Data thresholds
> 
> Thresholds are applied to prevent anyone viewing a report from inferring the demographics or interests of individual users. When a report contains Age, Gender, or Interest Category (as a primary or secondary dimension, or as part of an applied segment), a threshold may be applied and some data may be withheld from the report. For example, if there are fewer than N instances of Gender=male in a report, then data for the male value may be withheld.
> 
> If a threshold has been applied to a report, you will see a notice below the report title.

**Comment by paramesh016** [comment]
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-80709447-1', 'auto');
ga('send', 'pageview');
</script>
<script async src='js/analytics.js'></script>



In one of the article i read it requested me to add the above code 

but still its of no use

**Comment by paramesh016** [comment]
@victorsosa  : so we need to make sure large no of people are using this app , so that demographics data is populated ?

**Comment by victorsosa** [comment]
@paramesh016 yes, sir; That is correct

**Comment by paramesh016** [comment]
@victorsosa : ok thank you sir.
and also were u able to enable " **Enable Remarketing and Advertising Reporting Features for a web property** "
