### ISSUE TITLE
Device offline?

### ISSUE THREAD

**Issue by sadikyalcin** [danwilson/google-analytics-plugin#284]
It has been asked before but couldn't see an answer. What happens when a device is offline? I didn't see anything in local storage / session storage.

It is quite vital so I would be happy if you could enlighten me as soon as possible.

Thank you.

**Comment by victorsosa** [comment]
GA save those requests and try to resend them when it go on-line again, that's go enough answer?

**Comment by sadikyalcin** [comment]
That is a very good answer. Thanks for replying so quickly. Just for clarity, does the GA api do this or the plugin?

**Comment by victorsosa** [comment]
Yes, GA api does it

**Comment by sadikyalcin** [comment]
Quick answer.
Problem solved.
Less work.
Everybody happy :)

**Comment by victorsosa** [comment]
you welcome
