### ISSUE TITLE
OS version is not set in iOS 10 beta

### ISSUE THREAD

**Issue by remisture** [danwilson/google-analytics-plugin#285]
Traffic from devices running iOS 10 beta shows up as "(not set)"

**Comment by victorsosa** [comment]
Some data field can be set by the GA as not set; by the GA's algorithm; we don't control it.

**Comment by victorsosa** [comment]
Also this could be a bug in the GA api because the IOS 10 beta is the lastest release, in that case you should check the issue list:

https://code.google.com/p/analytics-issues/issues/list

**Comment by remisture** [comment]
Thank you 👍
