### ISSUE TITLE
Conflicting with Admob Pro

### ISSUE THREAD

**Issue by galcivar** [danwilson/google-analytics-plugin#286]
Hi,

I have the exact same issue as described in the following link:
[Cordova com.danielcwilson.plugins.googleanalytics with com.admob.google](http://stackoverflow.com/questions/31451872/cordova-com-danielcwilson-plugins-googleanalytics-with-com-admob-google)

Will be there a solution for it or is there a solution other than changing the plugin?

Thanks

**Comment by victorsosa** [comment]
The anwser is no, please check #262 issue for more details.
