### ISSUE TITLE
Platform Browser

### ISSUE THREAD

**Issue by danielgarnier** [danwilson/google-analytics-plugin#288]
Hello! 

I´m developing a PWA (progressive web app). So my platform is the Browser.
I have added your plugin using "cordova plugin add cordova-plugin-google-analytics" command line. As the installation has completed with no erros for browser platform, I had thought that this plugin support browser platform. But when I tested it, I've got this error message: Error: exec proxy not found for :: UniversalAnalytics :: startTrackerWithId

So I came back here and read your README.md more carefully. I'm understanding that your plugin does not support browser platform and the workaround is integrating with lavaca framework. Am I correct?

THanks
Daniel

**Comment by victorsosa** [comment]
please check #53
