### ISSUE TITLE
Strategy to handle asynchronous loading

### ISSUE THREAD

**Issue by sydneyhenrard** [danwilson/google-analytics-plugin#290]
Hi, 

The plugin is working great but sometimes I get `Cannot read property 'trackView' of undefined`. `window.ga` is undefined because the plugin is not loaded when the call is done.

I would like to find a strategy to recover from that error. My idea is to wrap every call and check if `window.ga` is defined, if so, the call is done, and if not, the call is done in a `setTimeout`.

```
	factory.trackView = function (view) {
		if (typeof $window.ga !== 'undefined') {
			$window.ga.startTrackerWithId('XXXXXXXXXX');
			$window.ga.trackView(view);
		} else {
			setTimeout(function () {
				if (typeof $window.ga !== 'undefined') {
					$window.ga.startTrackerWithId('XXXXXXXXXX');
					$window.ga.trackView(view);
				}
			}, 2000);
		}
	}
```

The reason I call `startTrackerWithId` is because I can't be sure that it's been called previously with success. The call might have been done previously when `window.ga` was undefined.

```
T: window.ga.startTrackerWithId unsuccessful, so will try again in 2s
T+1s: window.ga.trackView called right away because window.ga is now defined.
T+2s: window.startTrackerWithId is successful but occurs after the trackView
```

Q: Is it an issue to call several times `startTrackerWithId`?

I guess if `startTrackerWithId` has not been called successfully before `trackView`, the hit will not be published to GA.

What do you think?

**Comment by victorsosa** [comment]
First you need to call in this way; Before each plugin you must check if your device has fully loaded, and if the plugins are available using a native cordova event called deviceready. Implement it like so:

```
function sucess() {
  $window.ga.trackView(view);
}
document.addEventListener("deviceready", function () {
  window.ga.startTrackerWithId('XXXXXXXXXX, success, error);
}, false);
```
> Because the call is async

But you can call  $window.ga.trackView(view) anytime, right after `deviceready` event; but is you need to call it right after the call of `startTrackerWithId` then use the success method as above.

Q: Is it an issue to call several times startTrackerWithId?
yes, it is an issue call several times `startTrackerWithId()`, it need to be call only ones.

**Comment by sydneyhenrard** [comment]
I already call `startTrackerWithId` within a `deviceready` event. But I'll check that all my calls are triggered after the `deviceready` event.

Do you know what happens when a `trackView` is called before the `startTrackerWithId`?

**Comment by victorsosa** [comment]
you can't call it before, `trackview` use the tracker object create by `startTrackerWithId`

**Comment by sydneyhenrard** [comment]
I checked my code, and I called trackEvent before the `deviceready` event. To fix it I wrapped all methods I use this way:

```
	factory.trackView = function (view) {
		if (typeof $window.ga !== 'undefined') {
			$window.ga.trackView(view);
		} else {
			$log.error('Called trackView when Google Analytics was undefined, was it ready?' + isReady + ' - ' + view);
			setTimeout(function () {
				var msg = 'Second try trackView ' + view;
				if (typeof $window.ga !== 'undefined') {
					$window.ga.trackView(view);
					msg += ' SUCCESS';
				}
				$log.error(msg);
			}, 2000);
		}
	}
```
