### ISSUE TITLE
Tracker not started - only iOS - Ionic2

### ISSUE THREAD

**Issue by philipphalder** [danwilson/google-analytics-plugin#291]
Hello - everything works fine on Android but the Tracker is not starting on iOS.

```
import {GoogleAnalytics} from 'ionic-native';

    platform.ready().then(() => {
      StatusBar.styleDefault();
      // --- Google Analytics ---
      //GoogleAnalytics.debugMode();
      GoogleAnalytics.startTrackerWithId("UA-XXXXXXXX-X");   //I replaced it with my ID

      GoogleAnalytics.enableUncaughtExceptionReporting(true)
        .then((_success) => {})
        .catch((_error) => {
        console.log("ERROR Google Analytics:", _error)
      })
    });
```

**Error**: Tracker not started

Thanks for help :-)

**Comment by victorsosa** [comment]
please check answer #290 and let me know

**Comment by cernym43** [comment]
Hi, I have opposite problem. I am using Ionic2 and same code like above. On iOS everything work great but on Androind nothing happen. No error or warnings. Any ideas how can I find the problem? Thanks

**Comment by victorsosa** [comment]
@cernym43 please check that you have the google services api in you android emulator env

**Comment by victorsosa** [comment]
issue #168

**Comment by cernym43** [comment]
@victorsosa I am not using android emulator but real device. I tried downgrade plugin to older version. After app start it shows this error:
<img width="792" alt="snimek obrazovky 2016-09-26 v 18 14 13" src="https://cloud.githubusercontent.com/assets/15231881/18842415/34d6c558-8415-11e6-865f-9c025b55cca4.png"> **but** even with the error it works correctly (I can see behavior in GA). Any ideas how can I get rid of this error which does not appears in version 1.6? Thanks a lot, for you time!

**Comment by victorsosa** [comment]
Try to use this instead:
GoogleAnalytics.enableUncaughtExceptionReporting(true, function(){
//success
}, function(){
//error
});

because there is not promise.

**Comment by Bloggerschmidt** [comment]
Same problem here. iOS fine, Android not. Downgrading plugin doesn't solve anything. Error handling like `try` and `catch` or  `enableUncaughtExceptionReporting` don't work and I don't know why. Tricky.

**Comment by Bloggerschmidt** [comment]
Okay. It turns out that it depends on a root android device, muah. So, only work with clean devices! Everything okay from here now.

**Comment by peterpeterparker** [comment]
@cernym43 did you find a solution for that issue?

Same here. Everything alright on my Android phone (I see the results in my google analytics) but face the same issue while debugging in Xcode 8 / iPhone 6 / OS 9

The error I got is the following:

> Tracker not started

**Comment by peterpeterparker** [comment]
Well then, I refactored all the code, create a service just to handle these statistics and now it seems kind of working.

**Comment by victorsosa** [comment]
@peterpeterparker please post some example code so others can see the right way to use it. Thanks.

**Comment by peterpeterparker** [comment]
here you go @victorsosa 

I created a service like this:

    @Injectable()
    export class GoogleAnalyticsService {

    eventsNotSent:any[] = new Array();
    trackerInitialized:boolean = false;

    trackView(viewName:string) {
        if (typeof window.analytics === 'undefined') {
            this.eventsNotSent.push({viewName: viewName});
        } else {
            this.initGoogleAnalytics().then(() => {
                this.trackEventsNotSent().then(() => {
                    GoogleAnalytics.trackView(viewName).then(() => {
                        // Do nothing
                    });
                });
            }, (error: any) => {
                this.eventsNotSent.push({viewName: viewName});
            });
        }
    }
     
     private trackEventsNotSent():Promise<{}> {
        return new Promise((resolve) => {
            if (Comparator.isEmpty(this.eventsNotSent)) {
                resolve();
            } else {
                let promises = new Array();

                for (let i: number = 0; i < this.eventsNotSent.length; i++) {
                        promises.push(GoogleAnalytics.trackView(this.eventsNotSent[i].viewName));
                }

                Observable.forkJoin(promises).subscribe(
                    (data:any) => {
                        this.eventsNotSent = new Array();
                        resolve();
                    });
            }
        });
    }

    private initGoogleAnalytics():Promise<{}> {
        return new Promise((resolve, reject) => {
            if (this.trackerInitialized) {
                resolve();
            } else {
                    GoogleAnalytics.startTrackerWithId('MY_TRACKER_ID').then(() => {
                    window.cordova.getAppVersion.getVersionNumber().then((version: string) => {
                        GoogleAnalytics.setAppVersion(version).then(() => {
                            this.trackerInitialized = true;
                            resolve();
                        }, (error: any) => {
                            // GA init is ok
                            this.trackerInitialized = true;
                            resolve();
                        });
                    }, (error: any) => {
                        // GA init is ok
                        this.trackerInitialized = true;
                        resolve();
                    });
                }).catch((error: any) => {
                    // Do nothing
                    this.trackerInitialized = false;
                    reject(error);
                });
            }
        });
    }
}

**Comment by victorsosa** [comment]
Thanks, this will help other to create their own using Ionic 2. 
I myself use Ionic 1 yet.

**Comment by baltazaroliveira** [comment]
I have issue resolved. The problem was on my device.

**Comment by fttx** [comment]
I've the same issue on android, ios doesn't print errors, i guess that is working 

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 8.0 Build version 8A218a
```

Tried on android 5 with an non-rooted phone.

```
constructor(platform: Platform) {
    platform.ready().then(() => {
      console.log("startTrackerWithId")
      GoogleAnalytics.startTrackerWithId('UA-87867313-2');
      setTimeout(function () {
        GoogleAnalytics.trackView('TestHome', 'TestHome').then(() => {
          console.log("trackView")
        });
      }, 20000)
    });
  }
```

output 

![image](https://cloud.githubusercontent.com/assets/5663423/20568009/3d9983e8-b19b-11e6-8d09-ebe67800c5e9.png)

**Comment by peterpeterparker** [comment]
@fttx try to put your tracker code in a provider/service, that solved my issue

**Comment by criticalpixel** [comment]
@peterpeterparker can you give us an example that's working for you? I'm getting the same error as @fttx , Tracker not started, even if I have it in a provider :(

**Comment by peterpeterparker** [comment]
@criticalpixel you have it here a couple of post above, I posted my all provider codes (see GoogleAnalyticsService)

**Comment by criticalpixel** [comment]
I've tried the above service. Problem is that the `startTrackerWithId` never resolves... it never sets 
`trackerInitialized = true;` 

As far as I know, GoogleAnalytics will only work after platform is ready, as this is when the plugin is available to us. It's like as if `GoogleAnalytics.startTrackerWithId('UA-****-1');` doesn't work.

I'm just stuck on this. Not sure what I'm doing wrong :(

**Comment by peterpeterparker** [comment]
@criticalpixel yep "of course" the service should be called after the platform is ready

in my case I've got an abstract page above every pages, there I've got my service call which I call from my pages constructor or where I need them. Also I catch 'cordova' because it doesn't work in a local browser.

    protected gaTrackView(platform: Platform, googleAnalyticsService: GoogleAnalyticsService, viewName: string) {
        platform.ready().then(() => {
            if (platform.is('cordova')) {
                googleAnalyticsService.trackView(viewName);
            }
        });
    }

    protected gaTrackEvent(platform: Platform, googleAnalyticsService: GoogleAnalyticsService, category: string, action: string) {
        platform.ready().then(() => {
            if (platform.is('cordova')) {
                googleAnalyticsService.trackEvent(category, action);
            }
        });
    }

**Comment by fttx** [comment]
Same issue with this configuration:

app.component.ts
![image](https://cloud.githubusercontent.com/assets/5663423/20600430/f0e2ccc6-b253-11e6-8de7-d9219a6b5e5c.png)

ga-provider.ts
![image](https://cloud.githubusercontent.com/assets/5663423/20600399/c4c2b6d8-b253-11e6-9e0c-4b9c444ffa2d.png)

Will try with the code you posted above.
Btw wich version of the plugin are you using? I've 1.7.1

**Comment by peterpeterparker** [comment]
@fttx if it still doesn't work, maybe try to trigger your first call (or add your code) not in the app.component constructor but in your first page/tab. 

I don't call my service from the app.component but "only" from my pages, maybe that's a difference too (since it's in a page and not in the app.component constructor, my calls are triggered a little bit later which without knowing helped me)

**Comment by fttx** [comment]
If i downgrade to 1.6.0 it works! What's your plugin version?

**Comment by peterpeterparker** [comment]
1.6.0 ;)

**Comment by criticalpixel** [comment]
@fttx about to try 1.6.0. Back in 5 🙏

**Comment by criticalpixel** [comment]
Ok, looks like the latest version is buggy. **1.6.0 does the trick!** call trackEvent after startTrackerWithId is resolved and it works 👍 

<img width="676" alt="app_component_ts_ _de_tmob_android" src="https://cloud.githubusercontent.com/assets/3206397/20601913/dfff90a2-b252-11e6-9446-0c7c39e4a5f9.png">
![events_-_analytics](https://cloud.githubusercontent.com/assets/3206397/20601928/f637571a-b252-11e6-9958-4e071057c49a.png)

Thanks @peterpeterparker & @fttx for your help!

**Comment by fttx** [comment]
@peterpeterparker I added the code for trackEvent method in your service: https://github.com/fttx/barcode-to-pc-app/blob/master/src/providers/google-analytics.ts

**Comment by peterpeterparker** [comment]
@fttx cool to hear that code helped. if you find some improvements, let me knows ;)

**Comment by victorsosa** [comment]
Ok, Thanks you guys for the inside; 1.7.0 signature changed to window.ga.startTrackerWithId('UA-XXXX-YY', 30) where 30 is the interval period. Maybe this is the root cause of the problem; Have anyone check the android logcat for errors? (It seems like this is not working only on Android)

**Comment by fttx** [comment]
Logcat on 1.7.1: 

```
11-25 11:55:36.004 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 14 : Hello GaProvider Provider
11-25 11:55:36.004 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(14)] "Hello GaProvider Provider", source: file:///android_asset/www/build/main.js (14)
11-25 11:55:36.523 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1223 : deviceready has not fired after 5 seconds.
11-25 11:55:36.523 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(1223)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1223)
11-25 11:55:36.524 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1216 : Channel not fired: onPluginsReady
11-25 11:55:36.524 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(1216)] "Channel not fired: onPluginsReady", source: file:///android_asset/www/cordova.js (1216)
11-25 11:55:36.524 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1216 : Channel not fired: onCordovaReady
11-25 11:55:36.525 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(1216)] "Channel not fired: onCordovaReady", source: file:///android_asset/www/cordova.js (1216)
11-25 11:55:37.097 21806-21806/com.ionicframework.testanalytics983093 D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/index.html)
11-25 11:55:37.112 21806-21984/com.ionicframework.testanalytics983093 I/App: WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
11-25 11:55:37.126 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 19 : Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
11-25 11:55:37.126 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(19)] "Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.", source: file:///android_asset/www/build/main.js (19)
11-25 11:55:37.126 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 19 : DEVICE READY FIRED AFTER
11-25 11:55:37.127 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(19)] "DEVICE READY FIRED AFTER", source: file:///android_asset/www/build/main.js (19)
11-25 11:55:37.164 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 14 : startTrackerWithId
11-25 11:55:37.164 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(14)] "startTrackerWithId", source: file:///android_asset/www/build/main.js (14)
11-25 11:55:42.876 6123-12381/com.android.vending I/PlayCommon: [17994] com.google.android.play.a.g.e(862): Preparing logs for uploading
11-25 11:55:42.877 6123-12381/com.android.vending I/PlayCommon: [17994] com.google.android.play.a.g.e(864): No file ready to send
11-25 11:55:45.590 838-1085/system_process D/sensors_hal_Time: tsOffsetIs: Apps: 144928829341549; DSPS: 454048602; Offset : 131072363358612
11-25 11:55:57.333 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 12 : EXCEPTION: Uncaught (in promise): Tracker not started
11-25 11:55:57.334 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(12)] "EXCEPTION: Uncaught (in promise): Tracker not started", source: file:///android_asset/www/build/main.js (12)
11-25 11:55:57.342 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 12 : ORIGINAL STACKTRACE:
11-25 11:55:57.342 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(12)] "ORIGINAL STACKTRACE:", source: file:///android_asset/www/build/main.js (12)
11-25 11:55:57.350 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 12 : Error: Uncaught (in promise): Tracker not started
                                                                                                   at s (file:///android_asset/www/build/polyfills.js:3:8568)
                                                                                                   at s (file:///android_asset/www/build/polyfills.js:3:8391)
                                                                                                   at file:///android_asset/www/build/polyfills.js:3:8902
                                                                                                   at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
                                                                                                   at Object.onInvokeTask (file:///android_asset/www/build/main.js:3:13172)
                                                                                                   at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
                                                                                                   at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
                                                                                                   at i (file:///android_asset/www/build/polyfills.js:3:8028)
11-25 11:55:57.350 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(12)] "Error: Uncaught (in promise): Tracker not started
                                                                                      at s (file:///android_asset/www/build/polyfills.js:3:8568)
                                                                                      at s (file:///android_asset/www/build/polyfills.js:3:8391)
                                                                                      at file:///android_asset/www/build/polyfills.js:3:8902
                                                                                      at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:14051)
                                                                                      at Object.onInvokeTask (file:///android_asset/www/build/main.js:3:13172)
                                                                                      at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:13987)
                                                                                      at e.runTask (file:///android_asset/www/build/polyfills.js:3:11411)
                                                                                      at i (file:///android_asset/www/build/polyfills.js:3:8028)", source: file:///android_asset/www/build/main.js (12)
11-25 11:55:57.373 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/polyfills.js: Line 3 : Unhandled Promise rejection:
11-25 11:55:57.373 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(3)] "Unhandled Promise rejection:", source: file:///android_asset/www/build/polyfills.js (3)
11-25 11:55:57.470 21806-21806/com.ionicframework.testanalytics983093 D/SystemWebChromeClient: file:///android_asset/www/build/polyfills.js: Line 3 : Error: Uncaught (in promise): Tracker not started
11-25 11:55:57.470 21806-21806/com.ionicframework.testanalytics983093 I/chromium: [INFO:CONSOLE(3)] "Error: Uncaught (in promise): Tracker not started", source: file:///android_asset/www/build/polyfills.js (3)
```

**Comment by victorsosa** [comment]
Well there is not java error; just a javascript promise issue.

**Comment by swapnil2993** [comment]
Downgrading from 1.7 to version 1.6.0 worked for me.

**Comment by victorsosa** [comment]
This bug is related to IONIC 2 using Ionic-native; please check https://github.com/driftyco/ionic-native/issues/940 
The ionic-native and ngCordova are wrapper API that didn't implement the parameters quick enough to avoid conflict. There is no fix need from google-analytics-plugin to be made.
This is because since version 1.7.x we change some parameters.

**Comment by fxlemire** [comment]
Instead of downgrading the plugin from 1.7.x to 1.6.0, updating `ionic-native` to 2.2.16 did the trick.

**Comment by victorsosa** [comment]
@fxlemire Thanks you, people pleas upgrade `ionic-native`. There is no fix need from google-analytics-plugin to be made.

**Comment by martingra** [comment]
@victorsosa @fxlemire I have downgrade the plugin version to 1.6.0, but still not working. I'm not receiving any error, but the event is not tracked in ga. I want to update the ionic-native(I currently have the version ionic-native@1.3.10). For any reason, when trying "npm update ionic-native" is not updating my ionic-native version. Can any of you walk me through the update?

**Comment by fxlemire** [comment]
@martingra Don't downgrade the plugin and simply set your ionic-native to 2.2.16 in your package.json (`"ionic-native": "2.2.16"`), then run `npm i` in your terminal.

**Comment by scott-alvis** [comment]
Is there a downside to writing a provider which calls startTrackerWithId on all calls like below? Or is @peterpeterparker and @fttx solutions more efficient?

This solutions seems to work as expected but there my be more overhead.

Thank you,

Scott

```
import { Injectable } from '@angular/core';
import { Platform } from 'ionic-angular';
import { GoogleAnalytics } from 'ionic-native';
// import { Observable } from 'rxjs/Observable';
// import 'rxjs/add/observable/forkJoin';

@Injectable()
export class GoogleAnalyticsProvider {

  constructor(private platform: Platform) {
  }

  trackView(name: string) {
    this.platform.ready().then(() => {
      GoogleAnalytics.startTrackerWithId('UA-********-1').then(() => {
        GoogleAnalytics.setUserId('user.name').then(() => {
          console.log('Successful call to setUserId with userId : user.name');
        }).catch((error) => {
          console.log('Error calling setUserId -> ' + error);
        });
        GoogleAnalytics.addCustomDimension(1, 'DIM-VALUE').then(() => {
          console.log('Successful call to addCustomDimension key : 1, value : DIM-VALUE');
        }).catch((error) => {
          console.log('Error calling addCustomDimension -> ' + error);
        });
        GoogleAnalytics.trackView(name).then(() => {
          console.log('Successful call to trackView with name : ' + name);
        }).catch((error) => {
          console.log('Error calling trackView -> ' + error);
        });
      }).catch((error) => {
        console.log('Error calling startTrackerWithId -> ' + error);
      });
    });
  }

  trackEvent(category: string, action: string, label?: string) {
    this.platform.ready().then(() => {
      GoogleAnalytics.startTrackerWithId('UA-********-1').then(() => {
        GoogleAnalytics.setUserId('user.name').then(() => {
          console.log('Successful call to setUserId with userId : user.name');
        }).catch((error) => {
          console.log('Error calling setUserId -> ' + error);
        });
        GoogleAnalytics.addCustomDimension(1, 'DIM-VALUE').then(() => {
          console.log('Successful call to addCustomDimension key : 1, value : DIM-VALUE');
        }).catch((error) => {
          console.log('Error calling addCustomDimension -> ' + error);
        });
        GoogleAnalytics.trackEvent(category, action, label).then(() => {
          console.log('Successful call to trackEvent with name : ' + name);
        }).catch((error) => {
          console.log('Error calling trackEvent -> ' + error);
        });
      }).catch((error) => {
        console.log('Error calling startTrackerWithId -> ' + error);
      });
    });
  }

}
```

**Comment by KatzoA** [comment]
Hello,
I would like to join you because I am on an application Ionic 2 or I wish to implement Angulartics2GoogleAnalytics
but I can not. Tabs do not interact with each other. Do you have a solution? Thank you.

**Comment by KatzoA** [comment]
Hello,
I would like to join you because I am on an application Ionic 2 or I wish to implement Angulartics2GoogleAnalytics
but I can not. Tabs do not interact with each other. Do you have a solution? Thank you.
