### ISSUE TITLE
TypeError: undefined is not an object(evaluating 'window.ga.trackEvent')

### ISSUE THREAD

**Issue by G3n3ralTao** [danwilson/google-analytics-plugin#293]
Hi,

I have reinstalled the plugin several times and I always get the following error message. I used the Cordova CLI installation function, but each time I get this when I tried to call trackEvent.

TypeError: undefined is not an object(evaluating 'window.ga.trackEvent')

I followed the instruction in the readme, but I can't get the plugin to work

**Comment by victorsosa** [comment]
Please post some code example

**Comment by G3n3ralTao** [comment]
document.addEventListener("deviceready", function()
            {
                window.ga.startTrackerWithId('UA-XXXXXXXX-4');
                window.ga.trackView('Main Menu');
            }, false);

function trackGoogleAnalytics(pEventName, pEventData){
        if(document.URL.indexOf('http://') === -1 && document.URL.indexOf('https://') === -1)
        {
            window.ga.trackEvent('Category', pEventName, pEventData, "");
        }

**Comment by G3n3ralTao** [comment]
I also get no compilation error. I created a fresh Cordova Project just to be sure, we upgraded to the version 6.3.1 recently. Using the CLI method, my config.xml don'T seam to be modified.

`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.telefiction.salmigondisvillage" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Salmigondis2</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="ios" spec="~4.2.1" />
    <engine name="android" spec="~5.2.2" />
</widget>
`

**Comment by G3n3ralTao** [comment]
Ok, can't seem to copy my config.xml file

**Comment by victorsosa** [comment]
Try to comment the line `window.ga.trackView('Main Menu');` because the call to startTrackerWithId need to alone because is an async call

**Comment by G3n3ralTao** [comment]
They are called separately. I only posted the generic function we use when we call event. The error I get is when I press "Play" in the game. Deviceready has already been called.

**Comment by G3n3ralTao** [comment]
Never Mind, the <script src="cordova.js" /> was remove somehow in the index.html.
Now it's working. 

Thank you for your time.
