### ISSUE TITLE
ionic build issue

### ISSUE THREAD

**Issue by onfire** [danwilson/google-analytics-plugin#299]
Hi there, I am having trouble using this plugin with an ionic project. After adding the plugin using `ionic plugin add cordova-plugin-google-analytics` I then go to do a test build using `ionic build ios`, but I get a heap of compile errors. All the errors are along the lines of this

`
duplicate symbol _llvm.cmdline in:
    /Users/xxx/Documents/WIP/xxx/App/platforms/ios/xxx/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGHit.o)
    /Users/xxx/Documents/WIP/xxx/App/platforms/ios/xxx/Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(GAIUtil.o)
`

Then at the bottom:

`duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
BUILD FAILED
`

I've tried adding/removing the module plus adding/removing the platform but nothing seems to help. I am not really doing anything special so not sure what else to try! 

Any help would be appreciated! Been going round and round for hours.

Ionic version: 1.2.4
Cordova version: 5.1.1
Doing the build on OSX

Thanks

**Comment by victorsosa** [comment]
you should test doing the project build using cordova tools, just for test; instead of ionic to see if is an ionic issue.

**Comment by onfire** [comment]
Just tried using `cordova build ios` and got the same result:

`ld: 232 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1`

**Comment by onfire** [comment]
@victorsosa any other suggestions?

**Comment by victorsosa** [comment]
Nop, I was able to compile the last version on mac OS el capitan

**Comment by victorsosa** [comment]
try use `cordova platform rm ios` and then `cordova platform add ios`.

After that do the build.

**Comment by sathiyaraj-tag** [comment]
I'm also the same issue, But _cordova platform add ios_  execute still facing same error issue.

**Comment by onfire** [comment]
For what its worth, I am still having an issue with this so I thought I would do a test on a fresh install.

This was my process:

```
ionic start myApp tabs
ionic platform add ios
ionic emulate ios -- worked fine

ionic plugin add cordova-plugin-google-analytics
ionic emulate ios -- failed with the original error above
```

@victorsosa  I was thinking this was something to do with our app but considering this happens on a fresh ionic install, it must be plugin specific

**Comment by victorsosa** [comment]
ok, which env are you using? OSX, IOS, xcode...

**Comment by onfire** [comment]
@victorsosa 

OSX 10.9.5 
Xcode 6.2
IOS emulator running IOS 8.2 (from Xcode 6.2)

**Comment by victorsosa** [comment]
Please try to use `ionic plugin add cordova-plugin-google-analytics --save`

it seems that people are getting issues because of the missing 'save' parameter in the install
