### ISSUE TITLE
Optimization: have initialisation arg for sending interval

### ISSUE THREAD

**Issue by tacitus** [danwilson/google-analytics-plugin#30]
Would be handy to be able to control the sending of data interval.

**Comment by cemerson** [comment]
Pardon my rookie question here (and if it's a thread highjack?) but ... without us manipulating the "sending interval" ourselves, how does this plugin work? Are all events/screens that are tracked in between intervals lost? Or are they all sent (in bulk) at each interval?

**Comment by victorsosa** [comment]
@cemerson  they all sent (in bulk) at each interval

**Comment by victorsosa** [comment]
release 1.7.0
