### ISSUE TITLE
AnalyticsReceiver is not registered or is disabled

### ISSUE THREAD

**Issue by stevecarlton** [danwilson/google-analytics-plugin#300]
Thanks for the plugin and the hard work. The plugin is working very well for me for iOS but Android is not reporting. After looking at the device logs I am seeing:

```
Google Analytics 7.8.95 is starting up. To enable debug logging on a device run:
09-22 22:45:01.236   350   350 W GAv4    : AnalyticsReceiver is not registered or is disabled. Register the receiver for reliable dispatching on non-Google Play devices. See http://goo.gl/8Rd3yj for instructions.

09-22 22:45:01.246   350   350 W GAv4    : CampaignTrackingReceiver is not registered, not exported or is disabled. Installation campaign tracking is not possible. See http://goo.gl/8Rd3yj for instructions.

09-22 22:45:01.261   350   369 W GAv4    : AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.
```

```
<receiver android:enabled="true" android:name="com.google.android.gms.analytics.AnalyticsReceiver">
      <intent-filter>
        <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH"/>
      </intent-filter>
    </receiver>
    <receiver android:enabled="true" android:exported="true" android:name="com.google.android.gms.analytics.CampaignTrackingReceiver">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
      </intent-filter>
    </receiver>
    <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.analytics.AnalyticsService"/>
    <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.analytics.CampaignTrackingService"/>
```

Of course I checked the AndroidManifest.xml and see the permissions mentioned in #150 
I am not seeing anything in the JS console even with debug mode enabled.
Running Cordova Android 5.2.2, plugin version 1.6.0

Any ideas on troubleshooting? Thanks in advance.

**Comment by victorsosa** [comment]
please double check you ./cordova/build/platforms/android/AndroidManifest.xml file to see if it was well generated

**Comment by stevecarlton** [comment]
@victorsosa I mentioned this in my post. The AndroidManifest.xml was pasted in and seems properly formatted.

**Comment by victorsosa** [comment]
check that you have installed the extras lib in the android simulator like: Google Analytics App Tracking SDK, Google Play Services, etc.

**Comment by victorsosa** [comment]
please check issue #274

**Comment by victorsosa** [comment]
Please try to use `cordova plugin add cordova-plugin-google-analytics --save` 

it seems that people are getting issues because of the missing 'save' parameter in the install
