### ISSUE TITLE
unclear syntax for Ionic/Angular

### ISSUE THREAD

**Issue by louisdoe** [danwilson/google-analytics-plugin#301]
Hi

I am developping a Ionic app. It's unclear which syntax I should use:
    `window.ga.trackView(...`
or
   ` $cordovaGoogleAnalytics.trackView(...`
?
Because [this page](http://ngcordova.com/docs/plugins/googleAnalytics/) redirects to this githup repo.

It would be good to have a note about Ionic/Angular in the docs.

Thanks for your help.

**Comment by victorsosa** [comment]
If you are using normal javascript code you should use `window.ga.trackview(`
if you are using ngCordova which is angular code you should use `$cordovaGoogleAnalytics.trackView`

**Comment by louisdoe** [comment]
ok thanks Victor !
