### ISSUE TITLE
Http status -1

### ISSUE THREAD

**Issue by n24005** [danwilson/google-analytics-plugin#302]
I believe I have everything installed properly, but I am not getting analytics reported to google.

With .debugMode() I see in the XCode console widow that the GAIReachabilityChecker flags update: 0X040003.    I execute the success function from startTrackerWithId and I set up a trackView.

The log shows that the view is triggered as I get a "Saved Hit:"...

It then displays the GET: with all of the collect? parameters.

Then GAIBatchingDispatcher didSendHits:response:data:error with HTTP status -1, yet the messages indicate that the hit is "Successfully deleted" and "sent".

Yet nothing is showing up n my dashboard...

Removed the .debugMode() and ran it via TestFlight - still nothing reported.

Suggestions?

TIA!
Jeff

**Comment by victorsosa** [comment]
please check issue #274

**Comment by n24005** [comment]
Thanks - that did give me enough information so that I am now getting data.
