### ISSUE TITLE
plugin does not work if active IDFA

### ISSUE THREAD

**Issue by andreaj8** [danwilson/google-analytics-plugin#304]
I activated the IDFA parameter, and no longer work my analytics, and IDFA field is not recognized establishment of analytics. How is it possible ? my mistake implementation?

window.ga.setAllowIDFACollection(true); 

Versions:
iOS & Android
cordova-plugin-google-analytics 0.8.1 
Cordova : 6.3.1
Ionic : 1.7.14

**Comment by sebastianovide** [comment]
Did you try with the latest 1.6?

**Comment by victorsosa** [comment]
please check issue #309

**Comment by andreaj8** [comment]
yes i'm using cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin".

**Comment by andreaj8** [comment]
I never had problems until I turned on the IDFA. Since that time the traffic to analytics has been suspended and removing the IDFA now the geolocation of my device is incorrect.

**Comment by nicowenterodt** [comment]
mh, I recognize some missbehaviour as well. traffic by ios10 devices is no longer tracked accordingly. not sure if it's related with the IDFA setting though.. I'm still investigating.

**Comment by yosikal** [comment]
I'm having a similar issue: since I turned IDFA on I can't see the IOS version as secondary dimension, analytics shows most of the IOS version as not set. Any idea?

**Comment by victorsosa** [comment]
ested out in the last version 1.7.11 and it is working fine.
