### ISSUE TITLE
Not Working with Ionic 2 RC.0 (Android)

### ISSUE THREAD

**Issue by baltazaroliveira** [danwilson/google-analytics-plugin#305]
I finally upgraded my app to Ionic 2 RC0 and when i run the app on my Device i get a error in Google Analtycs (work on latest beta)

https://cdn-enterprise.discourse.org/ionicframework/uploads/default/optimized/3X/b/f/bfaa4013f47ac813153f3cae07fd716cfabc68c7_1_690x89.png

The plugin is installed

https://cdn-enterprise.discourse.org/ionicframework/uploads/default/original/3X/e/7/e75f614a743a9f59e7a782cf15355633c835b87e.png

Any solution?

**Comment by ihadeed** [comment]
@baltazaroliveira try updating ionic-native to the latest version, I just published a new release with lots of fixes for this plugin.

**Comment by baltazaroliveira** [comment]
Updated to latest Ionic Native 2.1.6. Same error with the change suggested!

```
constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.

      // splash screen
      //Splashscreen.hide();

      if (Splashscreen) {
        setTimeout(() => {
          Splashscreen.hide();
        }, 1000);
      }

      // status bar
      StatusBar.styleDefault();

      //let name = Device.device.uuid;

      // GA
      //GoogleAnalytics.debugMode();
      GoogleAnalytics.startTrackerWithId("UA-17772329-16");

    });
  } // construtor

```
Please help to resolve this issue!

**Comment by baltazaroliveira** [comment]
Any update?

**Comment by victorsosa** [comment]
@baltazaroliveira plase check the issue #291, there is an example there of how to use it with ionic2
