### ISSUE TITLE
allowIDFACollection seems not working 

### ISSUE THREAD

**Issue by sebastianovide** [danwilson/google-analytics-plugin#309]
having allowIDFACollection enabled I expect to see demographic. But google keep saying 
"Your Analytics tracking code does not include the necessary support for the Demographics and Interest reports. Learn more about the simple, one-line, one-time change to your tracking code to add this support."

any idea ?

**Comment by victorsosa** [comment]
yes, please check issue #276

You need to generated enough data before it could generate the report

**Comment by sebastianovide** [comment]
perfect. I'm closing this then. Thanks
