### ISSUE TITLE
Add methods to adjust dispatch period

### ISSUE THREAD

**Issue by TheStalwart** [danwilson/google-analytics-plugin#311]
Please add JS functions to wrap dispatch period adjustment. 
Lowering dispatch period is important for debugging to see stuff in Real-Time console and avoid guessing whether or not plugin is configured correctly.

Android API:
GoogleAnalytics.getInstance(this).setLocalDispatchPeriod(30);
https://developers.google.com/analytics/devguides/collection/android/v4/dispatch

iOS API:
[GAI sharedInstance].dispatchInterval = 120;
https://developers.google.com/analytics/devguides/collection/ios/v3/dispatch

**Comment by victorsosa** [comment]
release 1.7.0
