### ISSUE TITLE
NSInvalidArgumentException in iOS 10 using Xcode 8

### ISSUE THREAD

**Issue by jasonatt** [danwilson/google-analytics-plugin#312]
Hi, on App Launch I am getting the below error within iOS only. For reference I am using Xcode 8 on MacOS Sierra and Compiling for iOS10 on iPhone 5s. Cordova version: ios 4.2.1

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringByTrimmingCharactersInSet:]: unrecognized selector sent to instance 0x1b214bef8'
*** First throw call stack:
(0x18d48c1c0 0x18bec455c 0x18d493278 0x18d490278 0x18d38a59c 0x1000e5b78 0x10008ece8 0x1005a125c 0x1005a121c 0x1005af2d4 0x1005b0e6c 0x1005b0bb8 0x18c51d2c8 0x18c51cdb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Xcode points to this file.

```
UniversalAnalyticsPlugin.m > -startTackerWithId
Line 26
[[GAI sharedInstance] trackerWithTrackingId:accountId];
```

**Comment by TheStalwart** [comment]
I can confirm this issue. Version 1.7.0 of plugin crashes the app.

Version i used successfully:
    <plugin name="cordova-plugin-google-analytics" spec="https://github.com/danwilson/google-analytics-plugin.git#739d7452943ec2d2a3152dc2cce65a48d538f9b4" />

**Comment by TheStalwart** [comment]
UniversalAnalyticsPlugin.m:26

When plugin is initialized omitting dispatchInterval parameter, code is trying to convert NSNull to integer

**Comment by TheStalwart** [comment]
(lldb) po command.arguments
<__NSArrayM 0x17405f320>(
UA-XXXXX-X,
<null>
)

**Comment by victorsosa** [comment]
@TheStalwart thanks, for the fix; but that issue is not the same reported in #312 and #316, any way the pr is welcome.

**Comment by TheStalwart** [comment]
#312 original description stated crash on the same line as my crash. Difference in method called could be related to different version of cordova-ios engine or deployment target, as these kinds of crashes often trace to internals of Core Frameworks.

I'm pretty sure my PR will fix both #312 and #316.

**Comment by victorsosa** [comment]
fix applied in v1.7.1, please check

**Comment by victorsosa** [comment]
@jasonatt please post the code you use to call this api; it should be contains something like:

`window.ga.startTrackerWithId('UA-XXXX-YY');`

**Comment by TheStalwart** [comment]
I was going to ask the same. Sorry @victorsosa, you were right about my PR addressing different issue. I haven't noticed dispatchInterval code landed in master days after this issue was reported

**Comment by victorsosa** [comment]
@TheStalwart No problema :+1:

**Comment by victorsosa** [comment]
people please check the issue #335; this could be related too

**Comment by victorsosa** [comment]
This should be working fine by now, the dispatchInterval parameter was missing in the library line in  ngCordova now should be working fine.
