### ISSUE TITLE
Inconsistent signature usage of addCustomDimension

### ISSUE THREAD

**Issue by mlegenhausen** [danwilson/google-analytics-plugin#314]
The usage of the `key` parameter of `addCustomDimension` differs between the platforms, the README and the typescript definition.

In the README, the android and wp8 platform it is defined as number where it in iOS and the typescript definition it is defined as string.

See following lines:
- https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m#L158
- https://github.com/danwilson/google-analytics-plugin/blob/master/typescript/analytics.d.ts#L32
- https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L85
- https://github.com/danwilson/google-analytics-plugin/blob/master/wp8/UniversalAnalytics.cs#L200

I think the right type for this parameter should be number? If you could confirm I would make sure it is consistent over all platforms.

**Comment by victorsosa** [comment]
Yes, you are right it is a number.

Any PR  is welcome.

**Comment by martyzz1** [comment]
https://github.com/danwilson/google-analytics-plugin/pull/325

**Comment by victorsosa** [comment]
@martyzz1 thanks

**Comment by mlegenhausen** [comment]
@martyzz1 thanks for helping out.

**Comment by martyzz1** [comment]
no worries... I wish I had more experience with Objective C and Java, as I'd love to get the Enhanced Ecommerce working...
