### ISSUE TITLE
App crashes on iOS 10

### ISSUE THREAD

**Issue by AndreasReitberger** [danwilson/google-analytics-plugin#316]
Hi,
I'm using your Plugin in my Android / iOS Games. While it works fine on android, the game crashes on start if the Google Analytics plugin is installed.

If I remove it, the game runs fine. It also worked fine before I updated to iOS10.

Thank you for your great service and plugin!

Regards
Andy

**Comment by victorsosa** [comment]
Do you any log about the crash, that  you can provide? and it is crashing on IOS 10 or android?

**Comment by AndreasReitberger** [comment]
Hi,
It'a on iOS only. Android is working fine. 
Maybe it's related to this bug
https://github.com/danwilson/google-analytics-plugin/issues/312

The app crashes without any error.

Regards 
Andy

**Comment by victorsosa** [comment]
please post some example code of how are you using the API.

**Comment by padupuy** [comment]
I reproduce the crash too on iOS 9.1, I use the last version of the plugin 1.7.2

`*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x15cdce7f0> was mutated while being enumerated.'
*** First throw call stack:
(0x1817d6db0 0x180e3bf80 0x1817d67e4 0x10005144c 0x10005435c 0x1005f1a7c 0x1005f1a3c 0x100600c9c 0x100600364 0x181439470 0x181439020)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

<img width="1392" alt="capture d ecran 2016-11-28 a 12 46 10" src="https://cloud.githubusercontent.com/assets/715255/20675594/2cea2dfe-b58d-11e6-91e2-b609fac94da7.png">

**Comment by martyzz1** [comment]
This might need a js change to fix... I'm looking into this.

**Comment by martyzz1** [comment]
can you post the JS code you use to start your tracker and any code you use to add customdimensions.

**Comment by victorsosa** [comment]
@martyzz1 thanks

**Comment by martyzz1** [comment]
My speculation is simply that the addCustomDimension is being called with a string not a number. This is being passed through to cordova.exec and then generating the error.
(I'm no expert on the cordova.exec side of things)

I've got a few commits on my fork which should raise a js error if this is the case. 
Can anybody test and confirm this is the cause of the above issue

https://github.com/martyzz1/google-analytics-plugin

**Comment by victorsosa** [comment]
@martyzz1 addCustomDimension() and addCustomDimensionsToTracker() works toghether.
Please rollback the change on the line:

`for (NSNumber *key in _customDimensions) {` to `for (NSString*key in _customDimensions) {`

on the method addCustomDimensionsToTracker(); that need to be NSString.

**Comment by martyzz1** [comment]
Looking at the code... as I understand it  - but I could be wrong - addCustomDimension should be invoked with (int, string)

The java code is explicit
else if (ADD_DIMENSION.equals(action)) {
            Integer key = args.getInt(0);
            String value = args.getString(1);
            this.addCustomDimension(key, value, callbackContext);
            return true;
So I assume the ios code would be the same. 

Which makes me think this should be the change

```
159 - (void) addCustomDimension: (CDVInvokedUrlCommand*)command
160 {
161     CDVPluginResult* pluginResult = nil;
162     NSString* key = [command.arguments objectAtIndex:0];
163     NSString* value = [command.arguments objectAtIndex:1];

```
Should become

NSSNumber* key = [command.arguments objectAtIndex:0];

**Comment by victorsosa** [comment]
You right on that point, but on IOS side there is a dictionary `_customDimensions` that's why the NSString in the key; which change everything.

**Comment by martyzz1** [comment]
but wouldn't this then leave a mismatch?  (I'm not an objectiveC coder, so really just picking through the code).

My concern is here:-
```

  [tracker set:[GAIFields customDimensionForIndex:[key intValue]]
        value:value];
```

```
- (void) addCustomDimensionsToTracker: (id<GAITracker>)tracker
{
    if (_customDimensions) {
      for (NSNumber *key in _customDimensions) {
        NSString *value = [_customDimensions objectForKey:key];

        /* NSLog(@"Setting tracker dimension slot %@: <%@>", key, value); */
        [tracker set:[GAIFields customDimensionForIndex:[key intValue]]
        value:value];
      }
    }
}

```
https://developers.google.com/analytics/devguides/collection/ios/v3/customdimsmets

**Comment by victorsosa** [comment]
`key intValue` convert the string into Integer; don't worry that was working fine

**Comment by martyzz1** [comment]
Check this out... I think it aligned pretty much with what you had. But uses a NumberFormatter to convert back to NSNumber..
https://github.com/danwilson/google-analytics-plugin/pull/334/files

**Comment by padupuy** [comment]
Hello @victorsosa @martyzz1 @AndreasReitberger 
I confirm the plugin works fine with Android, the crash is only with iOS.
Here is how I use the plugin

First, when device is ready, I init the tracker : 
`window.ga.startTrackerWithId('UA-XXXXXXXX-X', 30);`
`window.ga.setAllowIDFACollection(true);`

Then on each page, I track : 
```
export function trackView(title, params) {
  if (window.ga && window.ga.trackView) {
    window.ga.setUserId('1234567890');
      params.forEach(param => {
        window.ga.addCustomDimension(param.key, param.value, 
         () => {
         }, 
         () => {
         }
       );
      });
    window.ga.trackView(title);
  }
  else {
    console.log('Analytics utils - trackView', title, params);
  }
}
```

Where `param.key` in an integer and `param.value` a string

Thanks for your help

**Comment by martyzz1** [comment]
can you try it with my fork to see if that fixes the issue?

**Comment by padupuy** [comment]
@martyzz1 No more crash with your PR, it seems to work 👍

**Comment by martyzz1** [comment]
Great I'll raise a PR @victor

**Comment by victorsosa** [comment]
Thanks, great work!!!

**Comment by padupuy** [comment]
@martyzz1 @victorsosa 
Oups ... I spoke a little bit too hastily

<img width="1392" alt="capture d ecran 2016-11-30 a 14 35 54" src="https://cloud.githubusercontent.com/assets/715255/20754414/12bfa20e-b70b-11e6-9c4f-27d917bab408.png">

**Comment by martyzz1** [comment]
Can you show me what you are setting for the custom variable in your
JavaScript?

**Comment by padupuy** [comment]
I set those variables 
```
[
  {
    "key": 1,
    "value": "pf16"
  },
  {
    "key": 2,
    "value": "connexion"
  },
  {
    "key": 3,
    "value": "demo"
  },
  {
    "key": 4,
    "value": "fr-fr"
  },
  {
    "key": 5,
    "value": "ios"
  },
  {
    "key": 6,
    "value": ""
  },
  {
    "key": 7,
    "value": "n"
  },
  {
    "key": 8,
    "value": ""
  },
  {
    "key": 9,
    "value": ""
  },
  {
    "key": 10,
    "value": ""
  },
  {
    "key": 11,
    "value": ""
  },
  {
    "key": 12,
    "value": ""
  }
]
```

**Comment by martyzz1** [comment]
Thanks. Are the keys definitely being passed as integer in the JavaScript?
I added a console.log in the set CustomDimension function to warn if not an
integer.

**Comment by martyzz1** [comment]
I've pushed a possible fix on my branch. if you want to try it.

**Comment by padupuy** [comment]
I test asap and I'll let you know

**Comment by padupuy** [comment]
@martyzz1 it seems great ! I haven't notice any crash.
Could you add your last commits to your PR (https://github.com/danwilson/google-analytics-plugin/pull/334) ?

**Comment by martyzz1** [comment]
yeah they're in there... should be good to go

**Comment by victorsosa** [comment]
so addCustomDimension is working fine? just confirming

**Comment by padupuy** [comment]
@victorsosa I confirm you can merge the PR https://github.com/danwilson/google-analytics-plugin/pull/334

**Comment by victorsosa** [comment]
OK
