### ISSUE TITLE
Remove setUserId / Start new Session

### ISSUE THREAD

**Issue by clearminds** [danwilson/google-analytics-plugin#318]
I read #226 and I got the same issue, I am working on a app and can't figure out how to destroy the session and create a new one at logout.

Will running startTrackerWithId twice destroy the old session?

PS. Any place to donate?

**Comment by victorsosa** [comment]
you can use `window.ga.trackView('Screen Title', '', true)` to create a new session. You don't have to destroy because the api will remove it.

**Comment by clearminds** [comment]
Talked to an old colleague and according to him this did not clear the UserId

**Comment by clearminds** [comment]
Seems to work in the latest version - this was tried latest in an old version. Thanks!
