### ISSUE TITLE
Rename 'analytics' to 'ga'?

### ISSUE THREAD

**Issue by dpolivy** [danwilson/google-analytics-plugin#32]
I've been using [analytics.js](https://github.com/segmentio/analytics.js) as a master wrapper for my analytics needs, and that uses `window.analytics` as its mount point. I'm working on adding an integration so I can use analytics.js with this Google Analytics Plugin as an integration for my Cordova app.

I realize this is a bit of a long shot, especially since it's a breaking change, but I'd ask you to consider using a different global for this plugin, perhaps `ga` to be more consistent with how Google Analytics is exposed in a website?

Just a suggestion; thanks so much for providing this to begin with!

**Comment by dbaseman** [comment]
@dpolivy were you working on a Windows Phone integration?

**Comment by dpolivy** [comment]
@dbaseman Yes, here is the [repo](https://github.com/dpolivy/google-analytics-plugin/tree/wp8). It's a little behind, and it's still on my list to bring it current and send a PR. I'll see what I can do to move that higher on the todo list.

**Comment by dbaseman** [comment]
@dpolivy very nice, thanks!  This will save me some work.  Please let me know if there's anything I can help with.
