### ISSUE TITLE
Retreive UTM tracking details

### ISSUE THREAD

**Issue by snowbreeze** [danwilson/google-analytics-plugin#320]
Hey!

@danwilson  @victorsosa amazing work on this plugin!

I had a small request, I need to access the campaign name inside my js code, so that i can show the users appropriate content based on it. 

Is there anyway I could do something like window.ga.getCampaignName() 

Keep up the great work!

**Comment by victorsosa** [comment]
No, there no api for do that, but you app is the one sending the UTM parameter, just save the parameter you want in a variable and used it later.

**Comment by snowbreeze** [comment]
Yes, In the background somewhere the app is picking up the utm details and forwarding it to analytics, as i can see the details in my analytics dashboard. Question is how do I retrieve this information, I couldnt not find anything in this plugins code either

**Comment by snowbreeze** [comment]
@victorsosa 
```
just save the parameter you want in a variable and used it later.
```
I am going mad on how to do this, Can you please suggest a sample code :)

**Comment by victorsosa** [comment]
It is just a variable added to the string for the campaing url.
```
var my-campaign = 'saveme';
window.ga.trackView('Screen Title', 'my-scheme://content/1111?utm_source=google&utm_campaign=' + my-campaign)
```

my-campaing can be use anywhere.

**Comment by snowbreeze** [comment]
No you are getting me wrong. 
I want to retrieve the name of the campaign, that launched the app.

Suppose, I have 2 campaigns in adwords A and B.

somewhere in my index.html file I want to know

```
var campaign = //get the campaign name
//and then do something based on that
if(campaign == 'A') //do this
else //that

```

**Comment by victorsosa** [comment]
Check the documentation about google analitycs api:
https://developers.google.com/analytics/devguides/collection/android/v4/campaigns

I can't help you with that.

**Comment by ourarash** [comment]
@snowbreeze Did you find a solution for this?

**Comment by snowbreeze** [comment]
@ourarash Nothing yet, did you find anything? @victorsosa Please help us, we just need the UTM details to be accessible from javascript. Maybe store it somewhere in app preferences or local storage.

Thanks

**Comment by victorsosa** [comment]
Hi,

We can use this concept to get any variable from the plugin:
`plugin.get(plugin.Fields.CLIENT_ID, ...)`

please check issue #208

**Comment by snowbreeze** [comment]
possible

**Comment by snowbreeze** [comment]
What I understand is in the background, the analytics sdk can track where the install came from (UTM data) of both ios and android, and it passes it to the google analytics. We need a way to extract that information out to our javascript layer via the plugin.

**Comment by victorsosa** [comment]
PR #389 sent

**Comment by victorsosa** [comment]
Implemented in ver1.7.6

**Comment by snowbreeze** [comment]
Superb!!! @victorsosa 
Can you also give us a small sample on how to use this and get the install referr, also will this work for browser?

**Comment by victorsosa** [comment]
I implemented for browser but I don't know if it works; let me know.

Get the info from the readme.

**Comment by snowbreeze** [comment]
Ok I will test and update
