### ISSUE TITLE
Browser platform issue

### ISSUE THREAD

**Issue by snowbreeze** [danwilson/google-analytics-plugin#321]
Error
```
exec proxy not found for :: UniversalAnalytics :: startTrackerWithId
```

When I do this in console
```
window.ga
```
I get
```
UniversalAnalyticsPlugin {}
```

Installed platforms:
  android 5.2.2
  browser 4.1.0
  ios 4.2.1

cordova-plugin-google-analytics 1.6.0 "Google Universal Analytics Plugin"

It works fine in ios and android, but doesnt work in browser.

**Comment by victorsosa** [comment]
Browser platform is not implement yet, please check #313

**Comment by snowbreeze** [comment]
@victorsosa great! So this is coming soon, any eta?

**Comment by victorsosa** [comment]
by this month.

**Comment by snowbreeze** [comment]
Great.. Will be waiting..
