### ISSUE TITLE
trackMetric with a String Value fails in IOS

### ISSUE THREAD

**Issue by jkirsch** [danwilson/google-analytics-plugin#324]
I'm using the following metric tracking

This works for android, but not on IOS

```javascript
window.ga.trackMetric(1, "Userpreference");
```

On android, it expects an int and a String

```java
this.trackMetric(args.getInt(0), length > 1 ? args.getString(1) : "", callbackContext);
```
https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L82

on IOS

it takes a number and another number casted to String

```swift
NSNumber *value = nil;
if ([command.arguments count] > 0)
	key = [command.arguments objectAtIndex:0];
if ([command.arguments count] > 1)
	value = [command.arguments objectAtIndex:1];
id<GAITracker> tracker = [[GAI sharedInstance] defaultTracker];
[tracker set:[GAIFields customMetricForIndex:[key intValue]] value:[value stringValue]];
```

https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m#L188

This crashes the app with

[NSCFString stringValue]: unrecognized selector sent to instance

Presumably because the string is already a string and cannot be transformed.

Is that an intended behavior?

**Comment by victorsosa** [comment]
No, value should be a String.

**Comment by jkirsch** [comment]
Thanks for responding so quickly

I guess part of the confusion was by myself.
I used the wrong API call .. what I am doing is setting a custom dimension .. so I was calling the wrong API - with `addCustomDimension` it works without errors.

**Comment by victorsosa** [comment]
Either way, I think you found an issue.

**Comment by martyzz1** [comment]
I'm seeing a simillar issue, addCustomDimension()
Android expect a number. iOS (from what I can see) expects an NSString. should it be NSNumber
 
```
else if (ADD_DIMENSION.equals(action)) {
            Integer key = args.getInt(0);
            String value = args.getString(1);
            this.addCustomDimension(key, value, callbackContext);
            return true;

```
```
(void) addCustomDimensionsToTracker: (id<GAITracker>)tracker
{
    if (_customDimensions) {
      for (NSString *key in _customDimensions) {
        NSString *value = [_customDimensions objectForKey:key];

        /* NSLog(@"Setting tracker dimension slot %@: <%@>", key, value); */
        [tracker set:[GAIFields customDimensionForIndex:[key intValue]]
        value:value];
      }
    }
}


```

**Comment by victorsosa** [comment]
@martyzz1 Yes, you are right.

**Comment by martyzz1** [comment]
I've made a patch on a fork...

**Comment by martyzz1** [comment]
But still testing it... will raise a PR... (but I'm not a ObjectiveC coder, so just testing it now)

**Comment by martyzz1** [comment]
Here ya go., https://github.com/danwilson/google-analytics-plugin/pull/325

**Comment by victorsosa** [comment]
@martyzz1 thanks for the PR
