### ISSUE TITLE
WP8 deprecated now. What about windows?

### ISSUE THREAD

**Issue by arindamINT** [danwilson/google-analytics-plugin#329]
When it will work windows? Are you working on this part?

**Comment by victorsosa** [comment]
Only windows phone 8 was implemented; the windows platform need to be implemented; Any PR is welcome

check PR #89 for more info.

**Comment by arindamm** [comment]
It is not working on windows 8.1. plz do something.

**Comment by tanderson114** [comment]
Any updates for windows 8.1?

**Comment by holospeed** [comment]
Its working fine on windows Phone 8.1. Dont forget adding GoogleAnalytics SDK to your project.

**Comment by victorsosa** [comment]
@holospeed thanks

**Comment by victorsosa** [comment]
we have a PR #434 :tada: :tada:
