### ISSUE TITLE
Page not tracked

### ISSUE THREAD

**Issue by izhekov** [danwilson/google-analytics-plugin#332]
We have both a mobile app and a mobile site, both sharing almost the same code. The app is built using PhoneGap. Now we try to track the usage and the actual view/page hit using the following code when the app state changes:

window.ga.trackView(state.name, trackUrl, true);

This is actually causing google analytics to be hit, and I can see real-time data under "Locations" menu of Google Analytics. Unfortunately those hits have incomplete data as neither the page title, nor the page url are registered under the real-time "Content" menu. I'm not sure what I'm missing. 

Here's the logcat output:

I/GAv4    ( 3055): Google Analytics 8.4.87 is starting up. To enable debug logging on a device run:
I/GAv4    ( 3055):   adb shell setprop log.tag.GAv4 DEBUG
I/GAv4    ( 3055):   adb logcat -s GAv4
D/GAv4    ( 3055): setLocalDispatchPeriod (sec): 10
I/GAv4    ( 3055): Logger is deprecated. To enable debug logging, please run:
I/GAv4    ( 3055): adb shell setprop log.tag.GAv4 DEBUG
W/GAv4    ( 3055): Error getting advertiser id: com.google.android.gms.common.GooglePlayServicesNotAvailableException
D/GAv4    ( 3055): Hit delivery requested: ht=1480342152453, _s=30, _v=ma8.4.87, a=1204513444, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2826, cd=init, cd8=Init test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Hit saved to database. db-id, hit: 31, ht=1480342152453, _s=30, _v=ma8.4.87, a=1204513444, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2826, cd=init, cd8=Init test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Dispatching local hits. Elapsed time since last dispatch (ms): 671283
D/GAv4    ( 3055): POST compressed size, ratio %, url: 202, 88, https://ssl.google-analytics.com/batch
D/GAv4    ( 3055): POST status: 200
D/GAv4    ( 3055): Hit delivery requested: ht=1480342161542, _s=31, _v=ma8.4.87, a=1204513445, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.company, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Hit saved to database. db-id, hit: 32, ht=1480342161542, _s=31, _v=ma8.4.87, a=1204513445, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.company, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Dispatching local hits. Elapsed time since last dispatch (ms): 10002
D/GAv4    ( 3055): POST compressed size, ratio %, url: 261, 81, https://ssl.google-analytics.com/batch
D/GAv4    ( 3055): POST status: 200
D/GAv4    ( 3055): Hit delivery requested: ht=1480342170993, _s=32, _v=ma8.4.87, a=1204513446, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.industry, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Hit saved to database. db-id, hit: 33, ht=1480342170993, _s=32, _v=ma8.4.87, a=1204513446, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.industry, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Dispatching local hits. Elapsed time since last dispatch (ms): 10044
D/GAv4    ( 3055): POST compressed size, ratio %, url: 262, 81, https://ssl.google-analytics.com/batch
D/GAv4    ( 3055): POST status: 200
D/GAv4    ( 3055): Hit delivery requested: ht=1480342850719, _s=33, _v=ma8.4.87, a=1204513447, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.company, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Hit saved to database. db-id, hit: 34, ht=1480342850719, _s=33, _v=ma8.4.87, a=1204513447, aclid=, aid=com.emis.emispro, an=EMIS Mobile, anid=, ate=0, av=1.86.2826, cc=, cd=root.protected.company, cd8=Dimension Test, ci=, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, ck=, cm=, cn=, cs=app, dclid=, gclid=, gmob_t=, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3055): Dispatching local hits. Elapsed time since last dispatch (ms): 677125
D/GAv4    ( 3055): POST compressed size, ratio %, url: 261, 81, https://ssl.google-analytics.com/batch
D/GAv4    ( 3055): POST status: 200

**Comment by victorsosa** [comment]
Please check that you need to have GooglePlayServices:
`com.google.android.gms.common.GooglePlayServicesNotAvailableException`

**Comment by izhekov** [comment]
Thank you. That makes sense. I don't know why I missed it. I'm going to check it out and see if the problem is solved. My apologies for reporting it as an issue.

**Comment by izhekov** [comment]
My apologies about the inconvenience, but I'm still stuck with this issue. After installing Google Play Service the issue remains. I'll appreciate it if you can help me to solve it.

I attached screenshots from GA, which acts quite strange. The hit is registered, but there's nothing under "Content".

![locations](https://cloud.githubusercontent.com/assets/8613280/20704125/de5920a6-b626-11e6-98b0-48e2a702e382.PNG)
![content](https://cloud.githubusercontent.com/assets/8613280/20704126/de598c26-b626-11e6-80ad-d58fb416409c.PNG)

Here's the log:
I/GAv4    ( 3599): Google Analytics 10.0.84 is starting up. To enable debug logging on a device run:
I/GAv4    ( 3599):   adb shell setprop log.tag.GAv4 DEBUG
I/GAv4    ( 3599):   adb logcat -s GAv4
D/GAv4    ( 3599): setLocalDispatchPeriod (sec): 10
I/GAv4    ( 3599): Logger is deprecated. To enable debug logging, please run:
I/GAv4    ( 3599): adb shell setprop log.tag.GAv4 DEBUG
D/GAv4    ( 3599): Hit delivery requested: ht=1480355137801, _s=48, _v=ma10.0.84, a=1745431890, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2835, cd=init, cd8=Init test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3599): Hit saved to database. db-id, hit: 49, ht=1480355137801, _s=48, _v=ma10.0.84, a=1745431890, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2835, cd=init, cd8=Init test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3599): Dispatching local hits. Elapsed time since last dispatch (ms): 1021683
D/GAv4    ( 3599): POST compressed size, ratio %, url: 202, 88, https://ssl.google-analytics.com/batch
D/GAv4    ( 3599): POST status: 200
D/GAv4    ( 3599): Hit delivery requested: ht=1480355157049, _s=49, _v=ma10.0.84, a=1745431891, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2835, cd=root.protected.company, cd8=Dimension Test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, cs=app, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3599): Hit saved to database. db-id, hit: 50, ht=1480355157049, _s=49, _v=ma10.0.84, a=1745431891, aid=com.emis.emispro, an=EMIS Mobile, ate=0, av=1.86.2835, cd=root.protected.company, cd8=Dimension Test, cid=454e2928-1f4f-4323-b1fe-002d3a74edb7, cs=app, sc=start, sr=800x1184, t=screenview, tid=UA-1830606-6, ul=en-us, v=1
D/GAv4    ( 3599): Dispatching local hits. Elapsed time since last dispatch (ms): 18669
D/GAv4    ( 3599): POST compressed size, ratio %, url: 230, 85, https://ssl.google-analytics.com/batch
D/GAv4    ( 3599): POST status: 200

**Comment by martyzz1** [comment]
You might need to setup a Mobile View in analytics? Your screenshot looks
like a Web View...

**Comment by martymiller** [comment]
Did you ever resolve this issue?  I'm having the same problem.  I find that whenever I see "Hit saved to database", the event doesn't get sent.
