### ISSUE TITLE
Upgraded from 1.6.0 to 1.7.2 and it doesn't work anymore

### ISSUE THREAD

**Issue by rodrigograca31** [danwilson/google-analytics-plugin#333]
Hi!

I was using `1.6.0` and everything worked fine, some days ago I updated to `1.7.2` and stopped tracking all users...

If I removed it and add `1.6.0` again it works perfectly...

I searched a bit to see if anyone was having the same problem or if there was any API changes, I found that you changed from `window.analytics` to `window.ga` I'm now using `window.ga` and it didn't solve the problem....

Any ideas?

(cordova-android@6.1.0)
```
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.2
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS: Distributor ID:     LinuxMint Description:  Linux Mint 17.3 Rosa 
Node Version: v7.0.0
```

Thanks for the plugin and help.

**Comment by victorsosa** [comment]
IOS or Android?

**Comment by rodrigograca31** [comment]
Android.
(left my system specs and didn't mentioned that.... lol)

**Comment by FabioWidmer** [comment]
Same for me. Upgraded from 1.7.1 to 1.7.2 and on all Android devices its not working.

**Comment by rodrigograca31** [comment]
I originally upgraded to `1.7.1` and didn't worked and I tough "let's update to `1.7.2` and fix the problem" but it didn't work....

**Comment by biesbjerg** [comment]
Can confirm 1.6.0 is the latest version that is working for me as well.

**Comment by rodrigograca31** [comment]
More info: There's not error on the console....

**Comment by Sogapp** [comment]
Issue confirmed for me too (Android only)

**Comment by EralpB** [comment]
Confirmed with Android, iOS is fine. I'm reverting back to 1.6.0 as for this time.

**Comment by jafaripur** [comment]
Same for me, Not work in Android with 1.7.2 version and no error show or anything!!

**Comment by malwatte** [comment]
Facing the same problem.
Any updates?

**Comment by uenitest** [comment]
I've just tried version 1.7.4 and I face the same problem. I've tried using :

window.analytics.trackEvent(category, name);
window.ga.trackEvent(category, name);

but no tracking, no error, no network activity... :/

**Comment by rodrigograca31** [comment]
My code:
```javascript
if (window.ga !== undefined) {
    window.ga.startTrackerWithId('UA-XXX-X');
    window.ga.trackView('XXX');
}
```
(No, I don't use XXX as my actual code...)

**Comment by martyzz1** [comment]
This works for me...
```

if(window.ga) {
     console.log('Starting Tracker');
     window.ga.startTrackerWithId(window.ga_property_code, 30, function(msg) {
     console.log('Tracker start success', msg)
     //window.ga.debugMode()
     window.ga.setAllowIDFACollection(true);
     window.ga.enableUncaughtExceptionReporting(false, function(msg) {}, function(msg) {
          console.log('error', msg)})
          window.ga.addCustomDimension(2, 'new or logged out'
      }, function(msg){
          console.log('Tracker Start error', msg)
          cordova.getAppVersion(function(version) {
              window.appVersion = version;
          });
 });


```

**Comment by vrfurl** [comment]
Setting it up like like @martyzz1  suggested made it work for me as well.

**Comment by rodrigograca31** [comment]
@vrfurl what exactly makes it work?

The starting parameter? `window.ga.startTrackerWithId(window.ga_property_code, 30, function()`
Calling that other function? `window.ga.setAllowIDFACollection(true);`

Or what?

**Comment by vrfurl** [comment]
@rodrigograca31 To be honest I didn't test it or look into the source code enough to know what exactly makes it work but...  When I called it before like this: window.ga.startTrackerWithId(window.ga_property_code); or like this : window.ga.startTrackerWithId(window.ga_property_code, 30);

It didn't work for whatever reason.

But calling it just like @martyzz1 described with the success function callback and making sure to only call window.ga.setAllowIDFACollection(true); inside the success callback function is what made it finally start working and start sending data to GA for all trackView calls etc....

Hope that helps.

**Comment by mnenchev** [comment]
@martyzz1 that's really badly formatted code with errors :)

**Comment by martyzz1** [comment]
try now. was written in a hurry because I got fed up of answering the same question about it not working over and over....

**Comment by mnenchev** [comment]
@martyzz1 what should i try?

**Comment by victorsosa** [comment]
This seems to be a development issue no related to the api.

**Comment by rodrigograca31** [comment]
@victorsosa Has this issue been solve? can we use `1.7.2` without problems? (without changing code)
