### ISSUE TITLE
Short Sessions

### ISSUE THREAD

**Issue by linusanderas** [danwilson/google-analytics-plugin#339]
In Analytics the sessions are very short, from 0 to max 15 seconds. 

Right now I have just tested Android. Will try iOS later today but do anyone has a thought on what it is that can be wrong?

**Comment by victorsosa** [comment]
I haven't check the sessions time, yet

**Comment by victorsosa** [comment]
I think I found you issue, please check the docs https://support.google.com/analytics/answer/2795871?hl=en

that seems to be the issue in you case.  By default, sessions end after 30 minutes of inactivity and campaigns end after six months
