### ISSUE TITLE
Build error on 1.6.0

### ISSUE THREAD

**Issue by Baadier-Sydow** [danwilson/google-analytics-plugin#340]
@reedrichards and @jigsaxis.

I downgraded to 1.6.0 and still not able to build Google Analytics.

I get the following error:

    * What went wrong:
    Execution failed for task ':processDebugGoogleServices'.
    > Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

Nothing that I've found in Google works. I was on the latest version but downgraded to 1.6.0 after reading https://forum.ionicframework.com/t/google-analytics-tracker-not-started/70101/34

Any ideas?

**Comment by victorsosa** [comment]
Yes, you have a conflict with another package that use a specific version of google-services plugin

**Comment by Baadier-Sydow** [comment]
hmm thats going to be tricky to handle.

What options do I have as I suspect the plugin causing the issue is https://github.com/fechanique/cordova-plugin-fcm
