### ISSUE TITLE
How to use plugin with typescript?

### ISSUE THREAD

**Issue by gyzerok** [danwilson/google-analytics-plugin#344]
Hello there!

Thank you for the plugin and for even having TypeScript definitions! Can you, please, tell me what I should do in order to make it work with the TypeScript? Can't find any mention in the documentation about it.

**Comment by victorsosa** [comment]
Hi, 
there is a ton of Documentation; you can start on youtube

https://www.youtube.com/watch?v=DBzalzR1cjo

**Comment by victorsosa** [comment]
also check the Ionic 2 tutorial thy have good docs.
