### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by robinleigh** [danwilson/google-analytics-plugin#348]
I cannot get this plug-in to register anything with GA.  I've followed the instructions provided, but wonder what I'm missing.  My project is a Cordova iOS app with Angular JS.  Does anyone have a sample app to share?

I'm new to both Cordova and Angular, so wonder if there is some instruction that is missing because it is obvious....

Thanks for any help.

**Comment by victorsosa** [comment]
If you are using ngCordova please check issue #335

**Comment by robinleigh** [comment]
The links seem to be outdated.  I can’t make it work from this information….

Thank you for your help,

**Comment by robinleigh** [comment]
Is there a sample app out there so that I can learn from it (since I am new to cordova)?   That's all I ask---to see something that works....

**Comment by victorsosa** [comment]
please check the readme doc, there is one example
