### ISSUE TITLE
Question: How do I see the network data sent from my device?

### ISSUE THREAD

**Issue by kukikiloke** [danwilson/google-analytics-plugin#349]
What protocol does the GA plugin use to send data to Google, and how do I see it when I have my Android/iOS device connected?

By connecting Android/iOS device to computer, I'm able to see network logs used by the app on the device, but I don't see anything that is related to GA.

Can anyone please help?

**Comment by TheStalwart** [comment]
I guess you're using Safari/Chrome Web Inspector, which only tracks network requests passing through JavaScriptCore/V8 engine. This GA plugin uses native libraries on iOS and Android that are executed out of WebKit/Chromium environment.

Use Charles or Fiddler to monitor all traffic irregardless of origin and implementation.
