### ISSUE TITLE
Tracking works on Android but not starting on ios

### ISSUE THREAD

**Issue by massengupta** [danwilson/google-analytics-plugin#350]
I have built an app using this plugin and I am unable to track ios. I have tried upto version 1.7.4. Please help.
window.ga.startTrackerWithId('UA-XXXXX-XX',30,
            function(response){
                     //alert(JSON.stringify(response)); <-- this is coming blank for ios
                     var fileName = location.href.split("/").slice(-1);
                     window.ga.trackView(fileName);
                     //alert(fileName); <-- showing correctly
                   },
                   function(error){
                     //alert(JSON.stringify(error));
                  });
        });

**Comment by victorsosa** [comment]
related to issue #335
