### ISSUE TITLE
startTrackerWithId() doesn't work in Android but works in iOS

### ISSUE THREAD

**Issue by NilangaVirajith** [danwilson/google-analytics-plugin#352]
I'm using google analytics in an ionic application. Tracking works fine in iOS but doesn't start tracking in Android. So I inserted few logs in the "UniversalAnalyticsPlugin.java" file inside the plugin and it looks like "execute" method doesn't run after the line,
 int dispatchPeriod = args.length() > 1 ? args.getInt(1) : 30; 

Any ideas on why this might have happened? 
Thanks in advance.

**Comment by victorsosa** [comment]
Yes, if you are using Ionic; guess you are using ngCordova, then please check issue #335 there is an issue releated to ngCordova because they don't have added the last parameters to the api.
