### ISSUE TITLE
Can I use this plugin in a build.phonegap app?

### ISSUE THREAD

**Issue by KevinHolloway** [danwilson/google-analytics-plugin#353]
If so what is the required line for my config.xml file please?

**Comment by victorsosa** [comment]
Yes, you can use it; no line required to be added. Please check the readme file

**Comment by LukeSkywalker92** [comment]
I don't get it. Do I have to follow the guide without the cli? I just added the package name to my config.xml and it works for android with PhoneGap build but not for iOS.
