### ISSUE TITLE
window.ga is undefined

### ISSUE THREAD

**Issue by shirkan** [danwilson/google-analytics-plugin#354]
Hi,
I've been trying to integrate the plugin for several days now with no success + I have read the relevant issues to my problem but couldn't make it to work.
I have successfully added the plugin but the problem is I get 'window.ga is undefined' on all platforms (web, ios, android) even though the first use of window.ga is way after deviceReady() has completed. In Xcode, for example, I can see libGoogleAnalyticsServices.a & GoogleMobileAds.framework, yet the plugin refuses to work on runtime.
Any suggestions how can I fix this problem?
Thanks.

**Comment by SidMehta** [comment]
Hi @shirkan ,
Were you able to sort out the issue? I am also facing the same issue.

**Comment by shirkan** [comment]
Sadly, no.
Also, haven't heard from the author @danwilson :(
Hopefully, it's only because of the holidays.
Let's wait patiently.

**Comment by martyzz1** [comment]
Guys, please post your code. It's impossible to assess your issue without
it. Also please specify which version of the plugin you are running.

**Comment by shirkan** [comment]
it's very straightforward:
* installed with 'cordova plugin add cordova-plugin-google-analytics' using CLI
* in code:

`if(( /(ipad|iphone|ipod|android)/i.test(navigator.userAgent) )) {
    document.addEventListener('deviceready', startGA, false);
}

function startGA() {
    window.ga.startTrackerWithId('XXXX');
    window.ga.setAppVersion('1.8')
    console.log('started tracking with id XXXX')
}`

* I also have some `window.ga.trackEvent` calls in some functions which are called upon request.

**Comment by martyzz1** [comment]
Does your console log get called? What environment are you using. Checking the useragent  string is an awful way to do anything.. use window.cordova.platformId...

**Comment by shirkan** [comment]
Running on both iOS & Android.
Here are some logs from Android (replacing my id with XXXX):
on startup:

```
I/GAv4    ( 4611): Google Analytics 9.8.77 is starting up. To enable debug logging on a device run:
I/GAv4    ( 4611):   adb shell setprop log.tag.GAv4 DEBUG
I/GAv4    ( 4611):   adb logcat -s GAv4
W/PluginManager( 4611): THREAD WARNING: exec() call to UniversalAnalytics.startTrackerWithId blocked the main thread for 21ms. Plugin should use CordovaInterface.getThreadPool().
W/CordovaPlugin( 4611): Attempted to send a second callback for ID: UniversalAnalytics721656226
W/CordovaPlugin( 4611): Result was: "Invalid action"
W/CordovaPlugin( 4611): Attempted to send a second callback for ID: UniversalAnalytics721656227
W/CordovaPlugin( 4611): Result was: "Invalid action"
I/chromium( 4611): [INFO:CONSOLE(9)] "started tracking with id XXXX", source: file:///android_asset/www/js/ga.js (9)
```

later on I get:
```I/chromium( 4611): [INFO:CONSOLE(353)] "Uncaught TypeError: Cannot read property 'trackEvent' of undefined", source: file:///android_asset/www/js/main.js (353)```

which is for this code:
```window.ga.trackEvent('EditContract', 'ContractDelete');```

**Comment by shirkan** [comment]
BTW, checking the useragent string is a legacy way I'm using, I'll check window.cordova.platformId - thanks!

**Comment by ilman** [comment]
@shirkan I am having the same problem before. I wrap the window.ga.startTrackerWithId() with timeout on device ready to fix it.

**Comment by shirkan** [comment]
@ilman doesn't sound like a good practice... How would GA will know how to track the correct id? Besides, the object is undefined, something is probably wrong with the package integration.

**Comment by ilman** [comment]
Ofcourse I added the ga trackId in the function above :)

**Comment by shirkan** [comment]
@ilman I'm a bit confused... Does it work for you with the workaround? If so, can you please post a code snippet of what you did to make it work?

**Comment by shirkan** [comment]
No solution yet?

**Comment by shirkan** [comment]
Don't know how, removed and added the plugin several times and it's working now.
