### ISSUE TITLE
Error with Cordova build

### ISSUE THREAD

**Issue by IgorGanapolsky** [danwilson/google-analytics-plugin#356]
Hello,
I am trying to build my Cordova application from CLI, but am getting the following build error:
> /Users/igorganapolsky/workspace/experimental/cordova/platforms/android/src/cordova-plugin-adbcordova-analytics/ADBCordovaAnalytics/ADBCordovaAnalytics.java:1: error: ';' expected
package cordova-plugin-adbcordova-analytics;

Have you seen this error before?

Igor

**Comment by victorsosa** [comment]
Sorry, this is not a google-analytics-plugin error.
