### ISSUE TITLE
Browser Platform Not Working

### ISSUE THREAD

**Issue by snowbreeze** [danwilson/google-analytics-plugin#357]
I have started the plugin in browser, everything is working fine and no errors anywhere.
I enabled debug mode and here is the output below.

```
window.ga.trackEvent('test','test', 'test','test');
VM991:1 UniversalAnalyticsProxy ["send", Object]
```
However I do not see any change in the google analytics dashboard.
Nor do I see any network changes in the network tab

**Comment by victorsosa** [comment]
Please check you google analytics dashboard. In the case of PWA you have to use the WEB ANALITICS, not the MOBILE ANALITYCS configuration.

**Comment by snowbreeze** [comment]
Good suggestion,. But I have it as web

On Jan 4, 2017 2:30 AM, "victor sosa" <notifications@github.com> wrote:

Please check you google analytics dashboard. In the case of PWA you have to
use the WEB ANALITICS, not the MOBILE ANALITYCS configuration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danwilson/google-analytics-plugin/issues/357#issuecomment-270223318>,
or mute the thread

**Comment by snowbreeze** [comment]
@danwilson any ideas?? I am stuck here. No way the browser analytic is working

**Comment by harry81** [comment]
Just want to say that I also have the same problem. I hope there might be different approach if not possible. :)

**Comment by snowbreeze** [comment]
Weird thing is, everything is fine, all apis are loaded, just no network activity or change in analytic dashboard.

**Comment by victorsosa** [comment]
@mlegenhausen was the developer for this; on #313; maybe he can help

**Comment by mlegenhausen** [comment]
@snowbreeze Could you provide a example project where I can reproduce the issue?

**Comment by joekukish** [comment]
```
GoogleAnalytics.startTrackerWithId(trackingId)
  .then(() => {
    console.log('GA is now ready');
    // Tracker is ready
    // You can now track pages or set additional information such as AppVersion or UserId
  })
  .catch(e => console.log('Error starting GA', e)); 
```
And it prints the following output

UniversalAnalyticsProxy Array[2]0: "create"1: Objectlength: 2__proto__: Array[0]
UniversalAnalyticsProxy.js:146 UniversalAnalyticsProxy Array[3]
UniversalAnalyticsProxy.js:146 UniversalAnalyticsProxy Array[2]
app.component.ts:33 Error starting GA undefined

And after a timeout it triggers an exception:

Error: Uncaught (in promise): Error: send timeout
Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:35909:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)
    at s (http://localhost:8000/build/polyfills.js:3:4211)
    at http://localhost:8000/build/polyfills.js:3:3961
    at Object.callbackFromNative (http://localhost:8000/cordova.js:295:52)
    at Object.callbackError (http://localhost:8000/cordova.js:282:17)
    at onError (http://localhost:8000/cordova.js:975:25)
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:7
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:35909:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)

**Comment by victorsosa** [comment]
@joekukish are you using IONIC2?? --> `GoogleAnalytics.startTrackerWithId(trackingId)`

**Comment by morrisonbrett** [comment]
This may be the same issue as this one?  You need to also have init code in index.html.

https://github.com/danwilson/google-analytics-plugin/issues/361#issuecomment-271168355

**Comment by joekukish** [comment]
@victorsosa yes I am

**Comment by victorsosa** [comment]
@morrisonbrett Thanks

Please check my comment on issue #291 because this could be affected by that.

**Comment by martyzz1** [comment]
See my comment here https://github.com/danwilson/google-analytics-plugin/issues/361#issuecomment-272021303

**Comment by VinceOPS** [comment]
Hi

I fixed this https://github.com/danwilson/google-analytics-plugin/pull/373.

Plugin now works in the browser (using this PR).

**Comment by victorsosa** [comment]
please fix the code conflict

**Comment by victorsosa** [comment]
sorry for the delay the v1.7.5 is up with this change

**Comment by joekukish** [comment]
@victorsosa why `v1.7.5` instead of `1.7.5`? All other versions don't have the `v`

**Comment by VinceOPS** [comment]
@joekukish "[1.7.5 is the latest of 18 releases](https://www.npmjs.com/package/cordova-plugin-google-analytics)". No `v` here.

**Comment by joekukish** [comment]
@VinceOPS thanks, I was looking at the release in Github.

**Comment by victorsosa** [comment]
@joekukish, sorry about that it is 1.7.5

**Comment by victorsosa** [comment]
Tag fix done

**Comment by coreyroth** [comment]
Ok, I have followed everything from this thread as well as #361 and I'm not having any luck.  I am on 1.7.5 of the plugin and the latest version of Ionic Native and if I include the script in index.html for the browser platform, I still get the " Cannot read property 'apply' of undefined" error.  If I take out the browser script, I get the "send timeout" error.  Is there anything else I am missing?

**Comment by victorsosa** [comment]
@coreyroth are you developing a PWA application??

**Comment by coreyroth** [comment]
@victorsosa yes PWA is one use case.  Trying to get it working in PWA form first so I switched to a web app in analytics as well.  Also developing mobile apps as well though.

**Comment by victorsosa** [comment]
@coreyroth how I generate and run a PWA? to test this out

**Comment by VinceOPS** [comment]
cordova platform add browser
    cordova build browser
    cd platforms/browser/www

**Comment by coreyroth** [comment]
I actually resolved this by following the advice in #381 by pulling the plugin directly from git.  Maybe there is an issue in what is in npm.

**Comment by victorsosa** [comment]
@coreyroth OK good to know

**Comment by jlsuarezs** [comment]
I still have the same issue using version 1.8.2.

Do I have to add a web view to google analytics? Can't keep mobile app? 

Thanks.

**Comment by RohinMohanadas** [comment]
@jlsuarezs Hi, I had the same issue. Make sure that your call to ga.startTrackerWithId('yourTrackingId') is successful.
