### ISSUE TITLE
Conversion Tracking and Remarketing for iOS

### ISSUE THREAD

**Issue by piin** [danwilson/google-analytics-plugin#359]
Hello!,
Can I implement the conversion tracking with this plugin? 
thanks in advance.

**Comment by snowbreeze** [comment]
I was wondering the same

**Comment by victorsosa** [comment]
Please explain in details what is this? never hear it

**Comment by victorsosa** [comment]
@snowbreeze I think this was implemented in the v1.8.0 already so you can get any variable from the tracker.
