### ISSUE TITLE
There is no GA dashboard activity on IOS.

### ISSUE THREAD

**Issue by mnenchev** [danwilson/google-analytics-plugin#360]
Hi,

I have created mobile app tracking GA for my cordova app. I installed GA plugin and on my deviceready listener i added the following code:
`window.addEventListener('deviceready', function () {
        console.log('Starting Tracker');
        window.ga.startTrackerWithId(window.config.GA, 30,function(msg) { console.log(msg);  });
        window.ga.setAllowIDFACollection(true);
        window.ga.trackView('TestAPP');
        window.ga.enableUncaughtExceptionReporting(false, function(msg) {console.log(msg);}, function(msg) {
          console.log('error', msg);});
        console.log('End Tracker');

    }, true);`

On ios the GA dashboard doesn't account any event. I can see that on the safari remote debugger that the first two callbacks logged "null" and there aren't any exceptions or errors, however there is activity on the GA dashboard. This is only happening when i troubleshoot the app via safari remote debugger. Any ideas what i'm doing wrong?

ios (not sure about android yet)
Cordova 6.3.1
GA plugin - 1.7.4

**Comment by victorsosa** [comment]
this is very related to issue #335
