### ISSUE TITLE
trackView rejects with throwing an error

### ISSUE THREAD

**Issue by AmitMY** [danwilson/google-analytics-plugin#361]
I am using this plugin with ionic. (latest version of everything)

I have this code:
start tracking -> track view "test"

```
GoogleAnalytics.startTrackerWithId(config.googleAnalytics).then(
    res => {
        console.log("startTrackerWithId res", res);
        GoogleAnalytics.trackView("test").then(
            res => console.log("trackView res", res),
            error => console.log("trackView error", error),
        );
    },
    error => console.log("startTrackerWithId error", error)
);
```

And the console output is:
```
trackView error Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:40846:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)
```

Am I doing something wrong?

**Comment by morrisonbrett** [comment]
I ran into the same thing.  It's a documentation problem.  There's no note to tell you that you need to have the GA code in your index.html as well!  You would think installation of a plugin would handle everything for you, but it doesn't.  You still need code in your index.html.  Copy it from the GA dashboard and paste it in.

**Comment by AmitMY** [comment]
@morrisonbrett Thanks!
You mean this, right - https://developers.google.com/analytics/devguides/collection/analyticsjs/

Also, do I need the analytics.js file as well or just the tiny script -
```
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
```

**Comment by morrisonbrett** [comment]
That's it.  The analytics.js reference is in that script.

**Comment by AmitMY** [comment]
Weird.
If I add it, the plugin rejects with "cordova not available", and it says ga is not a function
Are you sure that is the solution?

**Comment by AmitMY** [comment]
Update:
It still throws `EXCEPTION: Uncaught (in promise): Error: send timeout`
However, it now shows that in realtime there is a user using the app.
It does not show the view, as that method again, was rejected

**Comment by morrisonbrett** [comment]
@AmitMY You need to run `> ionic serve` with a config to point to your BROWSER built code.  Cordova plugins won't work with default `ionic serve`.

Here's an example in project.json:

``
    "ionic:serve": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"
``

**Comment by joekukish** [comment]
@morrisonbrett you mean "package.json" right?

**Comment by martyzz1** [comment]
Guys, Inmy experience, until the documentation gets a much needed tidy up, You are better off reading the javascript source code, if you want to make sure you know how to use the code. 
For example, startTrackerWithId  does **not** return a promise.  so you can't call it with a .then()

Instead you pass your .then() function as a callback 

`startTrackerWithID('xxxxx-xxx', 30, function(){console.log('success');}, function(){console.log('error')});`


https://github.com/danwilson/google-analytics-plugin/blob/master/www/analytics.js#L3

**Comment by joekukish** [comment]
@martyzz1 it returns a promise on ionic2: https://ionicframework.com/docs/v2/native/google-analytics/

**Comment by morrisonbrett** [comment]
@joekukish yes.  Comment updated.

**Comment by joekukish** [comment]
@morrisonbrett Thanks! If we need to manually add the script in the index.html, then it means that we need to hardcode the trackingId in 2 locations. Do you have a way to update the trackingId if it is production or not?

Thank you for the ionic:serve hint, it is really useful!

**Comment by martyzz1** [comment]
@joekukish unless ionic2 is messing around with cordova.exec() calls, I suspect you are being misinformed by the ionic docs.

I've been using ionic for a year or so, and their documentation stinks. Sometimes, you just have to read the source code and go figure it out for yourself. and Whilst I do see that the ionic 2 docs say this returns a promise, Unless they are actually patching the code themselves, when installing this library under ionic2 - which would be unusual without changing its name - I think the docs are wrong.

**Comment by morrisonbrett** [comment]
@joekukish Yes, that means you do have to hardcode the tracking location. I have a settings.json file I store it in and pull from there.

I'm glad it helped! It took me MONTHS to figure this out.  I had tried the plugin for months prior and got the same failure every time, HOPING it would be fixed by someone by the time I was ready to go live at the end of my project.  Finally, when I had to focus on getting it working, I thought to myself, hmm...Maybe I need to explicitly put the generic GA tracking code in index.html?  I was surprised when it worked, and happy I was able to move on.

The fix is either documenting this, or somehow modifying the plugin code so it injects the initialization JavaScript as part of the startTrackerWithId() execution pattern.

**Comment by AmitMY** [comment]
I was using `ionic run browser`, which does use cordova.
It manages to load all plugins including Analytics.
If I add the tracking code to the index, all plugins still work, but now the analytics one throws an error "cordova not avaialble"

**Comment by victorsosa** [comment]
@martyzz1, @joekukish is right, promise are used in ionic 2; 
Also please everybody check my comment on issue #291 this could be affecting this issue too.

**Comment by klemensz** [comment]
I can't get this to work...

If I add this snippet to the index.html (in the body tab, before build/main.js is loaded:
```
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'WEB-TRACKING-ID', 'auto');
    ga('send', 'pageview');

  </script>
```
and then this code in app.component.ts

```
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();

      GoogleAnalytics.startTrackerWithId('WEB-TRACKING-ID')
        .then(() => {
          console.log('Google analytics is ready now');
          // Tracker is ready
          // You can now track pages or set additional information such as AppVersion or UserId
          //GoogleAnalytics.setAnonymizeIp(true);
          GoogleAnalytics.trackView('test').then(
            res => console.log('trackView res', res),
            error => console.log('trackView error', error),
          );
        })
        .catch(e => console.log('Error starting GoogleAnalytics', e));
    });
```

I will get this error when I run `$ ionic run browser` (which will load the cordova.js browser proxy):
```
Error starting GoogleAnalytics TypeError: Cannot read property 'apply' of undefined
    at callCordovaPlugin (main.js:310)
    at main.js:347
    at main.js:319
    at new t (polyfills.js:3)
    at tryNativePromise (main.js:318)
    at getPromise (main.js:340)
    at wrapPromise (main.js:346)
    at Function.<anonymous> (main.js:513)
    at Function.value [as startTrackerWithId] (main.js:574)
    at main.js:96792
```
It will record one page view in GA though, the one that is initally called in the script tag.

If I don't add the script tag to the HTML, then I will get the success callback `Google analytics is ready now`, but the following error:
```
trackView error Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:35424:37)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)
```

Is there still a missing piece in my setup?
What's also not clear to me: Do I need a GA **website** property tracking ID instead of **mobile app** tracking ID? (If I want to run it as a PWA). Then I would need a second tracking ID if I run it as an Android or iOS app?

**Comment by AmitMY** [comment]
@klemensz I'm the same user from the forum BTW.
Running the same code. Running into the same problem with trackview. no news unfortunetly

**Comment by victorsosa** [comment]
guys please download the last version of Ionic 2; The version 1.7.x will work only if the new parameters are implemented in the Ionic 2 wrapper API.

**Comment by klemensz** [comment]
That are the versions I'm using, I think they are the latest ones available:

```
Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.2 
Node Version: v5.5.0
```

    "ionic-native": "2.2.16"

**Comment by dobesv** [comment]
The script tag in index.html would only be useful when you are running in the browser, NOT on a native device.  This plugin is meant for use on a device, not in a browser.  I can't tell yet whether you can by chance use the same API in the browser and on the device, but you would need to have a Web type property in the browser, and a mobile app type property on a device (I believe).

**Comment by VinceOPS** [comment]
@dobesv This plugin definitely used to work on Browser.
I already proposed a [PR](https://github.com/danwilson/google-analytics-plugin/pull/327/commits/227bd884b4a5cef0e84f8f30ce8bfd1169db09d2) to fix the broken initialization of the analytics.js object, few weeks ago.

Yet, it looks like the [code](https://github.com/danwilson/google-analytics-plugin/pull/328/commits) proposed by @mlegenhausen is still buggy. Indeed, the `this._nativeGa` object never ends up being the one properly initialized by analytics.js. Replacing
`this._nativeGa.apply(this._nativeGa, args);`

with: 
`window['nativeGa'].apply(window['nativeGa'], args);`

fixes the issue.

Now I see my events being reported on the Analytics Dashboard.

**Comment by mlegenhausen** [comment]
@VinceOPS feel free to contribute you bugfix.

**Comment by VinceOPS** [comment]
@mlegenhausen Thanks! Did it https://github.com/danwilson/google-analytics-plugin/pull/373

**Comment by klemensz** [comment]
Will this fix be released in a new version 1.7.5?

**Comment by victorsosa** [comment]
@klemensz yes, the PR #373 will be implemented in v1.7.5

**Comment by klemensz** [comment]
Is there an ETA for 1.7.5?

**Comment by victorsosa** [comment]
@klemensz  v1.7.5 is up with this change
