### ISSUE TITLE
not working after building apk

### ISSUE THREAD

**Issue by jcmag** [danwilson/google-analytics-plugin#367]
Hi,
The plugin works fine when I run my app on my device using: 
`ionic run android`

But after building an apk file, using:
`ionic package build android`

and installing it on a device, then window.ga is undefined.
So it seems something is missing in the .apk file, to successfully initialize the plugin... what could it be?

**Comment by jcmag** [comment]
I've just downgraded the plugin from 1.7.4 to 1.6.0, and now it seems to work!

**Comment by victorsosa** [comment]
if that the case; you need to update the ionic 2 package to the last release. These had happend to a lot a people.
