### ISSUE TITLE
dispatching hits manually and in background?

### ISSUE THREAD

**Issue by jvjvjv** [danwilson/google-analytics-plugin#369]
Hi.

iOS SDK has instructions for dispatching events in the background and manually dispatching them. I don't see the ability to in the plugin, though.

**Comment by victorsosa** [comment]
good question,

Manual dispatching is not available right now.

**Comment by tylermakin** [comment]
@jvjvjv @victorsosa Could a manual dispatch be achieved by calling `window.ga.startTrackerWithId` again or would this just clear the cached data that has not been dispatched yet? I asked a similar question in #401.

**Comment by victorsosa** [comment]
this can be implemented using manual dispatch in a new method like:

`window.ga.dispatch() `

that call the method in android like this:
`GoogleAnalytics.getInstance(this).dispatchLocalHits();`

iOS: has it too.

Do you aggre?

**Comment by victorsosa** [comment]
This will be release on v1.8.0
