### ISSUE TITLE
Error sending custom dimension

### ISSUE THREAD

**Issue by Matias-Carazzo** [danwilson/google-analytics-plugin#370]
Hi,
I need to send a custom dimension just in one page of my app.
My code on that page is:

**window.ga.addCustomDimension(1, $scope.bar.nombre);
window.ga.trackView('Bar Detalle');**

That is working fine.

The problem is that in other pages i just have the trackView and there is also saving the custom dimension.
My code in other pages is:
**window.ga.trackView('Mapa');**

I've set up the custom dimension on Google Analytics with hit scope.

also I've tried to send null or '' value but is it is not allowed.
**err:Expected non-empty string argument for value.**

Im doing something wrong?

thanks

**Comment by victorsosa** [comment]
Good question, here some info:

>     Custom dimension values with user or session-level scope will apply to all hits in the current session, including past hits. If you don't want a custom dimension value with session or user-level scope to be applied to past hits in the current session, start a new session before applying the value to a hit.

Then you can use:
`window.ga.trackView('Mapa', '', true);` so it could use a new session without the custom dimension.

**Comment by Matias-Carazzo** [comment]
Thanks for clarifying that.
Im using HIT scope on my dimensions, But also in that case the value is propagated to other trackView events.

**Comment by victorsosa** [comment]
for events try;
 `window.ga.trackEvent('Category', 'Action', 'Label', Value, true);`

for new session creation.

**Comment by victorsosa** [comment]
for events try;
 `window.ga.trackEvent('Category', 'Action', 'Label', Value, true);`

for new session creation.
