### ISSUE TITLE
Unknown provider: googleAnalyticsProvider

### ISSUE THREAD

**Issue by MaxDBN** [danwilson/google-analytics-plugin#374]
Hey,

I have a project that is using this plugin with Ionic framework.
I switched to a new Linux system after working on OS X for a couple of months.

On the old system the project runs flawlessly but on the new system I can't get it started. **The code is identical on both systems and no changes have been made.**

I'm trying to run the development environment with the `ionic serve` command and the client console throws me the following exception:
```
4     836947   error    Uncaught Error: [$injector:unpr] Unknown provider: googleAnalyticsProvider <- googleAnalytics
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=googleAnalyticsProvider%20%3C-%20googleAnalytics, http://192.168.1.26:8100/lib/ionic/js/ionic.bundle.js, Line: 13241
```

- Tried to remove and add the plugin
- Tried to remove and add the platforms

The plugin version is:

> cordova-plugin-google-analytics 1.7.4 "Google Universal Analytics Plugin"

I also tried using version 0.8.1 (That is working on my old system)

**Comment by victorsosa** [comment]
please double check the IONIC version in both systems (linux and OSX) using ionic -v and let me know

**Comment by victorsosa** [comment]
please follow issue #388

**Comment by MaxDBN** [comment]
Hey, turns out that the problem was with my browser's ad-block. I tried to
comment and edit the thread but I couldn't do that before for some reason.

**Comment by victorsosa** [comment]
good to know
