### ISSUE TITLE
App crashes with the latest updates of Android SDK

### ISSUE THREAD

**Issue by tgensol** [danwilson/google-analytics-plugin#375]
Hi there,

With the new Android SDK (play services updated), my app was crashing. I found that this plugin was the cause.

I also found this : https://github.com/phonegap/phonegap-plugin-push/issues/1591

We need to change the plugin.xml with :

<framework src="com.google.android.gms:play-services-analytics:10.2+" />

Regards

**Comment by victorsosa** [comment]
sorry the change is empty; I can't see what need to be changed.

**Comment by tgensol** [comment]
We need to change the plugin.xml with ( I just created a pull request ) 

You need this :

`<framework src="com.google.android.gms:play-services-analytics:10.2+" />`

Regards

**Comment by victorsosa** [comment]
The change you propose can't be used:
`<framework src="com.google.android.gms:play-services-analytics:10.2+" />`
you are forcing every body to use that version and above.
`<framework src="com.google.android.gms:play-services-analytics:+" />`
this should works and have been working for a long time.
Thanks for the PR

**Comment by victorsosa** [comment]
As they already fixed the issue as I mention before:
https://github.com/phonegap/phonegap-plugin-push/issues/1591
