### ISSUE TITLE
Not work with me

### ISSUE THREAD

**Issue by fredroo** [danwilson/google-analytics-plugin#379]
```
  initializeApp() {
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      Splashscreen.hide();

      GoogleAnalytics.startTrackerWithId('UA-0000000000-0')
         .then(() => {
           console.log('Google analytics is ready now');
           // Tracker is ready
           // You can now track pages or set additional information such as AppVersion or UserId
           GoogleAnalytics.setAllowIDFACollection(true);
         })
         .catch(e => console.log('Error starting GoogleAnalytics', e));

    });

  }
```
not work with me use this plugin 

try with emulator android e web serve

Error starting GoogleAnalytics cordova_not_available

**Comment by victorsosa** [comment]
did you install the pluging first?

**Comment by fredroo** [comment]
yes pre install, show this error in console: Error starting GoogleAnalytics cordova_not_available

**Comment by victorsosa** [comment]
double check using `ionic plugin list` comand

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/23609826/b48547c2-024e-11e7-8410-6f83645441e4.png)

**Comment by fredroo** [comment]
i try with command: ionic emulate android

but not work

**Comment by fredroo** [comment]
@victorsosa help me

**Comment by fredroo** [comment]
@danwilson help me

**Comment by victorsosa** [comment]
@fredroo please post the `ionic info`

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/23707708/18c92a88-03f2-11e7-8ff2-db9a71e00dd5.png)

**Comment by victorsosa** [comment]
can you please update you cordova lib?

**Comment by fredroo** [comment]
with command: npm update -g cordova?

**Comment by victorsosa** [comment]
@fredroo yes please, `npm install -g cordova`

**Comment by fredroo** [comment]
@victorsosa  update nodejs, cordova and ionic but not work

show this error in console: Error starting GoogleAnalytics cordova_not_available

**Comment by victorsosa** [comment]
do a remove 
`cordova plugin remove cordova-plugin-google-analytics`
and 
`cordova plugin add cordova-plugin-google-analytics`

**Comment by fredroo** [comment]
Follow steps but not work
same error: Error starting GoogleAnalytics cordova_not_available
but not work with: ionic serve -g

and

ionic emulate android

**Comment by victorsosa** [comment]
ionic serve will never work; the api only work in the emulator or device

second: you should check the android development env, to see if the GoogleAnalytics api is installed, so it can be used in the emulator.

**Comment by fredroo** [comment]
Try emulate with API Level 25 and 22 

not work

**Comment by victorsosa** [comment]
No, I meant to check you installed libs

![129ea9c6-0285-11e7-957d-926985468982](https://cloud.githubusercontent.com/assets/2557974/23750234/5e69b7b4-04a2-11e7-8e80-e3927c0daef0.PNG)

**Comment by fredroo** [comment]
I Try with: ionic run android but not work
![image](https://cloud.githubusercontent.com/assets/6863089/23894637/a8763912-0881-11e7-9f58-6d1e943d3df2.png)
![image](https://cloud.githubusercontent.com/assets/6863089/23894646/b2bbed68-0881-11e7-9396-8040717b5f39.png)
![image](https://cloud.githubusercontent.com/assets/6863089/23894655/bcda956a-0881-11e7-8d65-a85dab144133.png)

**Comment by diey** [comment]
I guess this is the same issue with [this](https://forum.ionicframework.com/t/error-googleanalytics-plugin-not-installed-but-its-already-installed/82603/2)

**Comment by fredroo** [comment]
someone help me

**Comment by victorsosa** [comment]
try `ionic platform remove android` and `ionic platform add android`

**Comment by fredroo** [comment]
try but not work

**Comment by victorsosa** [comment]
try to create a new project with the plugin and see if you duplicate the issue them.

**Comment by victorsosa** [comment]
please follow issue #388
