### ISSUE TITLE
user-id view

### ISSUE THREAD

**Issue by maxpli** [danwilson/google-analytics-plugin#38]
is anybody else having trouble with analytics.setUserId('my-user-id')? 
in google analytics user-id coverage stays at unassigned 100% even though uid=my-user-id is sent with the request. the interesting thing is that in the real time overview hits are shown in the "all mobile app data" view and in the "user view" when uid is part of the request. so google analytics doesn't seem to be accepting hits in later data analysis.
any ideas?

**Comment by Lesego** [comment]
Hi Everyone. Has anyone figured out where and why the user id doesn't work?
Is there a work around for trying to achieve the same thing?

**Comment by kryptikal** [comment]
The User ID isn't supposed to be visualized in analytics. It seems, that its there to group page hits coming from one user across several platforms: http://cutroni.com/blog/2014/04/10/understanding-cross-device-measurement-and-the-user-id/

You have to use a custom dimension instead.

**Comment by victorsosa** [comment]
@lexith thanks for the answer.
