### ISSUE TITLE
Plugin does not work on Android. Works fine on iOS.

### ISSUE THREAD

**Issue by Moghul** [danwilson/google-analytics-plugin#380]
Using Cordova CLI 6.5.0 (not Ionic, not ngCordova, not phonegap).
<engine name="android" spec="~6.0.0" />
<engine name="ios" spec="~4.3.1" />

Plugin version: 1.7.5

My setup:
```
document.addEventListener("deviceready", function () {
    window.ga.startTrackerWithId('UA-12345678-1');
}
```

And then
```
window.ga.trackEvent(eventType.category, eventType.action);
```

This is what I have installed:
![capture](https://cloud.githubusercontent.com/assets/17046245/23614953/129ea9c6-0285-11e7-957d-926985468982.PNG)

![capture](https://cloud.githubusercontent.com/assets/17046245/23615033/625e8c7e-0285-11e7-982e-009012d89fb0.PNG)

Also have all the SDK tools and platforms up to 25.

I tried with window.ga.debugMode(); but that also did nothing. There are no errors, no logs, nothing. It works perfectly find on iOS, but on Android, no events are tracked, no views are tracked, etc. The app builds, the plugin installs, window.ga is NOT undefined. It just doesn't do anything.

**Comment by N0ps32** [comment]
Hi! I have the same issue since about a month only iOS events and views are being tracked.

**Comment by N0ps32** [comment]
We managed to figure out the problem and have a workaround for now:  
Seems like something in the play-services-analytics dependency changed that broke the plugin.  
Manually setting the version to "com.google.android.gms:play-services-analytics:9.0.+" does the trick and it starts working again.

**Comment by victorsosa** [comment]
I will check this out later, thanks

**Comment by victorsosa** [comment]
can you leas post the env info using `ionic info` command?

**Comment by victorsosa** [comment]
also please check issue #375

**Comment by Moghul** [comment]
I am not using Ionic, and the app does not crash.

The app builds, runs, and there are no errors. However, nothing works on Android. Everything is fine on iOS.

I will attempt the fix N0ps32 tomorrow and will let you know whether or not it works.

**Comment by Moghul** [comment]
UPDATE:

Using "com.google.android.gms:play-services-analytics:9.0.+" causes a dex exception:

```
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzabt;
```

Using "com.google.android.gms:play-services-analytics:10.2.0" allows me to build and run, but it doesn't work. Nothing gets tracked; it acts just like before.

I have reverted my changes and opened the Android project in Android Studio. Play-services-analytics-10.2.0 shows up like this:

![capture](https://cloud.githubusercontent.com/assets/17046245/23650153/6de2f4d0-0321-11e7-8d23-569ea0297401.PNG)

Running the app in Android Studio, and looking at the Android Monitor, I found this:

```
03-07 10:35:49.610 14727-14975/my.app.details W/CordovaPlugin: Attempted to send a second callback for ID: UniversalAnalytics1056730425
                                                                      Result was: "Invalid action"
```

Seems like there isn't something wrong with the library? More like something wrong with the plugin?

**Comment by Moghul** [comment]
Well, I can't figure out what's wrong with it, so in the meantime I switched to this:

https://github.com/cmackay/google-analytics-plugin

As a tip, make sure in the admin settings (bottom left), in the view settings (far right), your IP is not excluded in the filters.
