### ISSUE TITLE
Error: send timeout

### ISSUE THREAD

**Issue by chrisbenseler** [danwilson/google-analytics-plugin#381]
I'm using the plugin in an Ionic 2 app. I configured it and I'm trying to track a view, but the error
'Uncaught (in promise): Error: send timeout' is appearing when running in the browser (as a progressive web app, build using 'ionic build browser').
My piece of code:

```
GoogleAnalytics.startTrackerWithId(AppConfig.ga)
      .then(() => {
        console.log('Google analytics is ready now');
        GoogleAnalytics.trackView('App').then( () => {
          console.log('sent');
        })
        .catch( () => {
          console.log('rejected');
 });
```

I don't understand which catch is not being handled, and why the timeout occurs. When it runs in the device, it works fine.

**Comment by victorsosa** [comment]
please env info; use the `ionic info` command

**Comment by reyazucar** [comment]
hi, i have the same problem.

error: Error: send timeout
    at http://localhost:8000/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:170:13
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8000/build/main.js:3:15075)
    at t.invokeTask (http://localhost:8000/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8000/build/polyfills.js:3:7083)
    at invoke (http://localhost:8000/build/polyfills.js:3:10836)
    at e.args.(anonymous function) (http://localhost:8000/build/polyfills.js:2:30123)

Your system information:
Cordova CLI: 6.5.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.4.7
Xcode version: Not installed

thanks.

**Comment by victorsosa** [comment]
@reyazucar are you try to use the plugin in the browser platform?

**Comment by reyazucar** [comment]
yes, i am using browser platform.
i try updating ionic to 2.2.0, ionic-native 2.8.1, cordova-plugin-google-analytics 1.7.5
but i have the same error.

**Comment by victorsosa** [comment]
@reyazucar you are getting a timeout; it means that the api can't communicate. Check that a Web App property through the Google Analytics Admin Console was created (instead of a Mobile App)

**Comment by reyazucar** [comment]
i have cheked and it is configurated as webapp.
also i tried adding the ga script in the index.html page, and in this case i have another error 
annot read property 'apply' of undefined
    at callCordovaPlugin (plugin.js:123)
    at plugin.js:160
    at plugin.js:132
    at new t (polyfills.js:3)
    at tryNativePromise (plugin.js:131)
    at getPromise (plugin.js:153)
    at wrapPromise (plugin.js:159)
    at Function.<anonymous> (plugin.js:317)
    at Function.value [as startTrackerWithId] (plugin.js:378)
    at GoogleAnalyticService.init (googleAnalyticsService.ts:26)
    at app.component.ts:66
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (ng_zone.js:273)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)

So, if i put the ga script i have and error in GoogleAnalytics.startTrackerWithId(XXXX)
and if i not put the ga script, GoogleAnalytics.startTrackerWithId(XXXX) start fine, but then i have the timeout error en de trackview

**Comment by victorsosa** [comment]
@reyazucar do not try to add the ga script in the index.html page; this is don't by this plugin

**Comment by mordka** [comment]
Has anyone found a solution or a workaround to this problem? 
I'm runing Ionic app in browser and it's using cordova.

info:
```    "cordova-plugin-google-analytics": "1.7.5",```
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.1
Xcode version: Not installed
```

**Comment by victorsosa** [comment]
@mordka and @reyazucar please update to 1.7.6 it should be fine now, please let me know.

**Comment by reyazucar** [comment]
yes, now it is working fine my ionic2 pwa with the 1.7.9 version.
many thanks to all

**Comment by victorsosa** [comment]
closing this

**Comment by jlsuarezs** [comment]
I am still having the same issue using version 1.8.2: Error: Uncaught (in promise): Error: send timeout

Do I need to add a web view to google analytics? Or just keep the mobile view is ok?

Thanks.

**Comment by jlsuarezs** [comment]
It's not ok in my case using v1.8.3 and Ionic 4. Any thoughts?

**Comment by RohinMohanadas** [comment]
@jlsuarezs : I am getting the same error in v1.8.3
