### ISSUE TITLE
trackMetric JSON error

### ISSUE THREAD

**Issue by Lightning3105** [danwilson/google-analytics-plugin#382]
I get 'JSON error' printed to the console when using this code:
`window.ga.trackMetric('metric1', v.score, function(e){console.log(e)}, function(e){console.log(e)})`
Where v.score is an integer.

I have set a custom metric using `window.ga.addCustomDimension(1, v.mode)`, which seems to work fine. 

What am I doing wrong? Do I use 'metric1', or do I use the index like when setting a custom dimension? The error doesn't appear when I just use the index, but no data for that metric appears on my analytics dashboard.

**Comment by victorsosa** [comment]
please provide more data about the dev env that you are using; Also the key should be an Integer.

**Comment by victorsosa** [comment]
check issue comment on #436
