### ISSUE TITLE
[Ionic 1] analytics is not defined

### ISSUE THREAD

**Issue by sambhalgithub** [danwilson/google-analytics-plugin#384]
I am trying to integrate the Google analytics in my app using the tutorial [here](https://www.thepolyglotdeveloper.com/2014/06/using-google-analytics-ionicframework/)  

This is my code.
`// Ionic Starter App

// angular.module is a global place for creating, registering and retrieving Angular modules
// 'starter' is the name of this angular module example (also set in a <body> attribute in index.html)
// the 2nd parameter is an array of 'requires'
angular.module('starter', ['ionic'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {

    if(typeof analytics !== 'undefined') {
    analytics.startTrackerWithId("UA-96110297-1");
  } else {
    console.log("Google Analytics Unavailable");
    alert("Google Analytics Unavailable");
  }

    if(window.cordova && window.cordova.plugins.Keyboard) {
      // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
      // for form inputs)
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      // Don't remove this line unless you know what you are doing. It stops the viewport
      // from snapping when text inputs are focused. Ionic handles this internally for
      // a much nicer keyboard experience.
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
}).controller('AwesomeController', function($scope, $window) {
    if(typeof analytics !== 'undefined') { analytics.trackView("Awesome Controller"); } else { alert(JSON.stringify($window.analytics))}
 
    if(typeof analytics !== 'undefined') { analytics.trackEvent("Category", "Action", "Label", 25); }

    alert('Awesome controller')
});
`

and I am **testing it on my device but get the error as follows**

>  800665   error    ReferenceError: analytics is not defined

I have tried following global variable but all are **undefined**
**analytics, $window.analytics, ga, $window.ga**
I have even tried using **ngCordova** and also **tried readding the plugin again many times** but same error is showing.

**Comment by jamadrigale** [comment]
hi @sambhalgithub, i had the same problem, but i solved using $ionicPlatform.ready function.
try this:

.run(function($ionicPlatform){
    $ionicPlatform.ready(function() {
        if(typeof analytics !== 'undefined') {
            analytics.startTrackerWithId("UA-XXXXXXX-1");
        }
    }
};

i hope help you.

**Comment by victorsosa** [comment]
please follow this issue #388
