### ISSUE TITLE
Ability to end a session

### ISSUE THREAD

**Issue by yethie** [danwilson/google-analytics-plugin#398]
Would it be possibile to end a ga session without creating a new one?
Something equivalent to invoking:
`ga('send', 'pageview', {'sessionControl': 'end'});`

**Comment by victorsosa** [comment]
No, right now; but it can be implement using the set method in the tracker object

**Comment by victorsosa** [comment]
This will be release on v1.8.0 as:

To set a specific variable using this key list https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters:
for example to set session control:
* `window.ga.setVar('sc', 'end', function(result){ console.log(result);})`
