### ISSUE TITLE
uBlock origin extension blocks loading js files

### ISSUE THREAD

**Issue by dkarpik** [danwilson/google-analytics-plugin#400]
When user uses uBlock origin extension, the ionic app is not starting because it blocks plugin files. Ublock origing blocks any request that have '-google-analytics/' in path. Full list can be found here: https://github.com/gorhill/uBlock/blob/e6707fe8b155cc92da1cb5e4aad7098b057429cd/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt

```
cordova.js:1528 GET http://xxx/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js net::ERR_BLOCKED_BY_CLIENT
```

**Comment by victorsosa** [comment]
no idea how you will made this work without calling the '-google-analitycs' platform in the request
