### ISSUE TITLE
Dispatch when app goes into background

### ISSUE THREAD

**Issue by tylermakin** [danwilson/google-analytics-plugin#401]
It would be very useful to dispatch when the app goes into the background. With this method, the dispatch period could be substantially longer, thereby improving battery life.

Cordova already has a [pause event](http://cordova.apache.org/docs/en/6.x/cordova/events/events.html#pause) that could be listened for and a dispatch could be sent once the app is in the background. This could be a native feature of this plugin or could be configured by the users if a manual dispatch command were to be introduced.

Per the video in the [Firebase Analytics docs](https://firebase.google.com/docs/analytics/ios/start), Firebase dispatches information once an hour or when an app goes to the background.

This would be particularly useful for apps with minimal user interaction (<20 seconds on average).

Keep up the great work!

**Comment by tylermakin** [comment]
After taking a look at the [code for iOS](https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m), would it be possible to achieve the effect of a manual push by setting the dispatch period to a long period such as `window.ga.startTrackerWithId('UA-XXXX-YY', 3600)` then calling the function again when a manual push is desired? Or would calling this function again clear the cached data that has not been dispatched yet?

If this method would work to send a manual dispatch the data could be sent manually or when an app is sent to the background.

**Comment by victorsosa** [comment]
This will be release on v1.8.0
