### ISSUE TITLE
Cordova and Ionic not compiling right now

### ISSUE THREAD

**Issue by damarni** [danwilson/google-analytics-plugin#405]
CompileC /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.o Abracadapp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by victorsosa** [comment]
please provide the env info and can you check using the previous version 1.7.11 too

**Comment by victorsosa** [comment]
do you have a more complete log;  so I can get a idea of the line causing the compile issue?

**Comment by damarni** [comment]
Hi, thanks.

I don’t know how to try the older version because I added the plugin directly to my ionic app

The error I have is this one with the latest version:

CompileC /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.o Abracadapp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/danigil/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/danigil/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-generated-files.hmap -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-own-target-headers.hmap -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-all-target-headers.hmap -iquote /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-project-headers.hmap -I/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator/include -I/Users/danigil/Projects/pr
ova/abracadapp/abracadapp/platforms/ios/build/emulator/usr/local/lib/include -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/UninstalledProducts/include -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/UninstalledProducts/iphonesimulator/include -I/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/DerivedSources/x86_64 -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/DerivedSources -F/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator -include /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/sharedpch/Abracadapp-Prefix-bvcqsdxlfmayyocckxdppmtmrqup/Abracadapp-Prefix.pch -MMD -MT dependencies -MF /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.d --serialize-diagnostics /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.dia -c /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/Abracadapp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m -o /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.o
/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/Abracadapp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m:101:19: error: initializing 'NSString *__strong' with an expression of incompatible type 'void'
        NSString* result = [tracker set:parameterName value:parameter];
                  ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

CompileC /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/CDVShake.o Abracadapp/Plugins/cordova-plugin-shake/CDVShake.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/danigil/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/danigil/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-generated-files.hmap -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-own-target-headers.hmap -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-all-target-headers.hmap -iquote /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Abracadapp-project-headers.hmap -I/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator/include -I/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator/usr/local/lib/include -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/UninstalledProducts/include -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/UninstalledProducts/iphonesimulator/include -I/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/DerivedSources/x86_64 -I/Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/DerivedSources -F/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator -include /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/sharedpch/Abracadapp-Prefix-bvcqsdxlfmayyocckxdppmtmrqup/Abracadapp-Prefix.pch -MMD -MT dependencies -MF /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/CDVShake.d --serialize-diagnostics /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/CDVShake.dia -c /Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/Abracadapp/Plugins/cordova-plugin-shake/CDVShake.m -o /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/CDVShake.o


** BUILD FAILED **


The following build commands failed:

CompileC /Users/danigil/Library/Developer/Xcode/DerivedData/Abracadapp-cjmwzcwnzdjdfxddweyzmycyjisj/Build/Intermediates/Abracadapp.build/Debug-iphonesimulator/Abracadapp.build/Objects-normal/x86_64/UniversalAnalyticsPlugin.o Abracadapp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/cordova/build-debug.xcconfig,-workspace,Abracadapp.xcworkspace,-scheme,Abracadapp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/danigil/Projects/prova/abracadapp/abracadapp/platforms/ios/build/sharedpch



Dani

**Comment by victorsosa** [comment]
I so the compile issue, I am doing the fix;

you can install previous version like:
cordova plugin add cordova-plugin-google-analytics@1.7.11

**Comment by victorsosa** [comment]
Fixed, try to install the latest version 1.8.1

**Comment by damarni** [comment]
Thanks it works great now 👍
