### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by shenzj1994** [danwilson/google-analytics-plugin#407]
I got the following error when I was doing 'cordova build android', right after I updated it to latest version. 
It has no issue in 1.7.11.

> :compileDebugJavaWithJavacC:\eDocs\eDocs Repo\app\platforms\android\src\com\danielcwilson\plugins\analytics\UniversalAnalyticsPlugin.java:390: error: incompatible types: void cannot be converted to String
>         String result = tracker.set(variable, value);
>                                    ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
>  FAILED
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

**Comment by victorsosa** [comment]
compile issue fixed on v1.8.2
