### ISSUE TITLE
New update not working in IONIC or CORDOVA on Android

### ISSUE THREAD

**Issue by damarni** [danwilson/google-analytics-plugin#409]
Hi, I've tried compiling my app for Android and with the latest update of this plugin it doesn't work.

Here is the error:
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/danigil/Projects/abracadapp/abracadapp/platforms/android/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:390: error: incompatible types: void cannot be converted to String

        String result = tracker.set(variable, value);
                                   ^

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.06 secs

Error: /Users/danigil/Projects/abracadapp/abracadapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/danigil/Projects/abracadapp/abracadapp/platforms/android/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:390: error: incompatible types: void cannot be converted to String
        String result = tracker.set(variable, value);
                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Thanks in advance!

**Comment by miguelcarrascoq** [comment]
Same error here:
.../platforms/android/src/com/danielcwilson/plugins/analytics/UniversalAnalyticsPlugin.java:390: error: incompatible types: void cannot be converted to String
        String result = tracker.set(variable, value);

My config:
  Cordova CLI: 6.5.0 
  Ionic Framework Version: 3.1.1
  Ionic CLI Version: 2.2.1
  Ionic App Lib Version: 2.2.0
  Ionic App Scripts Version: 1.3.6
  ios-deploy version: 1.9.1 
  ios-sim version: 5.0.13 
  OS: macOS Sierra
  Node Version: v7.5.0
  Xcode version: Xcode 8.3.2 Build version 8E2002

Installed platforms:
  android 6.2.2
  browser 4.1.0
  ios 4.3.1

Android SDK build tools: 25.0.3
Android SDK Platform-Tools: 25.0.5
Android SDK Tools: 26.0.2

**Comment by miguelcarrascoq** [comment]
I resolve this by installing:

$ sudo cordova platform update android@6.2.2
$ sudo cordova plugin add cordova-plugin-google-analytics@1.6.0 --save

... and make sure in your config.xml:
<plugin name="cordova-plugin-google-analytics" spec="~1.6.0" />

Hope this help

**Comment by victorsosa** [comment]
fixed on v1.8.2
