### ISSUE TITLE
getVar always returns undefined in browser

### ISSUE THREAD

**Issue by sundbry** [danwilson/google-analytics-plugin#410]
getVar seems to be losing the reference to the analytics tracker instance when using analytics.js:

    ga.setVar("cid", "foo-1234", function (success) {console.log("cid set")}, function (error) {});
    ga.getVar("cid", function (success) {console.log("cid: " + success)}, function (error) {console.error(error)});
    undefined
    cid set
    cid: undefined

**Comment by victorsosa** [comment]
which platform?

**Comment by victorsosa** [comment]
please check and test this first:
cid: The value of this field should be a random UUID (version 4) as described in http://www.ietf.org/rfc/rfc4122.txt.

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid

**Comment by sundbry** [comment]
This is on the browser platform


    ga.setVar("cid", "06739372-8c99-4ba0-9629-ddb462d8163d", function (success) {console.log("cid set")}, function (error) {});
    ga.getVar("cid", function (success) {console.log("cid: " + success)}, function (error) {console.error(error)});

same results with &cid

    ga.setVar("&cid", "06739372-8c99-4ba0-9629-ddb462d8163d", function (success) {console.log("cid set")}, function (error) {});
    ga.getVar("&cid", function (success) {console.log("cid: " + success)}, function (error) {console.error(error)});

    no change

    nativeGa.getAll()[0].get('clientId');
    "1547248739.1493983614"
    // this works
    ga.setUserId("abcd")
    nativeGa.getAll()[0].get('&uid');
   "abcd"

**Comment by victorsosa** [comment]
This is happening in PWA platform only

**Comment by victorsosa** [comment]
this could be an implementation:
```
  getVar: function (param, success, error) {
    this._ga(function(tracker){
      success(tracker.get(param));
    });
  },
```

**Comment by victorsosa** [comment]
@mlegenhausen please check this and share with us you thoughts.

**Comment by mlegenhausen** [comment]
@victorsosa Seems to me [the official way of getting variables](https://developers.google.com/analytics/devguides/collection/analyticsjs/accessing-trackers#getting_data_stored_on_a_tracker). I am totally fine with that 👍

**Comment by victorsosa** [comment]
Ok, PR merged

**Comment by victorsosa** [comment]
release 1.8.3
