### ISSUE TITLE
[Browser] exec proxy not found for :: UniversalAnalytics :: startTrackerWithId

### ISSUE THREAD

**Issue by biesbjerg** [danwilson/google-analytics-plugin#413]
When building a PWA (`cordova build browser`) I get the following error when accessing the plugin:
`Error: exec proxy not found for :: UniversalAnalytics :: startTrackerWithId`

My usage (through Ionic Native v3.6.1):
```ts
export class AppComponent implements OnInit {

	public constructor(
		protected _platform: Platform,
		protected _googleAnalytics: GoogleAnalytics
	) {

	}

	public ngOnInit(): void {
		this._platform.ready().then(() => {
			this._googleAnalytics.startTrackerWithId('UA-XXX');
		});
	}
```

I'm using v1.8.2 of this plugin. 

Did I miss something?

**Comment by victorsosa** [comment]
please do 
`cordova plugin rm cordova-plugin-google-analytics`

`cordova plugin add cordova-plugin-google-analytics --save`
`npm i --save @ionic-native/google-analytics`

and try again

**Comment by biesbjerg** [comment]
Hi,

I didn't change anything. I already had the latest versions installed (and verified that it actually was the latest versions in my platform).

**Comment by biesbjerg** [comment]
Scratch that! Sorry, somehow it started working. 

I swear I verified the newest versions were installed. Thanks!

**Comment by victorsosa** [comment]
good to know
