### ISSUE TITLE
Removing custom dimensions

### ISSUE THREAD

**Issue by light** [danwilson/google-analytics-plugin#415]
The plugin currently does not allow to remove custom dimensions, only to add them. If you try to set the custom dimension to an empty string or `null` there is an error :
>Expected non-empty string argument for value.

It would be useful to allow to remove a custom dimension either by a `removeCustomDimension` method or allowing a null value as argument to `addCustomDimension`.

**Comment by victorsosa** [comment]
please check issue #420 for answer this question

**Comment by spacepope** [comment]
I think @light could be right.
As the custom dimensions and metrics on Android and Windows are set internally in a dictionary and then added to each hit on trackView, trackEvent, etc..., there is currently no possibility to unset this dimension/metric.

@victorsosa, now the penny has dropped and i finally realize why you documented the value parameter as optional before my last PR to fix trackMetric.. This way it could be unset on being null or undefined..

I will look into this in the next days and submit a new PR..
