### ISSUE TITLE
getvar breaks ios

### ISSUE THREAD

**Issue by snowbreeze** [danwilson/google-analytics-plugin#417]
![screen shot 2017-05-16 at 6 30 01 pm](https://cloud.githubusercontent.com/assets/8898721/26107092/bd60d7d6-3a65-11e7-852e-e6e33f806dbd.png)

**Comment by victorsosa** [comment]
The parameter seems to be Nil.

**Comment by victorsosa** [comment]
please try the 1.8.3; there is a fix for this.
