### ISSUE TITLE
Custom Metric is sent with more than one hit

### ISSUE THREAD

**Issue by nsoojin** [danwilson/google-analytics-plugin#418]
Hi guys,
As far as I know, a custom metric is sent with a single hit, but once I set a custom metric using trackMetric() function, the metric is also sent with all other subsequent hits.

I think this a bug, or do I have to explicitly unset the custom metric?

thanks in advance!

**Comment by victorsosa** [comment]
Yes, you have to unset it; you can create a new session for the subsequent hits.
`window.ga.trackView('Screen Title', '', true)` using the last parameter.

From Docs:
https://developers.google.com/analytics/devguides/collection/android/v4/customdimsmets

`If you don't want a custom dimension value with session or user-level scope to be applied to past hits in the current session, start a new session before applying the value to a hit.`

**Comment by victorsosa** [comment]
please check comment on issue #424

**Comment by victorsosa** [comment]
fixed on v1.9.0
