### ISSUE TITLE
error on compile the app

### ISSUE THREAD

**Issue by pawelduszczak** [danwilson/google-analytics-plugin#419]
When I install this plugin and try to complie my app I'm getting such error:

![error](https://cloud.githubusercontent.com/assets/20207676/26248424/9d741eb2-3ca2-11e7-9b36-8c4d35ad3eee.jpg)

Is there enything i can do to get it to work properly?

**Comment by victorsosa** [comment]
This error is not related to this plugin; please check you code.

**Comment by pawelduszczak** [comment]
@victorsosa not so quick :)
Until i installed this plugin all was just fine, no errors at all. Also no errors in app code. So I'm thinking there must be some conflict maybe with other plugin or in this plugin itself. Even if it's not error in this plugin I have no other startpoint because errors occured after this specific plugin installation.

**Comment by victorsosa** [comment]
as you can see in the console log the error is related to the google maps plug-in that you are using.
