### ISSUE TITLE
Multiple dex files error

### ISSUE THREAD

**Issue by MarsupiL** [danwilson/google-analytics-plugin#423]
I get this error when using this plugin together with any cordova firebase push notifications plugin.
It seems that this analytics plugin uses a deprecated way of declaring the dependencies of the play-services-gcm. (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#multidex)

**Comment by victorsosa** [comment]
Please read the documation you sent:

> Alternatively, switch to another plugin that provides the same functionality but uses gradle:
> 
> https://github.com/danwilson/google-analytics-plugin https://github.com/cmackay/google-analytics-plugin

**Comment by vinimendes3** [comment]
I'm also facing this problem with multiple dex files error.
![screen shot 2017-06-16 at 3 35 11 pm](https://user-images.githubusercontent.com/3437722/27239972-73f3cbb0-52a9-11e7-8f32-624d5b348084.png)

**Comment by victorsosa** [comment]
Because, when some other packages include cordova-google-play-services as a dependency; that is not correctly imported.

**Comment by liquidcms** [comment]
Are you saying that:
1. GA conflicts with another plugin 
2. that other plugin uses play services, but does so incorrectly

Is there any way to find out which plugin is causing the issue?
