### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by remisture** [danwilson/google-analytics-plugin#425]
`cordova plugin add cordova-plugin-google-analytics`

> Error: Failed to fetch plugin git+https://github.com/danwilson/google-analytics-plugin.git via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Failed to get absolute path to installed module

Any ideas?

Thanks!

**Comment by victorsosa** [comment]
environment info please

**Comment by remisture** [comment]
> Cordova CLI: 6.4.0
> Gulp version:  CLI version 3.9.0
> Gulp local:   Local version 3.9.1
> Ionic Framework Version: 1.3.2
> Ionic CLI Version: 2.0.0
> Ionic App Lib Version: 2.0.0
> ios-deploy version: 1.9.0 
> ios-sim version: 5.0.8 
> OS: Mac OS X El Capitan
> Node Version: v4.2.6
> Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by victorsosa** [comment]
Please retry using `cordova plugin add https://github.com/danwilson/google-analytics-plugin.git`

also I recommend you to update you node to v6.x.x

**Comment by camillarhodes** [comment]
I get the same error (even with the full github address) 
any reason for closing this issue?

**Comment by HenryTiquet** [comment]
For those that at this time are looking for a posible solution. I got this to work by downgrading my npm version from 9.3.1 to 6.14.8. I am working on a old project and the dependencies versions are a big pain.

`npm install npm@6.14.8`

You may need to find the npm version that would match with your project dependencies versions and downgrade to that version.

I hope it can help someone save some time.
