### ISSUE TITLE
Pin version of Google Play Services to 11+

### ISSUE THREAD

**Issue by jacquesdev** [danwilson/google-analytics-plugin#427]
Hi @danwilson 

There seems to be an issue with this plugin when used in conjunction with the cordova-plugin-facebook4 plugin. The issue is that the Google Play Services dependency on this project should probably be pinned to whatever version you want it to be on. I saw 11 is the latest, and so I guess this is a good starting point.

I am working on a fix now, and will open a PR shortly.

Please see the issue below, we have asked a couple of other plugin owners to make similar changes to keep this working.

https://github.com/jeduan/cordova-plugin-facebook4/issues/507#issuecomment-307215695

**Comment by victorsosa** [comment]
Hi, @jacquesdev 

You should not use pinned versions on that plugin; you should use it like this:
```
<framework src="com.android.support:support-v4:+" />
<framework src="com.android.support:appcompat-v7:+" />
```
As they comment on the issue you should use the wildcard + to use the latest version.  

No change need to me made in this plugin. Sorry but there is nothing to change in this project. And yes I read the complete issue [#507](jeduan/cordova-plugin-facebook4#507 (comment))
