### ISSUE TITLE
Website URL required for mobile app tracking code creation

### ISSUE THREAD

**Issue by BrianJVarley** [danwilson/google-analytics-plugin#430]
Hi, 

 I'm setting up this `google-analytics-plugin` plugin in a mobile app but require a Google Analytics tracking code to configure.
I can setup a new account in my analytics dashboard but the on-boarding step requires a `website url`.

As this is a mobile app how do I provide a URL during this step?
Or does it matter what URL is supplied if using this tacking code with your plugin?

Thanks!
![ga-url](https://user-images.githubusercontent.com/6731968/27378488-f5068fe8-566f-11e7-8377-033ef91a6446.PNG)

**Comment by victorsosa** [comment]
> Mobile-App

 is the correct set. Please select the tab.
