### ISSUE TITLE
Can't get Referrer value

### ISSUE THREAD

**Issue by zepfan** [danwilson/google-analytics-plugin#431]
I cannot for the life of get any campaign information to return from the `getVar()` method. It seems a lot of other people have this same issue and it's never been resolved/clearly answered.

Given this code:

```
window.ga.getVar('cn', function (result) {
  if(!result) {
    return false;
  }

  // do something
});
```

And broadcasting the intent via `adb shell`:
```
am broadcast -a com.android.vending.INSTALL_REFERRER -n com.example.app/com.google.android.apps.analytics.AnalyticsReceiver --es "referrer" "utm_source=testSource\&utm_medium=testMedium\&utm_term=testTerm\&utm_content=testContent\&utm_campaign=testName"
```

```
am broadcast -a com.android.vending.INSTALL_REFERRER -n com.example.app/com.google.android.apps.analytics.CampaignTrackingReceiver --es "referrer" "utm_source=testSource\&utm_medium=testMedium\&utm_term=testTerm\&utm_content=testContent\&utm_campaign=testName"
```

OR just using this link to the Play Store:
```
https://play.google.com/store/apps/details?id=com.example.app&referrer=utm_source%3DtestSource%26utm_medium%3DtestMedium%26utm_term%3DtestTerm%26utm_content%3DtestContent%26utm_campaign%3DtestName
```
I get nothing every time.

I've also tried using `&cn` as suggested in other tickets without any success.

Has anyone figured this out?

**Comment by victorsosa** [comment]
Please comment on check issue #410

**Comment by rooswelt** [comment]
Same problem here, on last (1.8.3) release.

Tried both `cn` and `&cn` with no luck.

Please @victorsosa point us to the right comment on #410

**Comment by snowbreeze** [comment]
This issue is open, cant still get cn values in javascript
