### ISSUE TITLE
Tracker not started

### ISSUE THREAD

**Issue by thomdejong101** [danwilson/google-analytics-plugin#433]
**Used versions:**
```
  "@ionic-native/core": "3.10.2",
  "@ionic-native/google-analytics": "^3.12.1",
  "cordova-plugin-google-analytics": "^1.8.2",
```

**I'm submitting a ...**
[ X] bug report

**Current behavior:**

When trying to start tracking of my app I recieve a "Tracker not started" error from the: enableUncaughtExceptionReporting promise.
This results in the "trackView" method not working. The "trackEvent" however does work and is registered in google analytics.

**Expected behavior:**

Of the two methods mentioned above one of the following: neither method works or both methods work.

**Related code:**

        private startAnalytics() {
		if (!this.platform.is("cordova")) {
			console.log("PC build");
			return;
		}
		this.platform.ready().then(() => {

			this.ga.enableUncaughtExceptionReporting(true)
				.then((_success) => {
					console.log("GoogleAnalytics success: " + _success);
				}).catch((_error) => {
					console.trace();
					console.log("GoogleAnalytics error: " + _error);
				});

			this.ga.startTrackerWithId('UA-38xxx-31', 5)
				.then((e) => {
					console.log(e);
					this.startedTracking = true;
					this.ga.debugMode();
					this.ga.setAnonymizeIp(true);
					this.ga.trackView("start", '', true).then(() => console.log("tracking view started"));
				})
				.catch(e => console.log('Error starting GoogleAnalytics', e));
		});
	}

Possibly related to:
#291

**Comment by victorsosa** [comment]
@thomdejong101 you can only call `this.ga.enableUncaughtExceptionReporting` after calling `this.ga.startTrackerWithId` which init the component.

**Comment by thomdejong101** [comment]
@victorsosa Thank you for your quick response. After moving the code I no longer recieve the error message. I also do not recieve content on google analytics. When checking my logs from android I found these:
```
06-27 14:03:11.301 25175-25282/com.everywhereim.bep W/PluginManager: THREAD WARNING: exec() call to UniversalAnalytics.startTrackerWithId blocked the main thread for 19ms. Plugin should use CordovaInterface.getThreadPool().
06-27 14:03:11.305 25175-25175/com.everywhereim.bep D/SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 25237 : tracker started
06-27 14:03:11.305 25175-25175/com.everywhereim.bep I/chromium: [INFO:CONSOLE(25237)] "tracker started", source: file:///android_asset/www/build/main.js (25237)
06-27 14:03:11.306 25175-25282/com.everywhereim.bep I/GAv4: Logger is deprecated. To enable debug logging, please run:
                                                            adb shell setprop log.tag.GAv4 DEBUG
06-27 14:03:11.307 25175-25282/com.everywhereim.bep W/CordovaPlugin: Attempted to send a second callback for ID: UniversalAnalytics627750449
                                                                     Result was: "Invalid action"
```

Which might be the cause the problem. Please let me know if you see any mistakes that I made in the implementation. The code I use for calling the trackView and trackEvent is below:
```
public trackView(viewName) {
		this.platform.ready().then(() => {

			if (this.startedTracking) {
				console.log("tracking: " + viewName);
				this.ga.trackView(viewName).then((e) => { console.log(e); }).catch(e => console.log(e));
			}
		});
	}

	public trackEvent(category: string, action: string, label: string = null, value: number = null, newSession: boolean = null) {
		if (this.startedTracking) {
			this.ga.trackEvent(category, action, label, value, newSession);
		}
	}
```

**Comment by thomdejong101** [comment]
I finally figured out that I made a mistake in setting up the google analytics itself by checking the data as if it was a website instead of a mobile application.

**Comment by ZumelzuR** [comment]
Is a problem related with google-play-services incompatibilities. For fix it you have to make sure that all the PLAY_SERVICES_VERSION are the same, in my case for google-maps, googleplus  and the rest I used 15.0.2, but for analytics I have to use 15.0.2 (because there are not a 15.0.1 in maven repo).

SO go to your config.xml and add/change your analytics plugin tag to

```
    <plugin name="cordova-plugin-google-analytics">
        <variable name="PLAY_SERVICES_VERSION" value="15.0.2" />
    </plugin>
```

and make sure that all the other plugins have some 15.* version. (if you are using another one just make sure that all play service use the same version)

Then if you already added a platform, go to platforms/android/project.properties and the same, just make sure that all play-services libraries are the same version. for example I have:

```
cordova.system.library.10=com.google.android.gms:play-services-analytics:15.0.2
cordova.system.library.13=com.google.android.gms:play-services-maps:15.0.1
```
...

Hope that this work for you, work for me after a lot of research.
