### ISSUE TITLE
Conflict with phonegap-plugin-push

### ISSUE THREAD

**Issue by gustter** [danwilson/google-analytics-plugin#435]
I'm using PGB platform.

When I compile my App using phonegap-plugin-push and google-analytics-plugin an error occurs (only Android):

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;

Any idea?

Thanks!

**Comment by victorsosa** [comment]
please check comment issue #178

**Comment by gustter** [comment]
I see those references are a bit old.

I'm using:

<Preference name = 'phonegap-version' value = 'cli-6.3.0' />
<Preference name = "android-build-tool" value = "gradle" />
<Plugin name = "phonegap-plugin-push" spec = "1.8.2">
<Plugin name = "cordova-plugin-google-analytics" />

I have tried the various suggestions but they do not work.

Do you know if both plugins can work together?
That is, if there is any antecedent known.

Thanks.

**Comment by davgc** [comment]
We have the same problem

**Comment by abducbk** [comment]
I am getting the same error.
Error: /home/abdullaku/Desktop/kabinger_Cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

Where:
Script '/home/abdullaku/Desktop/kabinger_Cordova/platforms/android/phonegap-plugin-push/kabinger-push.gradle' line: 38

What went wrong:
A problem occurred evaluating root project 'android'.

Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
For input string: "+"
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
In my Project added push plugin and google analytics plugin..i tried all the above solution but that not working,

**Comment by AKosmachyov** [comment]
I solve the problem with "Multiple dex files define" using this plugin: [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release)

**Comment by victorsosa** [comment]
@AKosmachyov Thanks for the info.

**Comment by phonic** [comment]
@abducbk You problem seems to be different as it was indicated by @gustter 

To solve your individual problem, take a look at this resource
https://github.com/cmackay/google-analytics-plugin/issues/77

To make the story short:
- remove android platform
- change playservice-version in analytics-plugin.xml from "+" to match your desired one (eg. "11.0.1")
- add android platform again
- build

Hope it helps...

**Comment by victorsosa** [comment]
fixed on v1.8.4
