### ISSUE TITLE
Success callback is not called in addCustomDimension

### ISSUE THREAD

**Issue by mrzmyr** [danwilson/google-analytics-plugin#44]
I think the success callback `callbackContext.success` is not called in the [`addCustomDimension`](https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L111) method.

Let me know if a PR is appreciated.

**Comment by kevinbarz** [comment]
Hello. Thanks for all the good work Dan. I've just come across this issue as well. Do you still need a PR?

**Comment by mrzmyr** [comment]
@kevinbarz don't have the time currently, would be great if you can help out with a PR here :+1:

**Comment by danwilson** [comment]
Resolved by @kevinbarz in PR
