### ISSUE TITLE
Why will addTransaction be Deprecated on 1.9.0

### ISSUE THREAD

**Issue by tobischulz** [danwilson/google-analytics-plugin#442]
Hello,

can anybody tell me why addTransaction and addTransactionItem will be deprecated on 1.9.0? Are there changes on Google-Analytics side or what happened?

Thank you

**Comment by victorsosa** [comment]
yes, it is deprecated on Google-Analytics side; check [ecommerce](https://developers.google.com/analytics/devguides/collection/android/v4/ecommerce)

**Comment by tobischulz** [comment]
Thank you, so do you think i can use the deprecated addTransaction till this plugin will support the new enhanced ecommerce sdk or is it unusable on google´s serverside?

**Comment by victorsosa** [comment]
You can use the deprecated addTransaction even in this plugin, it will support

**Comment by victorsosa** [comment]
Hi, @spacepope 

This is what I am working in the new Enhanced Ecommerce Tracking for GA.

Look the API propose:

/**
  Enhanced Ecommerce Tracking

  Enhanced ecommerce enables the measurement of user interactions with products across the user's shopping experience, which include product impressions, product clicks, viewing product details, adding a product to a shopping cart, initiating the checkout process, transactions, and refunds.

  Product definition:
    var product = {};
    product.id = "P12345";
    product.name = "Android Warhol T-Shirt";
    product.category = "Apparel/T-Shirts";
    product.brand = "Google";
    product.variant = "Black";
    product.position = 1;
    product.customDimension = [1, "Member"];
    product.customMetric = [1, 12];
    product.price = 10.00;
    product.quantity = 10;
    product.CouponCode = '123AEV'

  Product Action definitions:
    ACTION_ADD                Action to use when a product is added to the cart.
    ACTION_CHECKOUT            Action to use for hits with checkout data.
    ACTION_CHECKOUT_OPTION    Action to be used for supplemental checkout data that needs to be provided after a checkout hit.
    ACTION_CHECKOUT_OPTIONS    This constant was deprecated. Use ACTION_CHECKOUT_OPTION instead.
    ACTION_CLICK              Action to use when the user clicks on a set of products.
    ACTION_DETAIL              Action to use when the user views detailed descriptions of products.
    ACTION_PURCHASE            Action that is used to report all the transaction data to GA.
    ACTION_REFUND              Action to use while reporting refunded transactions to GA.
    ACTION_REMOVE              Action to use when a product is removed from the cart.


    var productAction = {};
    productAction.action = "ACTION_PURCHASE";
    productAction.transactionId = "TT-1234";
    productAction.transactionRevenue = 3.14;
    productAction.transactionCouponCode = "EXTRA100";
    productAction.transactionShipping = 2.03;
    productAction.transactionTax = 1.02;
    productAction.checkoutOptions = "";
    productAction.checkoutStep = 1;
    productAction.transactionAffiliation = "";

   Promotion definitions:
    ACTION_CLICK    Action to use when the user clicks/taps on a promotion.
    ACTION_VIEW    Action to use when the user views a promotion.

    var promotion = {};
    promotion.id = "PROMO-ID1234";
    promotion.name = "mypromo";
    promotion.position = "position";
    promotion.creative = "creative";
*/
window.ga.addImpression(screamName, product)
window.ga.productAction(screamName, product, productAction); // check Product Action definitions
window.ga.checkout(screamName, product, productAction); // check Product Action definitions; this could be implemented in the method productAction
window.ga.addPromotion(promotion, 'ACTION_CLICK'); // I have to double check this, TODO

**Comment by spacepope** [comment]
I looked inside the Windows SDK code:
it seems that enhanced ecommerce classes are already present and ready to use, like Product, Promotion, ProductAction (see https://github.com/dotnet/windows-sdk-for-google-analytics/tree/master/src/Native/GoogleAnalytics.UWP/Ecommerce) and the corresponding methods on the HitBuilder like AddProduct, AddPromotion, SetProductAction and SetPromotionAction (see https://github.com/dotnet/windows-sdk-for-google-analytics/blob/master/src/Native/GoogleAnalytics.UWP/HitBuilder.cpp lines 171 ff.)

The only thing i didn't see is Impression and the corresponding AddImpression method. If this is needed, a PR has to be made to the Windows SDK.. But i am afraid there isn't a lot of attention to this project, my last PR is still unanswered :/

**Comment by victorsosa** [comment]
@spacepope thanks for you feedback.

Sure give them sometime to merge the PR. The impression is needed so a PR will needed too.

**Comment by spacepope** [comment]
If you're finished on the Android part, give me a note, so i can look if i can make the corresponding changes on the Windows platform..

**Comment by victorsosa** [comment]
I haven't even started the change; you can start and summit the PR any time you want ( I have been busy this days )

**Comment by victorsosa** [comment]
I have created a branch just for this change 'ecommerce' in that branch pusinh all the code; you will need to push you code to that branch too.

**Comment by victorsosa** [comment]
OK, I complete the code changes for Android and it is ready for test. On the branch ecommerce.

**Comment by victorsosa** [comment]
I add some documentation on the readme file

**Comment by spacepope** [comment]
Started working on this. Need some more time, more bugs on Windows SDK discovered..

**Comment by sitexw** [comment]
Hello, I wanted to know where in summer the e-commerce branch (https://github.com/danwilson/google-analytics-plugin/tree/ecommerce) ?
Can I use it in production ?

**Comment by victorsosa** [comment]
@sitexw you can use it; and let us know if the new ecommerce api is working; we haven't fully tested it yet.
