### ISSUE TITLE
It takes too long to start tracking or track any activity at all

### ISSUE THREAD

**Issue by faustoct** [danwilson/google-analytics-plugin#454]
It takes more than 15seconds to google analytics start tracking . How to make it happens immediately ?

**Comment by ali-mahmoodvand** [comment]
I'm change my java codes
```
GoogleAnalytics.getInstance(this.cordova.getActivity()).setLocalDispatchPeriod(1);
GoogleAnalytics.getInstance(this.cordova.getActivity()).reportActivityStart(this.cordova.getActivity());
```
but again not working for me :(

**Comment by faustoct** [comment]
Solution anyone ?

**Comment by ali-mahmoodvand** [comment]
please help us

**Comment by faustoct** [comment]
Anything can we try ? I don't have much time to investigate what's going on. I got a message on xcode running on ios that's take too long . Since I need it working perfectly I'm gonna invest some time on it and having any progress I can share here. If anyone have something to share pls do it.. so can save us tons of time.

**Comment by spacepope** [comment]
The underlying tracker instance is collecting submitted hits for a predefined dispatch time and then sending them all together.
Have you tried to initiate the tracker with a shorter dispatch time as suggested in the readme?
>//In your 'deviceready' handler, set up your Analytics tracker:
>window.ga.startTrackerWithId('UA-XXXX-YY', 30)
>//where UA-XXXX-YY is your Google Analytics Mobile App property and 30 is the dispatch period (optional)

so starting your tracker with ```window.ga.startTrackerWithId('UA-XXXX-YY', 0)``` should result in hits getting send immediately.

**Comment by spacepope** [comment]
Allthough i think Google Analytics is not the right tool if you want to achieve some kind of real time measurements..

**Comment by spacepope** [comment]
Ah, okay, as described in the docs https://developers.google.com/analytics/devguides/collection/ios/v3/dispatch
if you disable dispatching by choosing a dispatch period of 0, one has to manually trigger the dispatch.
You can do this with ```window.ga.dispatch()```, but it seems that you have to do it after each hit tracked.
Alternatively try a dispatch period of 1 second, if this fits your needs..

**Comment by faustoct** [comment]
@spacepope  Thanks for replying. I tried something like `window.ga.startTrackerWithId('UA-XXXX-YY', 5)` . I'm gonna have a look at `dispatch` and what you've recommended here ! Any progress I update this thread.

**Comment by faustoct** [comment]
@spacepope I already tried to use `dispatch` and it didn't work . I'm gonna have a look again !

**Comment by faustoct** [comment]
@spacepope  just does not get any tracking on google analytics at all. When navigate between screens the google analytics does not get updated, also it takes too long to get start tracking when open the app.

**Comment by faustoct** [comment]
I move away to firebase . By the way it reports a bit different of google analytics plugin.
