### ISSUE TITLE
Ionic 3/android  : startTrackerWithId reports that the plugin is not installed

### ISSUE THREAD

**Issue by jjmahe** [danwilson/google-analytics-plugin#455]
I am using ionic 3 and this was not a problem in ionic 2.
When debugging on android, the _startTrackerWithId_ reports a "plugin not installed" error.
I have followed the README instructions, without a better result (order in the import, include in platform ready function).
plugin is called from a provider.
Everything is at the latest version 
cordova-plugin-actionsheet 2.3.1 "ActionSheet"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.4 "Console"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-device-motion 1.2.3 "Device Motion"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-shake 0.5.4 "Shake Gesture Detection"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-vibration 2.1.2 "Vibration"
cordova-plugin-whitelist 1.3.0 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"

**Comment by Xixiao007** [comment]
I also have Ionic 3.5.0, using GA for the first time today, it reached GA is ready now` in console (code below) in Android real device.
Have you installed google play service via SDKManager?

```
ga
        .startTrackerWithId("UA-103041111-1")
        .then(() => {
          console.log("GA is ready now");
          //the component is ready and you can call any method here
          ga.trackView("test");
          ga.debugMode();
          ga.setAllowIDFACollection(true);
        })
        .catch(err => console.error("Error starting GA", err));
    });
```

**Comment by jjmahe** [comment]
Ooooh thanks for the quick answer! I want to say that my impression is that the call, even if protected by Platform Ready, is not well enough protected, because at some points of the app upload, it is executed anyway. I have remove a lot of the app load time by the --prod argument, and I have to report a successful ga init, only after a while in the runtime, but errors on the non installed plugin are still fired. So, conclusion, there is nothing related to this plugin, but to the way platform ready is really delivering the expected app state.
