### ISSUE TITLE
addTransaction only working when wrapped in .startTrackerWithId('UA-XXXX-YY', 30) 

### ISSUE THREAD

**Issue by ashtonbach** [danwilson/google-analytics-plugin#459]
Hello, 

I am only able to track a transaction when wrapping it in the startTrackerWithId function. This is being used with Angular2 and Ionic2. Anyone else having the same issue?

Thanks,
David

**Comment by bodeme** [comment]
@ashtonbach Hi, how did you get the transactions running? I've got similar problems: https://github.com/danwilson/google-analytics-plugin/issues/474
