### ISSUE TITLE
How to get iPhone model in Google Analytics?

### ISSUE THREAD

**Issue by malwatte** [danwilson/google-analytics-plugin#462]
Hi,
Can not see device model for iOS devices. I can see device model only for Android devices.
I want to know the model of the iPhone (e.g. iPhone 6, iPhone 6 plus, iPhone 7, ....)

This is what I am seeing the Google Analytics.
![screen shot 2017-08-17 at 4 37 04 pm](https://user-images.githubusercontent.com/2534778/29409655-e495a00e-836a-11e7-8e40-a69d44df33b3.png)

Any help is appreciated.

Thanks,
Sachitra

Version: 1.5.6

**Comment by malwatte** [comment]
Helppppp! 
:)

**Comment by victorsosa** [comment]
You can create and use a custom dimension for this. I don't know any other way because for iOS seems like there didn't develop that in the API.

**Comment by malwatte** [comment]
This is how I track iPhone model now. Create custom dimension and use cordova device plugin.
`this.ga.addCustomDimension(1, this.device.model);`
1 is the index of the custom dimension
device is the cordova device plugin
You will get the identifier of the iOS device as shown here [](https://www.theiphonewiki.com/wiki/Models )
