### ISSUE TITLE
Android build fails: com.google.android.gms:play-services-analytics version need to be specified

### ISSUE THREAD

**Issue by peterpeterparker** [danwilson/google-analytics-plugin#464]
Hi,

Right now `com.google.android.gms:play-services-analytics:+` doesn't explicitly specify a version number for the library which lead to a gradle conflict while using `phonegap-plugin-push` 2.0.0

Would you be ok to modify following line of `plugin.xml`?

Instead of 

     <framework src="com.google.android.gms:play-services-analytics:+" />

Specifying the use of version 11.0.1

     <framework src="com.google.android.gms:play-services-analytics:11.0.1" />

This fix the conflict error.

Related issue `phonegap-plugin-push`: https://github.com/phonegap/phonegap-plugin-push/issues/1718

**Comment by macdonst** [comment]
@danwilson I'm working with the cordova-cli team to add the ability to include variables in the framework tag.

So right now you have:

```
<framework src="com.google.android.gms:play-services-analytics:+" />
```

and when it is done we can specify:

```
<preference name="PLAY_SERVICES" default="+"/>
<framework src="com.google.android.gms:play-services-analytics:$PLAY_SERVICES" />
```

but then users will be able to over-ride the play services version to match other plugins that depend on the same framework but pin a specific version.

I'll send a PR when it's ready.

**Comment by danwilson** [comment]
The android conflicts with other plugins using play services was one of the main reasons I handed over maintenance of this plugin... it became too much for me to manage. This looks like a good step forward in that - thanks!

**Comment by danwilson** [comment]
AND a huge thanks to @victorsosa who is maintaining this plugin (and has been for a good while now) and on top of all the issues and PRs.

**Comment by peterpeterparker** [comment]
@macdonst this enhancement gonna be possible with cordova-android 6.3.0, am I understanding correctly?

**Comment by macdonst** [comment]
@peterpeterparker yeah, I'm just waiting for cordova-android 6.3.0 to get released. Currently going through the voting process at Apache.

**Comment by behaghel** [comment]
@macdonst is #485 the equivalent PR you were planning to do? Are we in position to progress this issue?

**Comment by Moghul** [comment]
Did this ever turn into anything? I just installed this plugin to get around another analytics plugin with another problem. @peterpeterparker 's solution worked, but obviously it's not great. Should I be installing from github or somethingh?

**Comment by macdonst** [comment]
@behaghel yeah, that PR #485 was exactly what I would have submitted as well.

**Comment by Moghul** [comment]
Yeah, just tested with logcat, onMessageReceived doesn't get called when you tap the notification.

**Comment by victorsosa** [comment]
implmented by PR #509

**Comment by iPzard** [comment]
I wasn't using Google Maps.. I was using AdMob SDK though, maybe there was a conflict with that. 

I was not able to resolve this issue and ended up finding a way to add Google Analytics w/o the need for a third party plugin such as this one.

**Comment by spinninghamster** [comment]
@iPzard Would you mind sharing how you implemented Google Analytics without the plugin?

**Comment by BhavikaP** [comment]
@iPzard Please can you share how you implemented GA without a plugin. As I am having issues with GA and Push plugin. Your help will be greatly appreciated. Thanks

**Comment by iPzard** [comment]
@BhavikaP and @spinninghamster (sorry for the late reply Spinning). I don't remember the specifics. However! What I can do is post my exact code. Replace "UA-XXXXXXXXX-X" with your own code ID and it should for you as well. This was a real pain for me when originally researching, so I hope this helps you guys avoid that trouble! Let me know how it goes, if you still can't get it, I'll dig a little deeper to see if there's anything else. 

<script>
        window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
        var GA_LOCAL_STORAGE_KEY = 'ga:clientId';
        ga('create', 'UA-XXXXXXXXX-X', {
          'storage': 'none',
          'clientId': localStorage.getItem(GA_LOCAL_STORAGE_KEY)
        });
        ga(function(tracker) {
          localStorage.setItem(GA_LOCAL_STORAGE_KEY, tracker.get('clientId'));
        });
        ga('set', 'checkProtocolTask', null);
        ga('send', 'pageview');
</script>

**Comment by peterpeterparker** [comment]
@BhavikaP @spinninghamster @BhavikaP just in case, I don't have the reference right here, but if I remember correctly my tests, I think that using the GA plugin is kind of a must if you ship you app on Android thru Google Play

You could implement the Javascript solution instead of the plugin, you will not face any compilation or runtime errors but you might then face the problem that events and page name triggered to GA will not be catch and displayed by GA with proper names, proper identification. Instead of these you might end up finding in your GA console long hash keys values instead of effective information you defined

**Comment by iPzard** [comment]
@peterpeterparker yeah, glad to help :).. It's much easier for people to just add the plugin too. I'd say that is just a last resort tactic. Something is better than nothing.

**Comment by BhavikaP** [comment]
@iPzard Thank you for the GA implementation without plugin. Will apply it and see how I go.

**Comment by iPzard** [comment]
@BhavikaP Glad to help :).. Let me know how it goes!

**Comment by BhavikaP** [comment]
@iPzard Added the code as mentioned above. But can't see any Realtime stats in GA. The GA account was setup for Application type Android - would that matter?

**Comment by iPzard** [comment]
@BhavikaP It won't be in real time. Google Analytics has somewhat of a delay. You should be able to see your stats tomorrow though (I know that kind of sucks).

**Comment by BhavikaP** [comment]
@iPzard It worked perfectly. Thank you so much. Much appreciated.

**Comment by iPzard** [comment]
@BhavikaP Sweet! No problem, glad it's up and running!
