### ISSUE TITLE
Can't Solve 'undefined' error

### ISSUE THREAD

**Issue by howardowens** [danwilson/google-analytics-plugin#469]
I read prior threads on this, but still can't solve the problem.

The plugin is installed.

I'm not using a framework.  I've tried the code below right after device ready on my main.js file and as the last lines of code within document ready at the bottom of main.js.

After I install the app on test device and check the console, I can console "analytics" and get an object back.

This code below shows `undefined` and `Google Analytics plugin could not be loaded.`
```
//google analytics 
console.log("first check for analytics: " + analytics);

  if (typeof analytics !== 'undefined') {
    analytics.startTrackerWithId('UA-xxxxxxx-x');
    analytics.setUserId(device_id);
    console.log("Analytics: " + analytics);
  } else {
    console.log("Google Analytics plugin could not be loaded.")
  }
```

**Comment by racingsolution** [comment]
I'm having the same problem... I've used this plugin in the past without any issues.. for some reason it's not working for either of my projects anymore.  It does work in the browser platform.. but when I build the app with it, window.ga is always undefined.

**Comment by howardowens** [comment]
I found a way to implement GA without a plugin so for me, in a way, this issue is resolved.

**Comment by racingsolution** [comment]
So strangely enough, despite window.ga saying it is undefined, my trackView calls started working and showing up on the real time screen.

**Comment by victorsosa** [comment]
please check issue #477
