### ISSUE TITLE
arm64 Support

### ISSUE THREAD

**Issue by jorgedavila25** [danwilson/google-analytics-plugin#47]
I have an Xcode 6 and Cordova 3.6 project, and I just updated this plugin to the latest with hopes that it will support arm64 architecture. When I remove "arm64" from Valid Architectures, it works, but when I add "arm64" i get this error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GAI", referenced from:
      objc-class-ref in UniversalAnalyticsPlugin.o
  "_OBJC_CLASS_$_GAIDictionaryBuilder", referenced from:
      objc-class-ref in UniversalAnalyticsPlugin.o
  "_OBJC_CLASS_$_GAIFields", referenced from:
      objc-class-ref in UniversalAnalyticsPlugin.o
  "_kGAIScreenName", referenced from:
      -[UniversalAnalyticsPlugin trackView:] in UniversalAnalyticsPlugin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am i doing something wrong, or is this plugin not compatible with arm64? 

Thanks!

**Comment by Tankwacht** [comment]
@jorgedavila25 - Can you explain what you did? I am facing the same problem... :/

**Comment by botweb** [comment]
@jorgedavila25 Please describe to us, what you did to get it working. I'm also facing this problem.
