### ISSUE TITLE
trackView not working in Android (works on iOS) version 1.8.3

### ISSUE THREAD

**Issue by royken** [danwilson/google-analytics-plugin#473]
Hello,
I'm using the plugin on an Ionic1 app, and its working great on iOS, I can see the activity in the Google Analytics dashboard for realtime data. But its not doing anything in Android. Exact same code. No evident errors on logcat. I'm using the 1.8.3 version and following this [link](http://ngcordova.com/docs/plugins/googleAnalytics/)
```
$cordova plugin ls
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
```
This is how I use the plugin:
```
$cordovaGoogleAnalytics.debugMode();
$cordovaGoogleAnalytics.startTrackerWithId('UA-XXXXXXXXX-1');
$cordovaGoogleAnalytics.setUserId(USER_ID);
$cordovaGoogleAnalytics.trackView('Page_Title');
```

![image](https://user-images.githubusercontent.com/7059358/31117645-850ceade-a822-11e7-8ad1-17c7922a4e07.png)

System Info:
Cordova CLI: 6.5.0
 ```

Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.11.1
```

**Comment by nncl** [comment]
@royken I think it's related to [this one](https://github.com/danwilson/google-analytics-plugin/issues/420#issuecomment-306180827)

**Comment by royken** [comment]
@nncl Thank you,
I did exactly what he said, but nothing shows. When I open logcat this is what I have:
![github](https://user-images.githubusercontent.com/7059358/31555833-708e63ba-b03a-11e7-85cf-6d834a0b4d73.PNG)

**Comment by boboldehampsink** [comment]
I'm seeing the same problem. The plugin works on iOS and on Android >= 7.0 but not on 6 and lower.

**Comment by victorsosa** [comment]
plase check issue #477
