### ISSUE TITLE
Question: Change ID on the fly

### ISSUE THREAD

**Issue by danielcrk** [danwilson/google-analytics-plugin#478]
Hi, and thanks so much for this plugin!

My app can switch between production and test API's on the fly, and I'd like to track events to different accounts depending on the API.

TLDR; Is it possible to run window.ga.startTrackerWithId('UA-xxxxxxxx-x'); after it has already been started, to change the GA account ID on the fly?

Thanks!

**Comment by victorsosa** [comment]
YES, just start it again
