### ISSUE TITLE
ga.trackView doesn't work for me on IOS

### ISSUE THREAD

**Issue by kingaryan** [danwilson/google-analytics-plugin#479]
Hi, 
I'm building Angular 2 app, and I used cordova plugin for google analytics. I can see that the google analytics can recognize the devices that I'm using but I cant see which pages I'm hitting. I used ga.trackView view but nothing happened. Could someone please  help me figure out the issue?

**Comment by danielvivek2006** [comment]
Please answer this. @danwilson

**Comment by jsdussanc** [comment]
Please help me with this

**Comment by victorsosa** [comment]
please check issue #477
