### ISSUE TITLE
[Question] Same account for  Web and App

### ISSUE THREAD

**Issue by theavijitsarkar** [danwilson/google-analytics-plugin#481]
Currently I have setup two properties one for web and one for mobile

This is how i start 
```

        if (md.mobile() || md.tablet()) {
            window.ga.startTrackerWithId('UA-4037XXXX-1')
        } else {
            window.ga.startTrackerWithId('UA-4037XXXX-2')
        }

```

My code is same for browser and phones. Is this the right way to do this? The problem is now I have two separate analytics, and merging the data is not possible, I have to track on both accounts, which is a huge pain.

Can you suggest if there is a way to do this with only one property?

**Comment by victorsosa** [comment]
you can only track one ID with this plug-in right now

**Comment by victorsosa** [comment]
mobile and tablet data are separate by google analitycs on the web page; don't need to do this code.
