### ISSUE TITLE
Mobile app property -> Firebase only

### ISSUE THREAD

**Issue by kaiserdan** [danwilson/google-analytics-plugin#489]
As of lately, Google Analytics refers to Firebase as the only way to track mobile apps. See the screenshot at https://forum.ionicframework.com/t/was-google-analytics-replaced-by-firebase/93556 for an example.

Does adding a regular GA Website Property ID work with the plugin, is there a way to set Firebase ID, or is the plugin therefore dysfunctional atm?

Thank you anyway for creating the plugin!

**Comment by ammichael** [comment]
I also have this problem. I tried creating as a website, but it doesn't seem to work. Have you found a way to analytics in Ionic apps?

**Comment by bigreni** [comment]
Refer to #466 for the solution. You need to set up a new view of your website and select Mobile app.
