### ISSUE TITLE
Analytics is not show the screen name is not shown properly (ionic; production)

### ISSUE THREAD

**Issue by minhui27** [danwilson/google-analytics-plugin#491]
The screen name is not shown properly when the ionic app is build in production mode. The screen name always displayed as 'n', 't', 'l', or 'e', instead of display as 'Homepage' or any the other readable screen name.

![ga-screen2](https://user-images.githubusercontent.com/18694106/34923839-51d646f6-f9da-11e7-902d-44487acb1e25.JPG)

**Comment by AndrWeisR** [comment]
I don't see this in my production app (using version 1.8.3 of the plugin and Ionic 3). I get full page names

**Comment by victorsosa** [comment]
It can't be duplicated
