### ISSUE TITLE
No crash reporting??

### ISSUE THREAD

**Issue by PhamPhong1412** [danwilson/google-analytics-plugin#493]
I'm using google analytic v4 in unity, i can't not find crash&exception section. Please help, thanks!!

![screen shot 2018-01-30 at 10 55 35 am](https://user-images.githubusercontent.com/12563569/35547529-21c29fe0-05ac-11e8-9cce-58cdacc16119.png)

**Comment by victorsosa** [comment]
please check Google analitycs documentation for that
