### ISSUE TITLE
"Missing Command Error" on Windows 10 UWP

### ISSUE THREAD

**Issue by VictorAssis** [danwilson/google-analytics-plugin#496]
I'm trying to use this plugin with Ionic 3.x in Windows Phone (on Android works fine), but i get the error "Error starting GoogleAnalytics Missing Command Error" in the Javascript Console on Visual Studio. Here are the steps I'm following:

1. On terminal: `ionic cordova build windows`
2. Open the Visual Studio 2015 project;
3. Open the Package Manager Console (Tools > NuGet Package Manager > Package Manager Console);
4. Execute the command `Install-Package UWP.SDKforGoogleAnalytics.Native -Version 1.5.2`
5. Run the project in device clicking on "Play" button.

Is there a step missing?

ionic info:
```
cli packages: (C:\Users\user\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 windows 5.0.0
    Ionic Framework    : ionic-angular 3.6.0
System:
    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10
Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : legacy
```

**Comment by spacepope** [comment]
Hi @VictorAssis 
that sounds like you don't have the correct plugin version. You can verify this by looking into the plugin folder under `plugins/cordova-plugin-google-analytics` and check if there is a `windows` folder.
If not, please try to install it from github with `cordova plugin add https://github.com/danwilson/google-analytics-plugin.git --save`. (the latest npm version doesn't seem to have Windows UWP support included yet..)

**Comment by victorsosa** [comment]
version 1.8.4 release
