### ISSUE TITLE
crashes app after installed google-analytics-plugin

### ISSUE THREAD

**Issue by anuj-njoshi** [danwilson/google-analytics-plugin#499]
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.google.firebase:firebase-core:9.0.0
cordova.system.library.3=com.google.firebase:firebase-messaging:9.0.0
cordova.gradle.include.1=cordova-plugin-fcm/app-FCMPlugin.gradle
cordova.gradle.include.2=com-sarriaroman-photoviewer/app-photoviewer.gradle
cordova.system.library.4=com.android.support:support-v4:26.+
cordova.system.library.5=com.android.support:appcompat-v7:26.+
cordova.system.library.6=com.android.support:support-v4:+
cordova.system.library.7=com.google.android.gms:play-services-analytics:9.0.0
Default version of gms is 9.0.0

**Comment by victorsosa** [comment]
no info of the issue
