### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by wallstudios** [danwilson/google-analytics-plugin#504]
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"

Tried doing an android build today and got the following error.

> Error: more than one library with package name 'com.google.android.gms.license'

Did a quick search and found this fix.
changed to: 11.+ from previously: +
In plugin.xml

I changed 
    <framework src="com.google.android.gms:play-services-analytics:+" />
to
    <framework src="com.google.android.gms:play-services-analytics:11.+" />

and it now works.
Not sure if this is going to be an ongoing issue or not.

**Comment by victorsosa** [comment]
merged PR #502

**Comment by FME-Daniel** [comment]
@victorsosa can we get a version bump to get that fix out in the wild?

**Comment by SpellChucker** [comment]
yes please, let's get a version bump. It's annoying having to go into `project.properties` every time we re-add platforms and update the versions there.

**Comment by victorsosa** [comment]
fixed on v1.8.4
