### ISSUE TITLE
AdMob and Google Analytics plugins can't run at the same project

### ISSUE THREAD

**Issue by coolman7** [danwilson/google-analytics-plugin#513]
Hello,
I want to use AdMob Free and Google Analytics native plugins at the same Ionic 3 project. I can use only AdMob or only Google Analytics at my project without any problem. But when I use both of plugins, my app crashes with "Sorry app has failed" error message:

https://ionicframework.com/docs/native/admob-free/
https://ionicframework.com/docs/native/google-analytics/

Any idea how to solve this problem?

Thanks

Here is my ionic configuration:
```
$ ionic info
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 8.0.0 

local packages:
    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0 browser 5.0.3
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 26.1.1
    Node              : v8.10.0
    npm               : 3.5.2 
    OS                : Linux 4.15

Environment Variables:
    ANDROID_HOME : /opt/Android/Sdk/

Misc:
    backend : pro
```

**Comment by sametcetin06** [comment]
+1

**Comment by victorsosa** [comment]
ok, but what is the log error?

**Comment by victorsosa** [comment]
more info needed

**Comment by victorsosa** [comment]
this could be related to the issue #464

**Comment by coolman7** [comment]
I fed up the problems of hybrid mobile programming and switched to native java programming for android. So I can't give you more details. I hope anyone who faces same problem would like to give more details.
