### ISSUE TITLE
Ionic App iOS Build error with google analytics

### ISSUE THREAD

**Issue by hptumovil** [danwilson/google-analytics-plugin#520]
I have the next error when I try to compile

/Users/projectName/platforms/ios/HPTUMovil/Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:3:9: fatal error: module 'Firebase' not found
@import Firebase;
 ~~~~~~~^~~~~~~~
1 error generated.

I need help with this, please.

**Comment by victorsosa** [comment]
this is not related to this plugin
