### ISSUE TITLE
Cannot add version 1.8.4

### ISSUE THREAD

**Issue by malwatte** [danwilson/google-analytics-plugin#523]
I did `ionic cordova plugin add cordova-plugin-google-analytics`
Version in package.json says 1.8.4, but plugin.xml does not have the variable GMS_VERSION.

So I tried `ionic cordova plugin add https://github.com/danwilson/google-analytics-plugin.git` to get the latest version from git. Now the version and plugin.xml is correct. But `ionic cordova prepare` fails with the error,
`Failed to restore plugin "cordova-plugin-google-analytics" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/danwilson/google-analytics-plugin.git via registry.`

How to get the 1.8.4?

**Comment by victorsosa** [comment]
you are right, sorry my mistake during the merge

**Comment by victorsosa** [comment]
NOW it is working

```
BUILD SUCCESSFUL
 in 30s

2 actionable tasks: 2 executed

Subproject Path: CordovaLib
Adding cordova-plugin-google-analytics to package.json

Saved plugin info for "cordova-plugin-google-analytics" to config.xml
```

please add the latest version

**Comment by malwatte** [comment]
Thank you for the quick response. I'll add it again.
