### ISSUE TITLE
Google analytics - Firebase mobile

### ISSUE THREAD

**Issue by MumblesNZ** [danwilson/google-analytics-plugin#528]
Hello,

From what I can tell, it looks like google has changed the analytics portion of their website so now you can't create a mobile app and get a ID UA-XXXXX as normal, as they force you to use their firebase analytics engine for mobile instead. 

Has anyone got a workaround for this? Are people just registering their apps as websites? 

Thanks

**Comment by victorsosa** [comment]
Hello,
Yes you can just registering their apps as websites and use it the Google analytics

**Comment by MumblesNZ** [comment]
Ok thanks
