### ISSUE TITLE
Add support for platform browser

### ISSUE THREAD

**Issue by sgimeno** [danwilson/google-analytics-plugin#53]
Cordova CLI 4.0.0 adds support for the `browser` platform. How should this plugin handle this platform? Is it possible to bind the analytics JS browser library methods to the plugin? ie:

```
var ga = require('analytics.js');
...
startTrackerWithId: function(trackerId){
    ga('create', trackerId, 'auto');
}
...
```

This was my first thought when facing the issue, what do you think? Are there any side-effects I haven't noticed? Any other approaches?

**Comment by kcampion** [comment]
+1

**Comment by adyz** [comment]
+1

**Comment by gaboesquivel** [comment]
:+1:

**Comment by gilesa** [comment]
+1

**Comment by joekukish** [comment]
Is there any update on this issue? This would enable to do PWA with the same code base.

**Comment by morrisonbrett** [comment]
+1

**Comment by oliviertassinari** [comment]
I have managed to solve this issue by using a higher abstraction layer.
The major hardness is by passing the
`document.addEventListener('deviceready'` limitation of the cordova API.
The browser API provided by Google queues requests.

Le sam. 10 sept. 2016 à 02:39, Brett Morrison <notifications@github.com> a
écrit :

**Comment by victorsosa** [comment]
PLease check https://github.com/apache/cordova-browser this is the cordova platform target for browser

**Comment by victorsosa** [comment]
Here is a guide on how to implement browser support for a plugin:
http://moduscreate.com/supporting-the-browser-platform-in-a-cordova-plugin/

**Comment by victorsosa** [comment]
PR #313 created to browser support - dev is not complete yet

**Comment by victorsosa** [comment]
Is here, release 1.7.0
