### ISSUE TITLE
Can't download v1.8.6 - startTracker() error

### ISSUE THREAD

**Issue by henriqueruss** [danwilson/google-analytics-plugin#530]
Hello, I'm trying to download v1.8.6 using cordova but without success. 

When I downloaded v1.8.5 presents error during build in startTracker() function.

`private void startTracker(String id, int dispatchPeriod, CallbackContext callbackContext) {
        this.cordova.getActivity().getThreadPool().execute(new Runnable() {
            public void run() {
                if (null != id && id.length() > 0) {
                    tracker = GoogleAnalytics.getInstance(this.cordova.getActivity()).newTracker(id);
                    callbackContext.success("tracker started");
                    trackerStarted = true;
                    GoogleAnalytics.getInstance(this.cordova.getActivity()).setLocalDispatchPeriod(dispatchPeriod);
                } else {
                    callbackContext.error("tracker id is not valid");
                }
            }
        });
    }
`

Apparently the error was fixed in v1.8.6 changing the function to:

`private void startTracker(String id, int dispatchPeriod, CallbackContext callbackContext) {
        if (null != id && id.length() > 0) {
            tracker = GoogleAnalytics.getInstance(this.cordova.getActivity()).newTracker(id);
            callbackContext.success("tracker started");
            trackerStarted = true;
            GoogleAnalytics.getInstance(this.cordova.getActivity()).setLocalDispatchPeriod(dispatchPeriod);
        } else {
            callbackContext.error("tracker id is not valid");
        }
    }`

But I can't download it. I noticed yout package.json still present v1.8.5, any chances of the problem ocurs becouse that?

Thank you for the attention.

Ionic Info:
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0
local packages:
    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.1.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v8.11.3
    npm               : 5.6.0
    OS                : Windows 10

**Comment by spinninghamster** [comment]
I can confirm I have the same issue.

`window.analytics.startTrackerWithId('XXXXX');` is never being called. Which one is the last version working for you?

**Comment by victorsosa** [comment]
please download the new version 1.9.0
