### ISSUE TITLE
Error on iOS using getVar. App crash

### ISSUE THREAD

**Issue by pedrovr-** [danwilson/google-analytics-plugin#538]
I have problems with the plugin getting a variable from the tracker in iOS, the app crashes without giving an error. 

I've been debugging the error and I fixed it by updating the Google Analytics SDK libraries to the latest, because the real problem was in the tracker implementation. Would you accept a PR to change libraries or change them by yourself?

**Comment by pedrovr-** [comment]
I've created PR #539 to update SDK libraries for iOS to version 3.17. This version fix some bugs on the SDK.

**Comment by victorsosa** [comment]
release 1.9.0
