### ISSUE TITLE
Unset userId

### ISSUE THREAD

**Issue by rosshadden** [danwilson/google-analytics-plugin#54]
It doesn't look like there is a way to unset the `userId` once set.  Does setting it to an empty string or null perhaps achieve the same thing?

**Comment by Yonet** [comment]
They are not very clear on the documentation page. This is from the support:

The Google Analytics User ID policy requires that you stop tracking user ID once a user signs out of your website. So, you'll need to unset the user ID if the user signs out.

https://support.google.com/tagmanager/answer/4565987
