### ISSUE TITLE
1.8.6 Not working on android

### ISSUE THREAD

**Issue by bw7432** [danwilson/google-analytics-plugin#540]
Work perfectly on IOS but it does not send anything to Google Analytics on Android. Plugin version 1.8.6.

**Comment by malwatte** [comment]
I had this issue in 1.8.6 and I changed the gms version to 16.0.3 and it started to work.

`cordova plugin add cordova-plugin-google-analytics --variable GMS_VERSION=16.0.3`

Check other plugins and change the GMS_VERSION version accordingly

**Comment by bw7432** [comment]
@spinninghamster - 1.8.3 DOES WORK! Thank you so much.
