### ISSUE TITLE
Firefox blocking Google Analytics requests

### ISSUE THREAD

**Issue by ThorvaldAagaard** [danwilson/google-analytics-plugin#543]
I the console I can see the following on a firefox browser:
```
ERROR Error: "Uncaught (in promise): Error: send timeout
send/</timeout<@https://<website>/plugins/cordova-plugin-google-analytics/browser/UniversalAnalyticsProxy.js:184:13
```

This is caused by the browser making tracking protection

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

It looks like the recommended way is to check if ga has been loaded using code like this

```
var trackOutboundLink = function(url) {
    // check if the GA object exists and that it has initialized
    if(window.ga && ga.loaded) { {
        // if yes, rely on GA to follow link
        ga('send', 'event', 'outbound', 'click', url, {
            'transport': 'beacon',
            'hitCallback': function(){document.location = url;}
        });
    } else {
        // if not, follow link ourselves
        document.location = url;
    }
}
```

Is it possible to included this check in the plugin?

I know I can allow tracking in my browser, but I can't force users to allow tracking

**Comment by spinninghamster** [comment]
This is only happening on Firefox OS, right?

**Comment by ThorvaldAagaard** [comment]
Yes, and only when a user disallows tracking

**Comment by victorsosa** [comment]
Firefox blocking tracking feature; issue close
