### ISSUE TITLE
Problem occurring while applying com.android.application

### ISSUE THREAD

**Issue by ArkageTeam** [danwilson/google-analytics-plugin#545]
Dear all,

we do hope you will be able to assist us installing the plugin as we are stuck since two weeks trying to solve below issue upon compiling our app in android studio.

> * What went wrong:
> A problem occurred evaluating root project 'android'.
> > Failed to apply plugin [id 'com.android.application']
>    > Minimum supported Gradle version is 4.6. Current version is 4.1. If using the gradle wrapper, try editing the distributionUrl in /Users/Fabio/localhost/mst/gradle/wrapper/gradle-wrapper.properties to gradle-4.6-all.zip

We seem not to be able to update correctly Gradle: therefore, first of all, is there anyone so kind to share with us a tutorial about upgrading it.
Whatever we try, downloading 4.6 up to 4.9, the message keeps reporting 4.1 is too low.

Thank you and best
Arkage Team

**Comment by victorsosa** [comment]
not related to this project
