### ISSUE TITLE
Unable to install plugin on IBM MobileFirst Cordova

### ISSUE THREAD

**Issue by chunhoong** [danwilson/google-analytics-plugin#547]
Hi,

I have problem to install this plugin. I am using IBM MobileFirst Cordova, which is essentially Cordova 5.0.0 with cordova-android 3.6.4.

![image](https://user-images.githubusercontent.com/12269078/48115302-7413d600-e29d-11e8-8515-90cfa955f3ee.png)

I tried again by installing using -dd flag, this time I am able to observe this error:
![capture](https://user-images.githubusercontent.com/12269078/48115612-74f93780-e29e-11e8-850c-1b0b124072a0.PNG)

which still returns `No plugin added. Use 'mfp cordova plugin add'`,
when I am checking my installed plugins using `mfp cordova plugin ls`.

**Comment by victorsosa** [comment]
this is a communication issue: CERT_UNTRUSTED you need to check with mfp developer
