### ISSUE TITLE
Ionic4 Blank App + GoogleAnalytics TypeError

### ISSUE THREAD

**Issue by medoix** [danwilson/google-analytics-plugin#549]
Blank "SideMenu" project with only this plugin installed throws the following in the browser after a successfull compile by ionic itself.

`TypeError: Object(...) is not a function[Learn More] index.js:497:8
./node_modules/@ionic-native/google-analytics/index.js/GoogleAnalytics<
index.js:497:8
./node_modules/@ionic-native/google-analytics/index.js
index.js:50
__webpack_require__
bootstrap:83
./src/app/app.component.ts
http://localhost:8100/main.js:1682:88
__webpack_require__
bootstrap:83
./src/app/app.module.ts
http://localhost:8100/main.js:1777:72
__webpack_require__
bootstrap:83
./src/main.ts
main.ts:1
__webpack_require__
bootstrap:83
0
http://localhost:8100/main.js:1882:18
__webpack_require__
bootstrap:83
checkDeferredModules
bootstrap:45
webpackJsonpCallback
bootstrap:32
<anonymous>
http://localhost:8100/main.js:1:57
`

**Comment by DragonAK** [comment]
Same for me. Just going with cordova-plugin-firebase instead.

**Comment by medoix** [comment]
Closing as likely out of date now.
