### ISSUE TITLE
How can we enable Google Analytics Demographics and Interest Reports

### ISSUE THREAD

**Issue by paishin** [danwilson/google-analytics-plugin#55]
When going into Google Analytics Demographics and Interest Reports I get a message that my tracking code does not provide the necesary support for the Demographics and Interest Reports.

**Comment by mediavrog** [comment]
+1

**Comment by denvazh** [comment]
+1

**Comment by yongyu-lee** [comment]
+1 Thanks

**Comment by Jwata** [comment]
+1

**Comment by tannerlinsley** [comment]
+1 This would be great to have.

**Comment by DaniloOliveira28** [comment]
+1

**Comment by wallstudios** [comment]
I have a request for this as well. Any update?

**Comment by demege** [comment]
+1 This would be great to have.

**Comment by vlaraort** [comment]
+1 to this. Are there any news?

**Comment by shmuel-krakower** [comment]
+1

**Comment by souly1** [comment]
+1

**Comment by maiskovich** [comment]
+1
In which state is this?Is it possible to help with the implementation?what is needed?

Toda raba

**Comment by antonfire** [comment]
Any news on this feature?

**Comment by barocsi** [comment]
+1?

**Comment by victorsosa** [comment]
Added to the API, thanks all.
