### ISSUE TITLE
Cannot find name 'GoogleAnalytics'

### ISSUE THREAD

**Issue by leaditnet** [danwilson/google-analytics-plugin#553]
on ionic, the compiler cannot see the type GoogleAnalytics as tried to apply the code in constructor
constructor(public platform: Platform,private ga: GoogleAnalytics )

instead it is able t o see GoogleAnalyticsOriginal which is also gives error on runtime.

Anybody has solution, I tried on 
 ionic (Ionic CLI)  : 4.5.0 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 15 other plugins)
System:
   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.5.0
   OS     : Windows 10

**Comment by mugwhump** [comment]
Yup, same issue here. I get the feeling we're not actually supposed to be using GoogleAnalyticsOriginal, but that's the only way I could get the error "Cannot find name 'GoogleAnalytics'" to go away.

But when I use GoogleAnalyticsOriginal, I get
> Encountered undefined provider! Usually this means you have a circular dependencies (might be caused by using 'barrel' index.ts files.

**Comment by leaditnet** [comment]
Hi I got the answer here  https://stackoverflow.com/a/54422357/4178475 as follow

You installed the latest @ionic-native/google-analytics (v5+).
Then you should import GoogleAnalytics from @ionic-native/google-analytics/ngx

import { GoogleAnalytics } from '@ionic-native/google-analytics/ngx';
Or else install @ionic-native/google-analytics with v4+, then you can import GoogleAnalytics from  @ionic-native/google-analytics

import { GoogleAnalytics } from '@ionic-native/google-analytics'

**Comment by Harika511** [comment]
Yes it works import { GoogleAnalytics } from '@ionic-native/google-analytics/ngx';

**Comment by supasheva** [comment]
Thank you. This helped me
