### ISSUE TITLE
Ionic 4 error

### ISSUE THREAD

**Issue by dodomui** [danwilson/google-analytics-plugin#560]
I'd like to setup Google Analytics for Ionic 4.
While I try to declare in app.module.ts providers: [GoogleAnalytics].
Receive below error

<code>compiler.js:2430 Uncaught Error: Invalid provider for the NgModule 'AppModule' - only instances of Provider and Type are allowed, got: [?[object Object]?, ...]</code>

**Comment by victorsosa** [comment]
this is a angular provider configuration issue.
