### ISSUE TITLE
Creating a new Google Analytics website account for Cordova apps

### ISSUE THREAD

**Issue by manish2535** [danwilson/google-analytics-plugin#564]
Since its recommended we use this plugin to track as a "Website" and not "Mobile app" anymore (https://github.com/danwilson/google-analytics-plugin/issues/550#issuecomment-445539948) because of Google's recent announcement - https://support.google.com/analytics/answer/9167112?hl=en, my question is What do I put in the Website URL field when creating a new analytics profile?
![Screen Shot 2019-07-21 at 3 23 16 PM](https://user-images.githubusercontent.com/4663798/61596094-027e7c80-abcd-11e9-8b5c-140220b43a6c.png)

I have tried "none" but it complains saying "URL ends with an invalid top-level domain name". Do I put anything random in there like "dummyurl.com" to get the Tracking ID (UA-XXXXX-Y)?

**Comment by malwatte** [comment]
I used my web site URL and it is not relevant to the app at all. But still worked.

**Comment by manish2535** [comment]
Yeah i used localhost.com and it seems that value just doesnt matter. The tracking id is all that matters.
