### ISSUE TITLE
Fail to compile Project with ionic 4

### ISSUE THREAD

**Issue by tankejaures** [danwilson/google-analytics-plugin#571]
Hello please I have some problem when i compile project ionic 4;
In the project I use cordova FCM and google analytic plugin; This is error on console

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[16.0.
  0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-analytics-impl:16.0.1 -> com.google.android.gms:play-services-m
  easurement-base@[16.0.0], but play-services-measurement-base version was 16.5.0.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk@16.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-analytics-impl@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement@16.5.0
  -- Project 'app' depends onto com.google.firebase:firebase-analytics@16.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-analytics@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-v4-impl@16.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-base@16.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@16.5.0
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-sdk-api@16.5.0
  -- Project 'app' depends onto com.google.firebase:firebase-core@16.0.9
  -- Project 'app' depends onto com.google.android.gms:play-services-measurement-impl@16.5.0

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

Please I don't know what can i do to solve this problem
Please help me 
Thank's

**Comment by mybluedog24** [comment]
If you are using Capacitor, I just see that Cordova FCM is not compatible with Capacitor: https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins/
