### ISSUE TITLE
After Install Google Analytics App not build 

### ISSUE THREAD

**Issue by snaveenpandi** [danwilson/google-analytics-plugin#573]
[link](https://ionicframework.com/docs/v3/native/google-analytics/)
cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:
    cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)

local packages:
    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 8.1.0
    Ionic Framework    : ionic-angular 3.9.2

**Comment by victorsosa** [comment]
no error message was provided
