### ISSUE TITLE
clashes with other plugins / fails to compile

### ISSUE THREAD

**Issue by Edmu** [danwilson/google-analytics-plugin#575]
duplicate symbol '_OBJC_METACLASS_$_TAGUniversalAnalytics' in:
    ...platforms/ios/Pods/GoogleTagManager/Frameworks/GoogleTagManager.framework/GoogleTagManager(TAGUniversalAnalytics_398262d418b53042dc4e5b4d94f50e24.o)
    .../platforms/ios/.../Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGUniversalAnalytics.o)

In my cases it clashes with firebasex plugin. Someone already reported similar issue on that repo:

https://github.com/dpa99c/cordova-plugin-firebasex/issues/327

**Comment by HansKrywaa** [comment]
@victorsosa Is it possible to fix that? The Problem is described here: https://github.com/dpa99c/cordova-plugin-firebasex/issues/327#issuecomment-594818774

**Comment by Edmu** [comment]
@HansKrywaa If the clash is between firebasex and google-analytics plugins try using this build branch of firebasex https://github.com/dpa99c/cordova-plugin-firebasex/tree/cli_build it has some deps removed and does not conflict (yet) with google analytics plugin.

**Comment by victorsosa** [comment]
Using cocoa-pop plugin so the library stop been static it can be fixed. check issue #377
any PR is welcome.

**Comment by HansKrywaa** [comment]
PR created. Please give it a look @victorsosa

**Comment by victorsosa** [comment]
to be release on 1.9

**Comment by HansKrywaa** [comment]
when 1.9 will be published?

**Comment by victorsosa** [comment]
Done @HansKrywaa
