### ISSUE TITLE
Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020

### ISSUE THREAD

**Issue by khalilbenhassine** [danwilson/google-analytics-plugin#576]
the plugin must be updated for accounting with WKWEBVIEW always I had a message from apple for migration

https://github.com/apache/cordova-ios/issues/761

**Comment by victorsosa** [comment]
Any code fix is welcome

**Comment by HansKrywaa** [comment]
@khalilbenhassine i think this Plugin doesn't use UiWebView? Am i wrong?

**Comment by victorsosa** [comment]
yes base on the comment from apache/cordova-ios#761 this plugin is not the issue

**Comment by HansKrywaa** [comment]
Mhh in the Mentioned Comment the Plugin seems to be the Problem but u don't know why 🤷🏼‍♂️

**Comment by victorsosa** [comment]
erikyuzwa the author said that this plugin is not the problem

**Comment by HansKrywaa** [comment]
Yeah but after he re-added the Platform after the Plugin remove it worked then.

But doesn't matter as i included the Plugin too and don't get any warning when build to TestFlight so can't be that Plugin.

**Comment by khalilbenhassine** [comment]
okay thank you how i know which plugin uses uiwebview because i saw in the forms that analytics uses uiwebview?
