### ISSUE TITLE
Error during archiving

### ISSUE THREAD

**Issue by SebasWebDev** [danwilson/google-analytics-plugin#579]
Today I updated the version of the Cordova plugin (1.9.0) and I got the following error during archiving:
```
In file included from /path/to/my/app/platforms/ios/MyApp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.m:4:
--
02-Apr-2020 14:28:38 | /path/to/my/app/platforms/ios/myApp/Plugins/cordova-plugin-google-analytics/UniversalAnalyticsPlugin.h:6:9: fatal error: 'GoogleAnalytics/GAI.h' file not found
02-Apr-2020 14:28:38 | #import <GoogleAnalytics/GAI.h>
```

The fix was easy: use the version 1.8.6. But I wanted to let you know. This issue happened multiple times.

**Comment by rpragesh** [comment]
I am also having the same issue. did you got the solution??

**Comment by JuanManuelOyarzunDev** [comment]
Tengo la versión 1.9.0 y tengo el mismo error:
**cordova-plugin-google-analytics/UniversalAnalyticsPlugin.h:6:9: fatal error: 
      'GoogleAnalytics/GAI.h' file not found
#import <GoogleAnalytics/GAI.h>**

**Comment by sanjredfield** [comment]
Also experiencing the same issue

**Comment by tbergeron** [comment]
Anyone has an idea of what's happening with this plugin?

**Comment by MLuan** [comment]
I'm facing this same issue. 
Build using last version dosen't work on IOS. 
"GoogleAnalytics/GAI.h' file not found.

**Comment by rpragesh** [comment]
I am also facing the same issue. `"GoogleAnalytics/GAI.h' file not found.` can anyone please help with this ASAP

**Comment by KAIOAVILA** [comment]
adds GoogleAnalytics as a dependency on the Pods that work

**Comment by billb037** [comment]
@KAIOAVILA 
> adds GoogleAnalytics as a dependency on the Pods that work

what do you mean by this?

**Comment by KAIOAVILA** [comment]
> @KAIOAVILA
> 
> > adds GoogleAnalytics as a dependency on the Pods that work
> 
> what do you mean by this?

I added GoogleAnalytics on the pods
config.xml
`<platform name="ios">
        <pod name="GoogleAnalytics" version="3.17.0" />
    </platform>`


I'm using the cordova-plugin-cocoapod-support plugin to add this dependency to pods

**Comment by billb037** [comment]
seems this has been an issue for quite awhile. is there a workaround or something that describes how to get beyond this?

**Comment by KAIOAVILA** [comment]
> seems this has been an issue for quite awhile. is there a workaround or something that describes how to get beyond this?

Didn't you solve it with the solution I passed above?

**Comment by billb037** [comment]
> > seems this has been an issue for quite awhile. is there a workaround or something that describes how to get beyond this?
> 
> @billb037 Didn't you solve it with the solution I passed above?

No it didn't solve it for me

**Comment by SebasWebDev** [comment]
@billb037 use the version 1.8.6 for now. That's the version right before this issue was introduced.

**Comment by victorsosa** [comment]
> cordova-plugin-cocoapod-support

This will need to be documented, thanks
