### ISSUE TITLE
Google Analytics and iOS 14.5 ATT requirements

### ISSUE THREAD

**Issue by bradical1379** [danwilson/google-analytics-plugin#591]
Even with the IDFA framework removed from my project, I am still getting my app rejected from Apple for failing to comply with their new App Transparency requirements. With the removal of the IDFA framework, shouldn't all of the data collected by anonymous and not necessarily fall under their requirements for their ATT policies?

Or, are we now required to prompt users that we are collecting their information in order to use this plugin?

**Comment by muuvmuuv** [comment]
We are required to prompt users! This is to protect everyone'c privacy! If this plugin is not going to implement a "request before track" we have to remove analytics at all...
