### ISSUE TITLE
Facing build error on Apple M1 Pro chip Mac Xcode, while choosing iOS Simulator. Issue only on build for simulator's, working fine for real devices.

### ISSUE THREAD

**Issue by andaralex** [danwilson/google-analytics-plugin#595]
OS: macOS Monterey Version 12.3
Chip: Apple M1 Pro

**Plugin Details:**
"cordova-plugin-google-analytics": "1.9.1",

"cordova": {
    "plugins": {
      "cordova-plugin-google-analytics": {
        "GMS_VERSION": "18.0.1"
      },
    "platforms": [
      "ios"
     ]
    },

Recently I changed my MacBook Pro with Apple M1 Chip. In my application, I have used the "google-analytics-plugin": 1.9.1 and getting below issue while build and run the iOS simulator:

<img width="1405" alt="Screenshot 2022-03-24 at 4 08 24 PM" src="https://user-images.githubusercontent.com/922142/159902029-8c90000a-8def-4f60-a5e2-91e27d7f465e.png">

**ld: in /Users/Alexandar.S/Documents/ionic_sample_app/test_app/platforms/ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a(TAGActualAdIdAccess.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/Alexandar.S/Documents/ionic_sample_app/test_app/platforms/ios/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

<img width="862" alt="Screenshot 2022-03-24 at 4 10 29 PM" src="https://user-images.githubusercontent.com/922142/159901233-34163e45-c2e4-4d28-893e-e32c42eaefe9.png">

Issue only on Xcode while choosing iOS simulator, on real iPhone devices working fine. Also build succeeded on Cordova CLI.
 
<img width="565" alt="Screenshot 2022-03-24 at 4 26 19 PM" src="https://user-images.githubusercontent.com/922142/159901830-7f54010c-c6a7-4911-92ad-c722cf3fc3ce.png">

**Note:** Same working on macOS Big Sur Intel chip machine having Xcode 12.

**Comment by victorsosa** [comment]
Yes you problem is with the architecture; the code is compiled for architecture arm64, but you are trying to compile it for a Apple M1 is an [ARM](https://en.wikipedia.org/wiki/ARM_architecture)-based

**Comment by victorsosa** [comment]
Trying removing this line `<pod name="GoogleIDFASupport" spec="3.14.0" />`; because it seems to be a versions conflict

**Comment by andaralex** [comment]
Thanks for your quick reply.
You are correct. As you said, it's version conflict. Now Xcode build succeeded and the app running in iOS simulators. 
**I made the below changes in plugin.xml file.**

**commented this line <pod name="GoogleIDFASupport" spec="3.14.0" /> 
and updated the GoogleAnalytics pod spec version to 3.20.0**

    <podspec>
      <config>
        <source url="https://cdn.cocoapods.org/"/>
      </config>
      <pods use-frameworks="true">
        <pod name="GoogleAnalytics" spec="3.20.0"/>
        
      </pods>
    </podspec>

    <pods use-frameworks="true">
      <pod name="GoogleAnalytics" spec="3.20.0"/>
      
    </pods>

<img width="1724" alt="Screenshot 2022-03-24 at 8 00 00 PM" src="https://user-images.githubusercontent.com/922142/159943831-00488337-a450-4885-9cd7-f03c690b47b4.png">

**Comment by andaralex** [comment]
Raised PR for this fix - https://github.com/danwilson/google-analytics-plugin/pull/596#issue-1180452809. Please review and merge it.
