### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by diptendulkar** [danwilson/google-analytics-plugin#604]
Hi, 

In my  Cordova  project, I am using analytics  plugin version 11.6.2, however, the build gets failed with the below error 

[13:26:51] FAILURE: Build failed with an exception.
[13:26:51] * What went wrong:
[13:26:51] Execution failed for task ':app:processReleaseManifest'.
[13:26:51] > Manifest merger failed : Attribute receiver#com.google.android.gms.analytics.AnalyticsReceiver@exported value=(true) from AndroidManifest.xml:28:42-65
[13:26:51]   	is also present at [com.google.android.gms:play-services-analytics:11.6.2] AndroidManifest.xml:27:108-132 value=(false).

**Comment by EYALIN** [comment]
@diptendulkar what is the exception?

**Comment by diptendulkar** [comment]
> 
 Manifest merger failed : Attribute receiver#com.google.android.gms.analytics.AnalyticsReceiver@exported value=(true) from AndroidManifest.xml:28:42-65

**Comment by EYALIN** [comment]
@diptendulkar do you have the latest version after my PR merged?

**Comment by diptendulkar** [comment]
I am using 11.6.1

**Comment by EYALIN** [comment]
the latest version is "1.9.1". from where did you take 11.6.1?

**Comment by diptendulkar** [comment]
Could not find com.google.android.gms:play-services-analytics:1.9.1

found 11 version on this link - https://github.com/danwilson/google-analytics-plugin#configuring-play-services-version

**Comment by EYALIN** [comment]
you mean GMS_VERSION is version 11 and not the Cordova analytics plugin

what version is the plugin you have?

**Comment by J-who** [comment]
I came across this today. Looks like this pull request fixes it: https://github.com/danwilson/google-analytics-plugin/pull/603 which isn't included in 1.9.1.

**Comment by mley** [comment]
Somehow the changes in the pull-request got messed up. The pull-request #603 add the `android:exported="true" attribute to the receiver element, which contains the intent-filter. 
```
 <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver" android:exported="true" android:enabled="true">
```
But in release 1.9.2 and the current version the attribute is on that element 🤷 

https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml#L68

Looks like the pull-request's change got un-done in this commit: https://github.com/danwilson/google-analytics-plugin/commit/b7112a63539732ae6f565770db4b296851bdb990

**Comment by ricardosohn** [comment]
> Somehow the changes in the pull-request got messed up. The pull-request #603 add the `android:exported="true" attribute to the receiver element, which contains the intent-filter.
> 
> ```
>  <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver" android:exported="true" android:enabled="true">
> ```
> 
> But in release 1.9.2 and the current version the attribute is on that element 🤷
> 
> https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml#L68
> 
> Looks like the pull-request's change got un-done in this commit: [b7112a6](https://github.com/danwilson/google-analytics-plugin/commit/b7112a63539732ae6f565770db4b296851bdb990)

I confirm this is happenning on version 1.9.2.
Should be an easy fix.

**Comment by ricardosohn** [comment]
It appears that that flag needs to be set to false instead of true.
I may have gotten ahead of myself on that PR.
That came from the previous commit that just removed the flag (which at that moment was set to true).

**Comment by victorsosa** [comment]
Nop, I just reopen this one
