### ISSUE TITLE
Which plugin to use GA4 ?

### ISSUE THREAD

**Issue by BenLaKnet** [danwilson/google-analytics-plugin#606]
I try to use this plugin with GA4 trackingID but it does not work.
Is it possible to use it or change to another ?

**Comment by e-peeyush** [comment]
1++

**Comment by neerajrk2509** [comment]
Can you please update us on this?

**Comment by websystems-dev** [comment]
+1

**Comment by angelvalay** [comment]
With this plugin, I tried to integrate it with the new GA4 tracking ID but the events are not recorded in the Google Analytics platform and have no errors in the integration. Is this plugin using Universal Analytics services and not GA4?

**Comment by stevesum** [comment]
+1

**Comment by erikyuzwa** [comment]
Unless I'm mistaken, it looks like GA4 support is being tracked in #613

**Comment by rafaelwake** [comment]
+1
