### ISSUE TITLE
How to Debug - No network calls and no debug output

### ISSUE THREAD

**Issue by zeusstl** [danwilson/google-analytics-plugin#61]
Thanks so much for your work on this project!

Looking for advice for debugging.

$ cordova -v
3.5.0-0.2.6
$ phonegap -v
3.5.0-0.20.10

How do you know when it is working? What is the console log output I should filter for when debugMode is set (in the installed app using chrome://inspect via usb debug)?
I don't see any debug output and no network calls.

1) Running "analytics" in my console gives the js object as below.
2) The js file is found. file://android_asset/www/plugins/com.danielcwilson.plugins.googleanalytics/www/analytics.js
3) No errors caught in try catch.
4) Tried with windows.analytics instead of just analytics.

**The code: (with a fake ga tracking id - my tests had a real number in there.)**
        $ionicPlatform.ready(function () {
            DEBUG && console.log( "app::run $ionicPlatform.ready" );
            if(typeof window.analytics !== "undefined") {
                DEBUG && console.log( "app::run window.analytics is defined" );
                try {
                    DEBUG && window.analytics.debugMode();
                    window.analytics.startTrackerWithId("UA-xxxxxxxx-x");
                } catch (e) {
                    console.log( "app::run window.analytics caught error: ", e );
                }
                window.analytics.startTrackerWithId("UA-xxxxxxxx-x");
            } else {
                DEBUG && console.log("app::run Google Analytics Unavailable");
            }  
        });

**analytics object in console:**
![screenshot 2014-12-18 15 17 05](https://cloud.githubusercontent.com/assets/5577624/5495144/037185c0-86c9-11e4-8271-8a29c9bca42b.png)

**Comment by jayeshjain24** [comment]
@danwilson could you please give an example as to how to debug. Where do I place my place my call back?

**Comment by jayeshjain24** [comment]
@danwilson : I just logged an alert message for success callback while doing ```window.analytics.startTrackerWithId("UA-xxxxxxxx-x");``` .  It did gave me success msg. But the data did not appear in Google analytics dashboard. Then I used https://github.com/ggendre/GALocalStorage and data appears on dashboard. I created the account around 36 hours ago. I am not sure whats wrong and why I cant see the data in my dashboard when I use this plugin.

Can you help?
