### ISSUE TITLE
1.9.3 release needed

### ISSUE THREAD

**Issue by Jay031** [danwilson/google-analytics-plugin#613]
Hi all,

I'm really curious, the 1.9.3 version should be released 3 months ago.
Any ideas when this is going to happen? 
Because now we use some hardcoded commit-hash in our npm to have a working version for our project.
We could really use an update, because a lot has been improved since 1.9.2 in September 2022

Cheers!

**Comment by EYALIN** [comment]
@Jay031 anyway this plugin is going to be deprecated in 1,July 2023 unless it will be changed to support GA4 (https://support.google.com/analytics/answer/10089681?hl=en)

I will start working on GA4 implementation soon

**Comment by bcolflesh** [comment]
In for GA4 implementation if it happens.

**Comment by autodisk-kjelt** [comment]
Is there any prospect of a GA4 integration?

**Comment by EYALIN** [comment]
I didn't investigate deeply, but I'm sure we will find something.
I will work on the integration in the next weeks and update.

**Comment by autodisk-kjelt** [comment]
@EYALIN do you have a status update for us?

**Comment by EYALIN** [comment]
@autodisk-kjelt  unfortunately not yet.

**Comment by erikyuzwa** [comment]
would love it to for GA4 - new to plugin dev but is there anything I can contribute on @EYALIN ?

**Comment by EYALIN** [comment]
@erikyuzwa I'm trying to set it on native android, but I think it is based on the firebase analytics. I'm still investigating it.

**Comment by erikyuzwa** [comment]
> I'm still investigating it, and will update here

Okay cool, good luck @EYALIN!

**Comment by EYALIN** [comment]
@erikyuzwa @autodisk-kjelt @bcolflesh @Jay031  after a day working with GA4, i can see that the plugin works as expected.
I still need to understand how to implement exceptions tracking, but anyway, you have all the explanations here:
https://github.com/dpa99c/cordova-plugin-firebasex

using the GA4 for apps, means you are using Firebase.

I followed the Google guide: https://support.google.com/analytics/answer/9304153?hl=en#:~:text=start%20collecting%20data.-,Add%20a%20data%20stream,-Are%20you%20continuing

you can take a universal property in google analytics, and you will see there a button that says "create to GA4" and go from there to create for Android and IOS.

it was very simple, and if you have questions, please write them here and I will do my best to help.

also, I'm maintaining, expanding to more functionalities, and solving bugs in 13 Cordova plugins (working on more) and keep the code always up to date (IOS and Android), so you can follow my repos for Cordova here:
https://github.com/EYALIN?tab=repositories&q=community&type=&language=&sort=

**Comment by bcolflesh** [comment]
Thanks EYALIN, will read when I get a chance.

**Comment by erikyuzwa** [comment]
thanks @EYALIN I'll take a look as well 👍 🙇

**Comment by purinder-chawla-aristocrat** [comment]
thanks @EYALIN, please let us know when can we use #1.9.3 for GA4

**Comment by EYALIN** [comment]
@purinder-chawla-aristocrat you cannot use this plugin anymore.
I moved to https://github.com/chemerisuk/cordova-plugin-firebase-analytics and also installed the cordova crashalytics plugin, and both work great.
the moving to GA4 is not easy to understand, but you can watch some google webinars.

also, please take a look above in the link i sent on how to migrate the current analytics property

**Comment by victorsosa** [comment]
v1.9.3 released

**Comment by dmolinet-nexus** [comment]
@EYALIN 
So from July 1 this plugin will be deprecated? Is it not possible to use version 1.9.3 with GA4?
And if so, is it mandatory to create a Firebase project for GA4 to work with https://github.com/chemerisuk/cordova-plugin-firebase-analytics or is there some other plugin or alternative?

**Comment by chrux** [comment]
Mobile projects now are required to work through Firebase for Analytics
