### ISSUE TITLE
Plugin increases app size a lot

### ISSUE THREAD

**Issue by paweldziura** [danwilson/google-analytics-plugin#62]
Is it proper behaviour that that plugin increases app size by about 10mb even if it is built?
My built app has size ~4mb without the plugin and ~14mb with the plugin.

I am looking at file at myapp/platforms/ios/build/emulator/myapp.app

**Comment by zeusstl** [comment]
That doesn't sound right to me. Our app is under 5MB with the plugin.

**Comment by mediavrog** [comment]
The plugin if used for IOS will include an SDK library file from Google, namely the `libGoogleAnalyticsServices.a`, which is around 11 MB

**Comment by danwilson** [comment]
Closing, as pointed out by @mediavrog iOS file size gets big due to a sizable library.  Thanks.
