### ISSUE TITLE
Assigning trackView to dimensions

### ISSUE THREAD

**Issue by dilignt** [danwilson/google-analytics-plugin#64]
Unless I misunderstand the API, I can't see a way of assigning a view to a custom dimension.  The API has the addCustomDimension method, and looking at the code all of these custom dimensions are applied to every trackView.  But what if I want to assign different dimension values to different trackView calls?

For example, in my app I have several lists of screens that I call trackView on, and I want to add a custom dimension of the list name, so I can filter the screen name by list name in Google Analytics.  How would I do that with the API as it currently stands?  Or have I missed something?

many thanks

**Comment by danwilson** [comment]
The way custom dimensions work now, they are applied every time as you stated.  I'm not really familiar with custom dimensions, but I do think that how it works now will not allow you to do what you are wanting... though it's definitely a valid use case from what I've seen.  A PR would be appreciated in this case if you or someone who has a better understanding than me of how this feature works in GA.

**Comment by dilignt** [comment]
Thanks for your reply.

So looking at the implementation I thought the custom dimension
implementation it would actually be OK for pageviews, provided that you
were wanting to add values for the same dimension to every page view.  But
I need to track events as well, which aren't applicable to my custom
dimension, but all the custom dimensions are added to trackView and
trackEvent regardless, so this is not right.

In any case, having tried it out, as soon as I add a single custom
dimension the tracker stops working and no further views or events are
submitted to Google.  So there seems to be a bug somewhere.

If I get more time I can have a play with the Android code and see if I can
get a working implementation.  I don't have experience with IOS or Windows
Phone though, and I've never done a pull request before, but I share any
working with a gist perhaps?  (I've not done a gist before either)
