### ISSUE TITLE
Google Campaign Measurement Available?

### ISSUE THREAD

**Issue by stephengardner** [danwilson/google-analytics-plugin#68]
I have a phonegap based app, looking to integrate with a google marketing campaign.
From google's website: https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns it says there are some steps that need to be taken to the native sdk code to make campaigns work.  Has this been integrated at all?  Is it in the works?  On hold?  I'm evaluating either going the native route or sticking with this plugin.

**Comment by vlaraort** [comment]
Can you please include this @danwilson ? It's very interesting, and I can't make It work with Anu2g solution due to cordova5 and playservices problems.

**Comment by raviagarwal292** [comment]
@danwilson could you please add a feature for campaign tracking as its one of the most important and killer feature for anyone to know where their app installation is coming from. 

Reference link [How do I implement Campaign tracking with Cordova?](url)

Regards
Ravi Agarwal

**Comment by victorsosa** [comment]
@raviagarwal292 thanks for you interest, please do not spam.

**Comment by victorsosa** [comment]
PR sent

**Comment by victorsosa** [comment]
Checkout v1.5.0

**Comment by escolhatecnologia** [comment]
i  need   get  value   from  "referrer"  INSTALL_REFERRER

**Comment by victorsosa** [comment]
@escolhatecnologia please check the new method on the readme:
`window.ga.getVar('cn', function(result){ console.log(result);})`

**Comment by wo-github** [comment]
Can someone help me with some basic explanations to get the parameter in a phonegap app?

My index.js starts with:

```
var App = {
    init: function () {
        if (document.URL.indexOf("http://") === -1) {
            App.testing_on_desktop = false;
        }
        // Datenbank
        App.db = window.openDatabase("WODB", "1.0", "WO App DB", 5*1024*1024);
        App.db.transaction(populateDB, errorCB, successCB);
        jQuery(document).ready(function () {
            $.support.cors = true;
            var deviceReadyDeferred = jQuery.Deferred();
            var jqmReadyDeferred    = jQuery.Deferred();
            App.version;
            App.hideMainMenu;
            App.realtimePush;
            App.pushNotificationId;
            App.landscapeWrong = false;
            App.db.transaction(getCommunityThemes, errorCB, successCB);
            App.db.transaction(getNewsGrids, errorCB, successCB);
            App.db.transaction(getInstGrids, errorCB, successCB);
            if (App.testing_on_desktop) {
                _onDeviceReady();
                deviceReadyDeferred.resolve();
            } else {
                if( typeof(navigator.splashscreen) != 'undefined' ) {
                    navigator.splashscreen.show();
                }
                document.addEventListener("deviceready", function () {
                    window.open = cordova.InAppBrowser.open;
                    if( screen.orientation.type == 'landscape-primary' || screen.orientation.type == 'landscape-secondary' ) {
                      App.landscapeWrong = true;
                    }
                    window.addEventListener("orientationchange", orientationChanged);
                    window.ga.startTrackerWithId('TRACKERID', 30);
                    trackEvent('App', 'Action', 'Open App');
                    cordova.getAppVersion().then(function (version) {
                        App.version = version;
                        window.ga.setAppVersion(version);
                        App.servers.public.query('checkVersion', {'version':App.version}, function (response) {
                          if( !response ) {
                            alert('Diese Version wird nicht mehr unterstützt! Bitte aktualisieren Sie die App über den AppStore.', function() {
                              navigator.app.exitApp();
                            });
                          }
                        });
                    });
                    window.ga.getVar('referrer', function(result){ console.log(result);})
                    window.ga.getVar('utm_source', function(result){ console.log(result);})
                    window.ga.getVar('cn', function(result){ console.log(result);})
```


I add my app with `phonegap run android` to my device, after running this command, the app is open.
In the first console I add `adb logcat CordovaLog:* CordovaWebViewClient:* *:S` to get some output from my app.
And in a second console I send
`adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n [id from config.xml]/com.google.android.apps.analytics.CampaignTrackingReceiver --es "referrer" "utm_source%3DtestSource%26utm_medium%3DtestMedium%26utm_term%3DtestTerm%26utm_content%3DtestContent%26utm_campaign%3DtestCampaign"`
to simulate the install referrer.
But I receive nothing.
How it`s possible to receive some information from the install url and to get the referrer parameter?
