### ISSUE TITLE
Difference with GAPlugin

### ISSUE THREAD

**Issue by zmandel** [danwilson/google-analytics-plugin#69]
Whats the difference with GAPlugin? https://github.com/phonegap-build/GAPlugin/
I see that both have recently been modified. Is this explained somewhere? (sorry I didnt find it)

**Comment by danwilson** [comment]
This plugin is completely separate, built by different contributors.  GAPlugin uses different versions of the Google Analytics SDK.  We try to keep this up to date with the latest iOS and Android SDKs.
