### ISSUE TITLE
idfa class missing, won't collect idfa

### ISSUE THREAD

**Issue by kurtommy** [danwilson/google-analytics-plugin#70]
i receive this error, any suggestions?
used with ngCordova in the same way of the example!
http://ngcordova.com/docs/plugins/googleAnalytics/

**Comment by MarcGodard** [comment]
I also get this error...

**Comment by kurtommy** [comment]
some suggestion please?

**Comment by danwilson** [comment]
Do you have any more information or logs for this?  When do you receive this error?
Some StackOverflow searches show that people had issues with the 3.0.8 release of GA.  This is now on release 3.0.10... could you see if this is still an issue?

**Comment by jkufrin** [comment]
I just downloaded your plugin last week on 2-17, which should have all the latest code, right? I'm getting this error too. "idfa class missing, won't collect idfa" only shows up once, right before my first GA call. I can't tell if it's actually causing any problems yet though. GA is getting my posts. The app is still in dev and hasn't been submitted to the store yet.

**Comment by kurtommy** [comment]
For me the error persist but adding this line:
cordovaGoogleAnalytics.trackView('name of the view');
GA track my views

**Comment by danwilson** [comment]
Closing this, as it appears to not actually cause any issues and is just letting the dev know that idfa is not being collected.

**Comment by cmarrero01** [comment]
I have the same issue only for IOS 

idfa class missing, won't collect idfa

**Comment by ChristineZheng** [comment]
Have you figure it out? I have the same situation.
