### ISSUE TITLE
Using Custom Dimensions

### ISSUE THREAD

**Issue by flinn** [danwilson/google-analytics-plugin#71]
When setting Custom Dimensions using this plugin, does the "key" parameter need to match the Custom Dimension's "Name" property in GA or does it need to be `dimension1` or `dimension2` to match the "Index" property of the Custom Dimension much like the web-based JS SDK requires you to do? 

For example, if you create your first Custom Dimension in GA and label it as "Username" then Google provides this sample code for you to set that Custom Dimension up within your application for reporting...

`var dimensionValue = 'SOME_DIMENSION_VALUE';`
`ga('set', 'dimension1', dimensionValue);`

That documentation is for a web app using the Universal Analytics library, but it seems that their iOS and Android SDKs work the same... So, should the plugin be used like this: 

`window.analytics.addCustomDimension('dimension1',  user.username, mySuccessCB, myErrorCB)`

Or, would it be used like this:

`window.analytics.addCustomDimension('Username', user.username, mySuccessCB, myErrorCB)`

Orrrr, am I completely misunderstanding all of this? :smile:

Thanks! Enjoying this plugin so far, great work.

**Comment by flinn** [comment]
False alarm! Sorry...

I just took a closer look at the Objective-C code and compared it to Google's UA documentation for setting dimensions in iOS and realized that the correct way to set Custom Dimensions using this plugin is actually like this... 

`window.analytics.addCustomDimension('1', user.username, mySuccessCB, myErrorCB)`

If you'd like, I will push an update to this plugin that makes it more obvious that the KEY parameter is solely the Index of the Custom Dimension by making the "addCustomDimension" function take an integer rather than a string and labeling it "dimensionIndex" rather than "key". Just let me know what your thoughts are!

Best,
Matt

**Comment by matteocasadei** [comment]
+1
Thanks

**Comment by Lesego** [comment]
nice catch. Thanks

**Comment by krik** [comment]
+1

**Comment by cemerson** [comment]
Ugh ... I was assuming dimension "name" not "index" as well and just waited the "data freshness" 24 hour delay to see if my addCustomDimension calls worked ... but they didn't. Glad to find this thread at least - thanks for posting this catch/detail. Hope it works this time!

**Comment by srparakh** [comment]
How to send the track pageView along with the dimension? do we have to send it together like this -
$scope.$on('$ionicView.beforeEnter', function() {
analytics.addCustomDimension('Gender', 'female');
analytics.trackView('Search Schedules');
});

**Comment by gatkinsNZ** [comment]
You just set it once (in the session), and then it will be sent with every
subsequent track call (e.g. trackView) during that session.

If you change the custom dimension value during the session, then only the
new value will apply for that whole session,

**Comment by marcgarreau** [comment]
Bump. This really should make it to the README. I like @flinn's suggestion of `dimensionIndex`.

**Comment by barocsi** [comment]
How can I revoke a custom dimension from subsequent tracks?

**Comment by gatkinsNZ** [comment]
Custom dimensions in effect apply only once per session. If you change the
value in the middle of a session, then the previous value is overwritten.

So you can't really revoke it from 'subsequent' tracks, other than to set
it to an empty string which would wipe it for the whole session.

**Comment by rafaelbiten** [comment]
I would also add this to the docs. I just spent quite some time debugging and trying to understand why this wasn't working...

**Comment by victorsosa** [comment]
Please everybody read the issue #95, I think the solution is there and we need a new feature for this

**Comment by victorsosa** [comment]
@barocsi check my post

**Comment by barocsi** [comment]
@victorsosa thanks!

**Comment by victorsosa** [comment]
Fix  for sessions issue related to #195

**Comment by victorsosa** [comment]
@srparakh addCustomDimension() method need to be called only ones by dimension, after that every hit will be added to that custom dimension.

**Comment by victorsosa** [comment]
To all, PR #292 to fix the parameter issue with the custom metric. 
But still we need the fix for issue #95 about the sessions and customs metrics.

**Comment by victorsosa** [comment]
PR #292 seems not to be the right fix base on what we need.

**Comment by victorsosa** [comment]
Readme doc was updated to avoid confusion using the key: 
```
To add a Custom Dimension
* `window.ga.addCustomDimension('Key', 'Value', success, error)`
* Key should be integer index of the dimension i.e. send `1` instead of `dimension1` for the first custom dimension you are tracking.
* e.g. `window.analytics.addCustomDimension(1, 'Value', success, error)`
```

**Comment by victorsosa** [comment]
From ver 1.6.0 we have a fix for issue:
_Custom dimensions in effect apply only once per session. If you change the value in the middle of a session, then the previous value is overwritten._

now you can create  a new session using a parameter of newSession for 
`
public trackView(screen:String, campaingUrl?:string, **newSession?:boolean**, successCallback?:Function, errorCallback?:Function):void;`

`public trackEvent(category:String, action:String, label?:String, value?:Number, **newSession?:boolean**, successCallback?:Function, errorCallback?:Function):void;`

**Comment by Lightning3105** [comment]
Is this the same for custom metrics? Do you use the index for the metric (eg 1) or the metric name (eg 'metric1')
