### ISSUE TITLE
i get error on ios when i am trying to make build

### ISSUE THREAD

**Issue by roysG** [danwilson/google-analytics-plugin#72]
clang: error: no such file or directory: '/Users/Admin/www/picktags.com/public_html/picktagsApp/platforms/ios/picktagsApp/Plugins/com.danielcwilson.plugins.googleanalytics/UniversalAnalyticsPlugin.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

I installed as you instructed on readme page

**Comment by RafaelLeonhardt** [comment]
me too.

**Comment by flinn** [comment]
Alternatively you can download the Google Analytics SDK for iOS, unzip it and then copy the "UniversalAnalyticsPlugin.m" file within it into your existing iOS project and then using Xcode go to your Project Settings and click the "General" tab, click the "+" button under 'Linked Libraries and Frameworks' and add that file there so it gets built/linked to your project.

**Comment by danwilson** [comment]
Building off @flinn 's answer, sometime the Cordova CLI fails to add the linking.  See Issue #11 for more information and see if that resolves your issue.
