### ISSUE TITLE
Support for Apple mandate for 64-Bit compatibility

### ISSUE THREAD

**Issue by clevercommute** [danwilson/google-analytics-plugin#73]
Hi - 

We love this plug in. It's been a huge help for a project we are trying to get off the ground. 
One snag we hit...as we build using "Phone Gap Build" 
It gives us this error  
"Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture" 

Any thoughts on a resolution? 

Thanks! 

--Josh

**Comment by joshthompson** [comment]
I have just encountered this issue as well.

**Comment by danwilson** [comment]
64bit support has been in the iOS Google Analytics SDK since version 3.03, which has been in the plugin since at least April 2014.  

What version of the plugin are you using?

**Comment by clevercommute** [comment]
Just to be clear (in case it matters), we are talking about PhoneGapBuild...the Adobe hosted service.
My developer is sucessful when using 0.6.1 locally....but it 0.6.1 fails on PGB

**Comment by joshthompson** [comment]
I was using 2.3.1. I will update this with the next content push.
To confirm, should I set this to 3.03 or 3.0.3?
Thanks for your help.

**Comment by danwilson** [comment]
I apologize for not following up on this sooner... how are you installing this plugin with PhoneGap Build? Are you using: `<gap:plugin name="com.danielcwilson.plugins.googleanalytics" version="0.6.1" source="plugins.cordova.io" />` ?
