### ISSUE TITLE
Problem Installing google analytics plugin 

### ISSUE THREAD

**Issue by chrisjul** [danwilson/google-analytics-plugin#74]
Hey problem occur in installing plugin , i can't install google analytics plugin , my cordova version 3.6 
am geeting this error 1) failed to install com.danielcwilson.plugins.googleanalytics and  2) google play service.jar already exists please help me

Thanks Advances 
Christopher

**Comment by danwilson** [comment]
I'm looking into this now... for an immediate workaround, you can install an earlier version of the plugin (that will use Android's Google Analytics SDK v3 instead of v4):

`cordova plugin add com.danielcwilson.plugins.googleanalytics@0.6.1`

**Comment by chrisjul** [comment]
Hey wilson thank you for your solution. now i have facing another problem, your plugin not installed,  the error messages already plugin installed ,
![capture](https://cloud.githubusercontent.com/assets/3796117/6388300/5f8d5f1a-bdbe-11e4-8163-368da1a87774.PNG)

 here i have attached screenshot for your reference

**Comment by chrisjul** [comment]
now working fine. no more issue thanks danwilson i want to support your project please add more feature  to plugin
