### ISSUE TITLE
additional google play services for android not at api lvl 21

### ISSUE THREAD

**Issue by heggemille** [danwilson/google-analytics-plugin#76]
hi, when i add your plugin it will also add com.google.playservices for android explicit at api level 19. i want to update my complete project so i want to use cordova 3.7.1 with api level 21. other plugins using this lib need it on level 21. why do you explicit use level 19? this prevents me from updating

**Comment by mlegenhausen** [comment]
+1

**Comment by heggemille** [comment]
seems to fix it temporary with installing "cordova plugin add com.google.playservices@latest" before and after installing GA Plugin

**Comment by piernik** [comment]
+1

**Comment by quanghoc** [comment]
I got v21 of Google Playservices and it is still error.

**Comment by danwilson** [comment]
Closed with #118
