### ISSUE TITLE
analytics not defined

### ISSUE THREAD

**Issue by boolino** [danwilson/google-analytics-plugin#78]
after installing the plugin via  
"cordova plugin add https://github.com/danwilson/google-analytics-plugin.git" 
when I try to use it i get the following error: 
 -> error:TypeError: Cannot call method 'debugMode' of undefined

the code:
var app = {
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady(), true);
    },
    onDeviceReady: function() {
        try{
            window.analytics.debugMode();
        }catch(e){
            console.log("error:"+e);
        }
    }
};

I'ts strange because the spinnerDialog was installed in the same way and I'm calling it with window.plugins.spinnerDialog and it works, or the barcodescanner with cordova.plugins.barcodescaner , but analitycs doesn't work with none of them.

Do I have to copy some file, or define anything else??

**Comment by danwilson** [comment]
Please check Issue #11 to see if that clears up your issue.  Sometimes the Cordova CLI does not add the files properly for iOS
