### ISSUE TITLE
Plugin won't work on Anrdoid phones without Play Services

### ISSUE THREAD

**Issue by keval5531** [danwilson/google-analytics-plugin#80]
...so what is/are the prerequisite(s) for the plugin to work on iOS? I checked Google's documentation; but being less familiar with iOS development, I am not sure if there'd come such issues.
 
I tested the plugin in my Ionic application on multiple devices. And it worked on most, except one which does not have Play Services installed. On this device, the app didn't load the template which had a analytics function within and app was stuck at a blank white screen.
To be honest, the thought of "_plugin won't work without play services_" doesn't bother me. 

But I wanted to know if this was normal, and how does this work with iOS?

**Comment by danwilson** [comment]
iOS does not use Google Play Services - GPS is an Android-specific library.  
The latest version of Google Analytics for Android requires Google Play Services, so if that device does not have access to it (such as an Amazon phone) it likely will not work.  This plugin just builds on top of the SDK, so if the SDK does not have access, neither will this plugin sadly.
