### ISSUE TITLE
WP8 support

### ISSUE THREAD

**Issue by G3z** [danwilson/google-analytics-plugin#82]
is it possible to support Windows Phone 8 ?

**Comment by Fowowski** [comment]
+1 

I am also interested in this.

**Comment by danwilson** [comment]
Only iOS and Android have official SDKs, so for right now WP8 is not supported in this plugin (see Issue #20).  @dpolivy has an older fork where he was adding WP8 with an unofficial SDK that will likely be pulled in here once it is ready.

**Comment by dpolivy** [comment]
Here's my fork: https://github.com/dpolivy/google-analytics-plugin. I've been meaning to update it and provide a PR, will see if I can work on that now given the interest. Stay tuned.

**Comment by dpolivy** [comment]
OK, I've now got a PR for the latest version of the plugin. Please give it a try and let me know if you have any issues.

https://github.com/danwilson/google-analytics-plugin/pull/89
