### ISSUE TITLE
IP Anonymization

### ISSUE THREAD

**Issue by modul4richard** [danwilson/google-analytics-plugin#83]
hi.. our client wants to have IP Anonymization activated. is that possible?

**Comment by danwilson** [comment]
This is not available currently, but can be added.  Marking as enhancement for tracking.

**Comment by modul4richard** [comment]
cool, thanks

**Comment by wenzerl** [comment]
Coming back on this issue.
As our customer really wants to have this feature integrated, i may ask you, to please contact me directly. I would gladly contribute and hope to hear from you soon.
Werner

**Comment by Hirbod** [comment]
+1

**Comment by Freundschaft** [comment]
+1

**Comment by julio6114** [comment]
Have you got create a pull request to include this feature ?

Thanks

**Comment by victorsosa** [comment]
Fixed, thanks @Freundschaft
