### ISSUE TITLE
Rename secondary dimension's app name

### ISSUE THREAD

**Issue by Fowowski** [danwilson/google-analytics-plugin#84]
After sending data to the ecommerce (I literally used two methods addTransaction & addTransactionItem) I can see after choosing App Name from Secondary dimension select list (in analytics Transactions tab) that my App name is probably taken from the config.xml.

Is there any option to pass data to analytics that will contain customized app name?
I use phonegap and I have grunt-phonegap-build task that is handling the build process for me - it basically makes the zip file and sends it to build.phonegap.com where it's compiled for ios, windows and android.

Could I do something like described here: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#apptracking

**Comment by danwilson** [comment]
This is not available currently, but it is possible to add to the plugin.  Marking this as an enhancement for tracking.

**Comment by victorsosa** [comment]
This could be implemented using:
https://developers.google.com/android/reference/com/google/android/gms/analytics/Tracker.html#setAppName(java.lang.String)

**Comment by victorsosa** [comment]
You can do this using the method setVar since ver 1.8.0
