### ISSUE TITLE
Getting error undefined is not a function and a.getTime is not a function on User Engagement section of Google Analytics dashboard.

### ISSUE THREAD

**Issue by rohitsre** [danwilson/google-analytics-plugin#90]
I'm getting both above mentioned error on App Overview section under block User Engagement.
![google_analytics_issue](https://cloud.githubusercontent.com/assets/9881857/7111090/d3407882-e1d8-11e4-8e38-36580d0f511c.png)

**Comment by danwilson** [comment]
Are you getting any errors in the app's debug consoles when you run the app?  This seems like it is not an issue with the plugin.

**Comment by rohitsre** [comment]
I'm getting below data in the app's debug console
![gettime](https://cloud.githubusercontent.com/assets/9881857/7140861/6ffe017c-e2eb-11e4-878f-530879fcbe5b.png)


2015-04-14 21:08:34.181 Mofluid[14053:225931] VERBOSE: GoogleAnalytics 3.10 -[GAIBatchingDispatcher persist:] (GAIBatchingDispatcher.m:497): Saved hit: {
    parameters =     {
        "&_crc" = 0;
        "&_u" = ".ojL";
        "&_v" = "mi3.1.0";
        "&a" = 1006055059;
        "&aid" = "com.demo.app";
        "&an" = Demo;
        "&av" = "0.0.1";
        "&cd" = Demo;
        "&cid" = "709a5295-aa2b-4c7b-bd61-5953f637d6fc";
        "&ds" = app;
        "&sr" = 375x667;
        "&t" = timing;
        "&tid" = "UA-61824192-1";
        "&ul" = en;
        "&utc" = Demo;
        "&utl" = Hits;
        "&utt" = 249428;
        "&utv" = AppUser;
        "&v" = 1;
        "&z" = 11214849990108044888;
        gaiVersion = "3.10";
    };
    timestamp = "2015-04-14 15:38:34 +0000";
}

**Comment by rohitsre** [comment]
Now it's showing session from 4 other countries. How it could be possible ?. I've not released my app not play store yet.

![country](https://cloud.githubusercontent.com/assets/9881857/7154493/3928a70e-e374-11e4-9be0-45988a537833.png)

**Comment by rohitsre** [comment]
Issue resolved now I was not passing any variable to track user timing
