### ISSUE TITLE
Is there a way to remove google analytics?

### ISSUE THREAD

**Issue by felquis** [danwilson/google-analytics-plugin#91]
In a moment of my application I need GA to stop tracking everything. 

For example, if the user logged it a tester, I'd like to send a event "Tester User detected" and remove tracking for these users...

Thanks.

**Comment by boynet** [comment]
put all the ga calls in function like:
function trackEvent(Category, Action, Label, Value){
if (!user.isTester) window.analytics.trackEvent('Category', 'Action', 'Label', Value)
}

**Comment by felquis** [comment]
@danwilson @boynet's suggestion is one part of the solution, but GA still tracking sessions and session time.
