### ISSUE TITLE
Installing Plugin in Visual Studio for Cordova fails

### ISSUE THREAD

**Issue by garsidestephen** [danwilson/google-analytics-plugin#93]
Hi, I have been trying unsuccessfully to install your plugin to a cordova project via Visual Studio / Github.  Visual Studio just crashes with no error. Eventually traced it to the plugin.xml file being invalid.  Just needs xmlns:android="http://schemas.android.com/apk/res/android" adding to the opening <plugin tag.

cheers

**Comment by danwilson** [comment]
Thanks - merged PR #94 to resolve this
