### ISSUE TITLE
"Could not connect to the server" on iPhone but works fine in iPhone Simulator

### ISSUE THREAD

**Issue by grgarside** [danwilson/google-analytics-plugin#97]
Everything works fine in the iPhone Simulator, but on an actual iPhone, I get the following message repeated constantly after attempting to trackView:

> INFO: GoogleAnalytics 3.10 -[GAIBatchingDispatcher didSendHits:response:data:error:] (GAIBatchingDispatcher.m:205): Dispatch error: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo=0x1742e0080 {NSUnderlyingError=0x17025fb60 "Could not connect to the server.", NSErrorFailingURLStringKey=https://ssl.google-analytics.com/batch, NSErrorFailingURLKey=https://ssl.google-analytics.com/batch, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}

How should I start to debug this? I don't know if this is just my iPhone, as I don't have any other physical device to try this on.

**Comment by grgarside** [comment]
Never mind, my /etc/hosts was blocking it, oops :see_no_evil:

**Comment by cemerson** [comment]
Hey @grgarside can you explain what your fix was? I'm getting this error too but no idea what /etc/hosts would be on my iPhone or why I'd need to fuss with it (?).

**Comment by cemerson** [comment]
Just to follow-up / add detail... 

I am in the same/similar boat to @grgarside because this plugin works fine in my iOS Simulator (iPhone 5 iOS 9 for example) and I can see the Real-Time SCREEN data coming in ... but when testing on my actual device (iPhone 6 iOS 8.x) no Real-Time data comes in and I keep getting the below errors (each time the GA interval comes around). Could someone please help? Am I missing a framework or is this some kind of SSL/Transport issue? I don't know what /etc/hosts is. Thank you in advance.

````
2015-08-04 08:52:25.374 App[...] GoogleAnalytics 3.10 
	-[GAIRequestBuilder requestPostUrl:payload:compression:]
		(GAIRequestBuilder.m:167): building URLRequest for https://ssl.google-analytics.com/batch

2015-08-04 08:52:25.377 App[...] GoogleAnalytics 3.10 
	-[GAIBatchingDispatcher dispatchWithCompletionHandler:]
		(GAIBatchingDispatcher.m:612): Sending hit(s) POST: https://ssl.google-analytics.com/batch

2015-08-04 08:52:25.401 App[...] GoogleAnalytics 3.10 
	-[GAIBatchingDispatcher didSendHits:response:data:error:]
		(GAIBatchingDispatcher.m:205): Dispatch error: Error Domain=NSPOSIXErrorDomain Code=2 
			"The operation couldn’t be completed. No such file or directory" UserInfo=0x174c6e2c0 {NSErrorFailingURLStringKey=https://ssl.google-analytics.com/batch, NSErrorFailingURLKey=https://ssl.google-analytics.com/batch, _kCFStreamErrorCodeKey=2, _kCFStreamErrorDomainKey=1}
````

**Comment by cemerson** [comment]
Ok just to answer my question (in case someone else encounters the same) - for me it had something to do with the fact that the iPhone I was testing on was jailbroken (*Sorry but until Apple puts "Disable Auto-Lock" in the 1-swipe menu, I still need my [CCControls!](http://www.igeeksblog.com/cccontrols-possibly-the-best-ios-7-control-center-customization-cydia-tweak/)* ) . 

Anyhow once I rebooted to [Safe Mode](https://cydia.saurik.com/safemode/) [GAIBatchingDispatcher.m] stopped throwing the Dispatch error. No idea on the why or how here... but at least I found how to work around it.

**Comment by grgarside** [comment]
@cemerson Apologies for missing the notification but glad to hear you resolved the problem too. My device is also jailbroken and I had added a number of ad servers to my /etc/hosts file to block them and one of them was google-analytics.com, thereby inadvertently blocking my own analytics.

**Comment by cemerson** [comment]
Thanks @grgarside 
Nice to know it's probably my ad-blocking apps/tweaks - disabling those will be easier than going into safemode - thanks!
