### ISSUE TITLE
Difficulty with Ionic Framework

### ISSUE THREAD

**Issue by carpiediem** [danwilson/google-analytics-plugin#98]
I haven't been able to get this plugin working on my project, so I tried installing it on a very simple version.
```
ionic start gaPluginTest sidemenu
cd gaPluginTest
cordova plugin add https://github.com/danwilson/google-analytics-plugin.git
ionic platform add android
```
I inserted this code into the .run $ionicPlatform.ready functions in app.js:
```
if(typeof analytics !="undefined") {
    analytics.startTrackerWithId("UA-MYCODE-1");
} else {
    console.log("Google Analytics Unavailable");
}
```
and I added to the controllers provided by [Ionic's starter app](https://github.com/driftyco/ionic-starter-sidemenu):
```
.controller('PlaylistsCtrl', function($scope) {
  $scope.gaStatus = "Waiting";
  $scope.playlists = [
    { title: 'Reggae', id: 1 },
    { title: 'Chill', id: 2 },
    { title: 'Dubstep', id: 3 },
    { title: 'Indie', id: 4 },
    { title: 'Rap', id: 5 },
    { title: 'Cowbell', id: 6 }
  ];
  
  if(typeof analytics !="undefined") {
    analytics.trackView("All Playlists");
    $scope.gaStatus = "Sent";
  }
  else {$scope.gaStatus = "Failed";}
})

.controller('PlaylistCtrl', function($scope, $stateParams) {
  $scope.gaStatus = "Waiting";
  if(typeof analytics !="undefined") {
    analytics.trackView("Single Playlist");
    $scope.gaStatus = "Sent";
  }
  else {$scope.gaStatus = "Failed";}
});
```
I also added `{{gaStatus}}` to the templates for debugging.  Finally, I installed on my phone.
```
cordova build android
adb install platforms\android\ant-build\MainActivity-debug.apk
```

Here's the problem: when I ran the app and watched the [Real-Time data](https://www.google.com/analytics/web/?hl=en#realtime/rt-screen) on Google Analytics, I receive pageviews for `Single Playlist`, but not for `All Playlists`.  On-screen, the list of playlists says `Failed`, while the detail page says `Sent`.  Do you know what might be happening differently in these two controllers?

**Comment by TrevorJTClarke** [comment]
I am having this issue as well. Seems the library doesnt install correctly, or may need an update with the ionic version of Cordova. Any ideas??

**Comment by firoze** [comment]
I just ran into this issue...a few seconds ago. I found a way around it by wrapping the plugin call inside `$ionicPlatform.ready` like so:

```
$ionicPlatform.ready(function () {
   if(typeof analytics !="undefined") {
      analytics.trackView("All Playlists");
      $scope.gaStatus = "Sent";
   } else {
      $scope.gaStatus = "Failed";
   }
});
```

Try this out and let me know what happens. I'm curious to know why this has to happen...but it could be an issue on Ionic, and not the plugin itself.

**Comment by carpiediem** [comment]
I tried it in the Ionic tabs starter app, adding {{gaStatus}} to the template.  The variable was successfully sent to Sent, but there still isn't any data in the GA website.

Just to verify, the code you posted above was in a controller, right?

**Comment by TrevorJTClarke** [comment]
I was able to get it to work. 

Two things to note:

    - GA takes up to 15 minutes to find a new device!! (I found this on a blog)
    - You must call the startTrackerWithId & trackView together inside $ionicPlatform.ready

$ionicPlatform.ready(function() {

    if (typeof analytics !== 'undefined'){
        analytics.startTrackerWithId('UA-62340913-4');
        analytics.trackView('Init');
    } else {
        console.log("Google Analytics not loaded");
    }

});

**Comment by firoze** [comment]
That is right. Although, you will need to do `analytics.startTrackerWithId('UA-62340913-4');` only once...in 

```
angular.module(...).run(function($ionicPlatform){
   // here...I think?
});
```

**Comment by carpiediem** [comment]
It looks like you're right.  I never saw the data on the Real-Time screen, but yesterday's tests do show up in the the data now.  The 15 minute delay is strange, but thanks for your help.

**Comment by pallaviMN** [comment]
@carpiediem , can u plese let me how to track multiple views in ionic app with single tracker ID.

**Comment by carpiediem** [comment]
@pallaviMN , I didn't wind up using GA very much, but it should work if you do two things:

1. Initialize the plugin in a module(...).run() block (say, in app.js)
2. Run analytics.trackView(viewName) in your controllers

Remember that this will not work when you use `ionic serve` to test in a browser.  It will only work when you build and run on a device or emulator.

**Comment by Sumirmat97** [comment]
@carpiediem I have done all that is mentioned above, still getting not results. Even waited for 20 mins.

**Comment by carpiediem** [comment]
@Sumirmat97 , beyond what I wrote above I don't remember what I did. I don't have access to the code I was working with at the time anymore, either. Sorry I couldn't be more help.

**Comment by firoze** [comment]
@Sumirmat97 can you show some snippet of your code (controller, module etc)
